SixLabors/ImageSharp

src/ImageSharp/Colors/Color.cs, src/ImageSharp/PixelAccessor.cs, tests/ImageSharp.Tests/Colors/ColorTests.cs, tests/ImageSharp.Tests/project.json
@JimBobSquarePants I figured I'd take a shot at fixing this per our discussion yesterday. Let me know what you think about this approach. I added an additional test that ensures the bytes are laid out as expected in memory.
=> Ensure Color structure stores elements in RGBA order

.editorconfig, README.md, src/ImageSharp/Colors/PackedPixel/Argb.cs, tests/ImageSharp.Tests/Colors/PackedPixelTests.cs
Adds support for ARGB packed pixels.
=> Added Argb IPackedPixel

src/ImageSharp/Drawing/Paths/InternalPath.cs, src/ImageSharp/Drawing/Shapes/ComplexPolygon.cs, src/ImageSharp/Drawing/Shapes/Polygon.cs, tests/ImageSharp.Tests/Drawing/LineComplexPolygonTests.cs
Think I managed to make a tiny perf boost to complex polygons... and i think I managed to same a little bit of memory in the process.
Method |       Mean |    StdDev | Scaled | Scaled-StdDev |     Gen 0 |    Gen 1 |    Gen 2 | Allocated |
---------------------------- |----------- |---------- |------- |-------------- |---------- |--------- |--------- |---------- |
'Complex Polygon - Master' | 11.6810 ms | 0.0674 ms |   1.00 |          0.00 | 9422.9167 | 672.9167 | 672.9167 |  35.13 MB |
'Complex Polygon - Updated' |  6.6927 ms | 0.2831 ms |   0.57 |          0.02 |  706.2500 | 677.0833 | 677.0833 |   7.63 MB |`
=> Optimise polygon merging in complex polygons

src/ImageSharp/Colors/PackedPixel/IPackedPixel.cs, src/ImageSharp/Drawing/Brushes/Brushes`2.cs, src/ImageSharp/Drawing/Brushes/PatternBrush`2.cs, src/ImageSharp/Drawing/Draw.cs, src/ImageSharp/Drawing/DrawImage.cs, src/ImageSharp/Drawing/Fill.cs, src/ImageSharp/Drawing/Processors/DrawPathProcessor.cs, src/ImageSharp/Drawing/Processors/FillShapeProcessor.cs, src/ImageSharp/Drawing/Shapes/LinearPolygon.cs, src/ImageSharp/Formats/Gif/GifEncoderCore.cs, src/ImageSharp/Formats/Jpg/Components/Bits.cs, src/ImageSharp/Formats/Jpg/Components/Block8x8F.cs, src/ImageSharp/Formats/Jpg/Components/Bytes.cs, src/ImageSharp/Formats/Jpg/JpegDecoderCore.cs
I noticed the project had 124 stylecop warnings, so I fixed a few (down to 70 after this PR). Would be great to fix all and set warnings as errors on the project to get build time protection on this.
=> Adding missing documentation and fixing style issues.

CodeCoverage.runsettings, ImageSharp.sln, tests/ImageSharp.Tests/project.json
Visual Studio code coverage wasn't working for me due to some missing Shim dll so I fixed it - by adding MS codecoverage as a dependency. 
I also added a runsettings file to make sure only the right dlls end up in the coverage. You will need to import this from Test - TestSettings - Select test settings file 😄
=> Enable Visual Studio code coverage

tests/ImageSharp.Tests/Colors/ColorEqualityTests.cs
I added unit tests for:
- Equals
- Not equals
- HashCode equals
- HashCode not equals 
Found some strange behaviour on HashCode when two colours of the same type and seemingly different initialization values (and Vector4 values) seem to have the same hash code. See `NotEqualityDataDifferentObjects`  and lines with `// same hashcode??` comment.
=> Adding unit tests for equality and hash code for IPackedPixel types

src/ImageSharp/Colors/ColorspaceTransforms.cs, src/ImageSharp/Colors/Spaces/CieLab.cs, src/ImageSharp/Colors/Spaces/CieXyz.cs, src/ImageSharp/Colors/Spaces/Cmyk.cs, src/ImageSharp/Colors/Spaces/Hsl.cs, src/ImageSharp/Colors/Spaces/Hsv.cs, src/ImageSharp/Colors/Vector4BlendTransforms.cs, src/ImageSharp/Common/CommonConstants.cs, src/ImageSharp/Common/Constants.cs, src/ImageSharp/Common/Helpers/ImageMaths.cs, src/ImageSharp/Drawing/Processors/DrawPathProcessor.cs, src/ImageSharp/Drawing/Processors/FillShapeProcessor.cs, src/ImageSharp/Filters/Processors/Effects/BackgroundColorProcessor.cs, src/ImageSharp/Filters/Processors/Transforms/RotateProcessor.cs, src/ImageSharp/Quantizers/Wu/WuQuantizer.cs, tests/ImageSharp.Tests/Common/ConstantsTests.cs
I noticed we had a bunch of `private const float Epsilon = 0.001F;` duplicated throughout the code, and I see no reason why that shouldn't be in a common place.
I put it in the `Common` namespace, not sure how you feel about that. I fixed ColorSpaces and Transforms to use it, but there are a few more which I can fix if you guys think this is worth doing 😄 
Also added a test to protect the value, if that is accidentally changed we could be in quite some trouble.
=> Refactoring Epsilon const value to remove duplication.

src/ImageSharp.Drawing/project.json, src/ImageSharp.Formats.Bmp/project.json, src/ImageSharp.Formats.Gif/project.json, src/ImageSharp.Formats.Jpeg/project.json, src/ImageSharp.Formats.Png/project.json, src/ImageSharp.Processing/project.json, src/ImageSharp/project.json, tests/ImageSharp.Benchmarks/project.json
The downgrade from 4.6.1 to 4.6 in the benchmark is required to force
the System.Numerics.Vectors dependency to NuGet. The 4.6.1 version
does not contain the used generic vector type.
I have no idea if additional changes are required so that this profile ends up in the NuGet packages.
Closes #81
=> Add a .NET 4.6.1 profile to use its System.Numerics.Vectors

src/ImageSharp/Colors/Color.cs, src/ImageSharp/Colors/PackedPixel/Alpha8.cs, src/ImageSharp/Colors/PackedPixel/Argb.cs, src/ImageSharp/Colors/PackedPixel/Bgr565.cs, src/ImageSharp/Colors/PackedPixel/Bgra4444.cs, src/ImageSharp/Colors/PackedPixel/Bgra5551.cs, src/ImageSharp/Colors/PackedPixel/Byte4.cs, src/ImageSharp/Colors/PackedPixel/HalfSingle.cs, src/ImageSharp/Colors/PackedPixel/HalfTypeHelper.cs, src/ImageSharp/Colors/PackedPixel/HalfVector2.cs, src/ImageSharp/Colors/PackedPixel/HalfVector4.cs, src/ImageSharp/Colors/PackedPixel/NormalizedByte2.cs, src/ImageSharp/Colors/PackedPixel/NormalizedByte4.cs, src/ImageSharp/Colors/PackedPixel/NormalizedShort2.cs, src/ImageSharp/Colors/PackedPixel/NormalizedShort4.cs, src/ImageSharp/Colors/PackedPixel/Rg32.cs, src/ImageSharp/Colors/PackedPixel/Rgba1010102.cs, src/ImageSharp/Colors/PackedPixel/Rgba64.cs, src/ImageSharp/Colors/PackedPixel/Short2.cs, src/ImageSharp/Colors/PackedPixel/Short4.cs
Specially the ones that do packing/unpacking!
However, I'm not sure if all CLR implementations are capable of inlining methods on generic `TColor` arguments. Definitely works on the one that executes benchmarks on Windows :P
**Before**
```
Method |       Mean |    StdDev | Scaled | Scaled-StdDev | Allocated |
---------------------------- |----------- |---------- |------- |-------------- |---------- |
'System.Drawing Resize' | 53.3980 ms | 1.1966 ms |   1.00 |          0.00 |     512 B |
'ImageSharp Resize' | 35.9191 ms | 0.2008 ms |   0.67 |          0.02 | 186.06 kB |
'ImageSharp Compand Resize' | 59.7976 ms | 0.2730 ms |   1.12 |          0.02 | 186.74 kB |
```
**After**
```
Method |       Mean |    StdDev | Scaled | Scaled-StdDev | Allocated |
---------------------------- |----------- …
```
=> Inline PackedPixel primitive methods

README.md, src/ImageSharp/Image.cs, src/ImageSharp/Image/Image{TColor}.cs, src/ImageSharp/project.json, tests/ImageSharp.Tests/Formats/Bmp/BitmapTests.cs, tests/ImageSharp.Tests/Image/ImageTests.cs, tests/ImageSharp.Tests/TestFile.cs
The change entails adding a new target to the core ImageSharp package targeting netstandard .3, and adding a define to the netstandard1.1 target to allow conditional compilation.
In netstandard1.3+ we now have a dependency on `System.IO.FileSystem` this allows us to add a constructors to Image that take in a file path instead of a stream simplifying the boiler plate required to creating a file. It additionally allows us to add `Image.Save(path)` as an API that saves the file to the named path (looking up the correct image format, based on file's extension, from the formats loaded in to the `Configuration`)
This will simplify how a proportion of users will make use of the API but doesn't break compatibility with netstandard1.1 just doesn't have the nice path based APIs available.
How the …
=> Added file path based APIs to Image & Image<TColor>

src/ImageSharp.Processing/Overlays/Glow.cs, src/ImageSharp.Processing/Overlays/Vignette.cs, src/ImageSharp.Processing/Processors/Binarization/BinaryThresholdProcessor.cs, src/ImageSharp.Processing/Processors/Binarization/ErrorDiffusionDitherProcessor.cs, src/ImageSharp.Processing/Processors/Binarization/OrderedDitherProcessor.cs, src/ImageSharp.Processing/Processors/ColorMatrix/LomographProcessor.cs, src/ImageSharp.Processing/Processors/ColorMatrix/PolaroidProcessor.cs, src/ImageSharp.Processing/Processors/Overlays/GlowProcessor.cs, src/ImageSharp.Processing/Processors/Overlays/VignetteProcessor.cs, src/ImageSharp/Colors/Color.cs, src/ImageSharp/Colors/ColorBuilder{TColor}.cs, src/ImageSharp/Colors/NamedColors{TColor}.cs, tests/ImageSharp.Tests/Colors/ColorDefinitionTests.cs, tests/ImageSharp.Tests/Colors/ColorTests.cs, tests/ImageSharp.Tests/Image/PixelAccessorTests.cs
I noticed during the dithering PR that we had usages of the below patter for wellknown colors.
```c#
TColor packed = default(TColor);
packed.PackFromBytes(255, 255, 255, 255);
```
I've added 2 new classes, and fix up all the places that are using the above syntax where I can find them to use the improved syntax.
Additionally fixed up the Glow & Vignette usages to remove the usage of passing a default(TColor) around and then trying to compare to it, it seemed dangerous to me as whatever color default(TColor) actually ends up as could be what you want the glow to be and as it stood you could never use it.
Provides convenience methods for creating new `TColor`s from RGB byte and Hex strings allowing users to create any color using those mechanisms. 
provides static readonly representations …
=> Add NamedColors<TColor> and ColorBuilder<TColor>

.vscode/tasks.json, README.md
Because I develop on Linux I noticed the library builds, but came without support for the Linux .Net Core IDE. I added two tasks: _build_ and _test_ and linked it to `ctrl + shift + b`.
=> Support for VSCode

src/ImageSharp.Drawing/Brushes/Brushes{TColor}.cs, src/ImageSharp.Drawing/Brushes/ImageBrush{TColor}.cs, src/ImageSharp.Drawing/Brushes/PatternBrush{TColor}.cs, src/ImageSharp.Drawing/Brushes/Processors/BrushApplicator.cs, src/ImageSharp.Drawing/Brushes/RecolorBrush{TColor}.cs, src/ImageSharp.Drawing/Brushes/SolidBrush{TColor}.cs, src/ImageSharp.Drawing/GraphicsOptions.cs, src/ImageSharp.Drawing/ImageSharp.Drawing.csproj, src/ImageSharp.Drawing/Paths/ShapeRegion.cs, src/ImageSharp.Drawing/Processors/FillRegionProcessor.cs, src/ImageSharp.Drawing/Region.cs, src/ImageSharp.Drawing/Text/TextGraphicsOptions.cs, src/ImageSharp/Common/Memory/BufferPointer{T}.cs, tests/ImageSharp.Benchmarks/Drawing/FillPolygon.cs, tests/ImageSharp.Tests/Drawing/FillPatternTests.cs, tests/ImageSharp.Tests/Drawing/FillRegionProcessorTests.cs, tests/ImageSharp.Tests/Drawing/Paths/ShapeRegionTests.cs, tests/ImageSharp.Tests/Drawing/SolidBezierTests.cs, tests/ImageSharp.Tests/Drawing/SolidComplexPolygonTests.cs, tests/ImageSharp.Tests/Drawing/SolidPolygonTests.cs, tests/ImageSharp.Tests/Drawing/Text/TextGraphicsOptionsTests.cs
Swap out the fill region processor to use a much more accurate sub-pixel rendering technique.
This new renderer is a tiny bit slower than the old one, but (and its a big but) it totally removes the Parrallel looping making it entirely single threaded.
``` ini
BenchmarkDotNet=v0.10.1, OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i5-6200U CPU 2.30GHz, ProcessorCount=4
Frequency=2343752 Hz, Resolution=426.6663 ns, Timer=TSC
[Host]     : Clr 4.0.30319.42000, 64bit RyuJIT-v4.6.1637.0 [AttachedDebugger]
DefaultJob : Clr 4.0.30319.42000, 64bit RyuJIT-v4.6.1637.0
```
|                        Method |       Mean |    StdErr |    StdDev | Scaled | Scaled-StdDev |     Gen 0 |    Gen 1 |    Gen 2 | Allocated |
|------------------------------ |----------- |---------- |---------- …
=> improve vector/glyph rendering quality using a sub-pixel rendering techinique

src/ImageSharp.Drawing/Text/DrawText.cs, src/ImageSharp.Drawing/Text/TextGraphicsOptions.cs, tests/ImageSharp.Tests/Drawing/Text/DrawText.cs
This changes the default behavior to by defaulting all text to be drawn as 72 dpi as apposed to the images native resolution thus ensuing that the pixel height per point is consistent across images by default.
Can be switched back to image resolution by setting `UseImageResolution` in `TextGraphicsOptions` to `true`.
This change will prevent confusion for people dealing with images in terms of pixels instead of sizes dependent on DPI.
72 dpi was chosen is because 1 pt = 1/72 inch.
Fixes #148
=> Default text drawing at an image dpi independent size

src/ImageSharp/Formats/Png/PngEncoderCore.cs, src/ImageSharp/Formats/Png/PngInterlaceMode.cs, tests/ImageSharp.Tests/Drawing/FillRegionProcessorTests.cs, tests/ImageSharp.Tests/Formats/Png/PngEncoderTests.cs, tests/ImageSharp.Tests/Formats/Png/PngSmokeTests.cs, tests/ImageSharp.Tests/ImageComparer.cs, tests/ImageSharp.Tests/Processors/Filters/GrayscaleTest.cs, tests/ImageSharp.Tests/TestUtilities/Attributes/WithTestPatternImageAttribute.cs, tests/ImageSharp.Tests/TestUtilities/ImageProviders/BlankProvider.cs, tests/ImageSharp.Tests/TestUtilities/ImageProviders/FileProvider.cs, tests/ImageSharp.Tests/TestUtilities/ImageProviders/SolidProvider.cs, tests/ImageSharp.Tests/TestUtilities/ImageProviders/TestImageProvider.cs, tests/ImageSharp.Tests/TestUtilities/ImageProviders/TestPatternProvider.cs, tests/ImageSharp.Tests/TestUtilities/ImagingTestCaseUtility.cs, tests/ImageSharp.Tests/TestUtilities/TestImageExtensions.cs
This adds a helper image comparer class to testing to help us turn some of our none tests into real unit tests.
Add a couple of png smoke tests that encode and then decode an image in png then does a visual compare to verify they render the same as an example on how to use the comparer.
=> Add image comparer test helper

src/ImageSharp.Drawing/Brushes/ImageBrush{TColor}.cs, src/ImageSharp.Drawing/Paths/RectangleExtensions.cs, src/ImageSharp.Drawing/Pens/Pen{TColor}.cs, src/ImageSharp.Drawing/Processors/FillRegionProcessor.cs, src/ImageSharp/Colors/ColorspaceTransforms.cs, src/ImageSharp/Colors/PackedPixel/Bgr565.cs, src/ImageSharp/Colors/PackedPixel/NormalizedShort2.cs, src/ImageSharp/Colors/PackedPixel/NormalizedShort4.cs, src/ImageSharp/Colors/PackedPixel/Rgba1010102.cs, src/ImageSharp/Colors/PackedPixel/Rgba64.cs, src/ImageSharp/Colors/PackedPixel/Short2.cs, src/ImageSharp/Colors/PackedPixel/Short4.cs, src/ImageSharp/Colors/Spaces/CieLab.cs, src/ImageSharp/Colors/Spaces/Cmyk.cs, src/ImageSharp/Colors/Spaces/Hsl.cs, src/ImageSharp/Colors/Spaces/Hsv.cs, src/ImageSharp/Colors/Vector4BlendTransforms.cs, src/ImageSharp/Common/Extensions/Vector4Extensions.cs, src/ImageSharp/Common/Helpers/ImageMaths.cs, src/ImageSharp/Common/Helpers/MathF.cs, src/ImageSharp/Processing/Processors/Convolution/Convolution2DProcessor.cs, src/ImageSharp/Processing/Processors/Effects/BackgroundColorProcessor.cs, src/ImageSharp/Processing/Processors/Effects/OilPaintingProcessor.cs, src/ImageSharp/Processing/Processors/Overlays/GlowProcessor.cs, src/ImageSharp/Processing/Processors/Overlays/VignetteProcessor.cs, src/ImageSharp/Processing/Processors/Transforms/ResamplingWeightedProcessor.cs, src/ImageSharp/Processing/Processors/Transforms/RotateProcessor.cs, src/ImageSharp/Processing/Transforms/Options/ResizeHelper.cs, src/ImageSharp/Quantizers/Octree/Quantizer.cs, tests/ImageSharp.Tests/Helpers/MathFTests.cs
This update updates all existing code that used floating point `System.Math` methods to use our own internal `MathF` class. This reduces the noise in the codebase, makes intent more obvious and improves testability of the libraries.
I've aggressively inlined each method so there should be no slowdown.
I can add extra tests for the new class but I think the increased coverage from it's use should probably be enough.
=> Update to use MathsF

src/ImageSharp/IO/BigEndianBitConverter.cs, src/ImageSharp/IO/LittleEndianBitConverter.cs, tests/ImageSharp.Tests/IO/BigEndianBitConverter.ToTypeTests.cs, tests/ImageSharp.Tests/IO/LittleEndianBitConverter.ToTypeTests.cs
Fixing a bug where the ToInt16/32/64 methods ignored the startIndex parameter and always used 0.
=> Fix for ignored startIndex parameter in EndianBitConverter ToInt16/32/64 methods

src/ImageSharp/Formats/Png/PngDecoderCore.cs
Fixes #166 meaning that index pngs offset the first pixel of each row and fill that value with what ever color is in index 0 of the palette.
I think this is correct based on the fact we always add an extra byte to the scanline and when we encode the bytes with skip the first index.
See https://github.com/JimBobSquarePants/ImageSharp/blob/7d348667d6341e6a770e607cae94ff68df0176bc/src/ImageSharp/Formats/Png/Filters/NoneFilter.cs#L40
and https://github.com/JimBobSquarePants/ImageSharp/blob/7d348667d6341e6a770e607cae94ff68df0176bc/src/ImageSharp/Formats/Png/PngDecoderCore.cs#L350
_**DISCLAIMER** I don't know enough about the png format to know which side is correct should the first item be skipped or is it a bug in the encoder putting writing the scanline at the wrong location._
=> Fix for off by one for indexed pngs

src/ImageSharp/Formats/Png/IPngEncoderOptions.cs, src/ImageSharp/Formats/Png/PngEncoderCore.cs, src/ImageSharp/Formats/Png/PngEncoderOptions.cs, tests/ImageSharp.Tests/Formats/Png/PngSmokeTests.cs
Fixes how we generate the alpha channel for Indexed PNGs.
Based on info from [the W3C png spec](https://www.w3.org/TR/PNG/#11transinfo) the alpha channel should have an entry per index entry (if any alpha required).
This leaves me with the understanding that a `Threshold` amount doesn't make much sense but left it in for now but changed its default so it retains the entire set of values.
Applying this fix makes me notice 2 things;
1. The OctreeQuantizer seems to introduce some odd difference in the alpha values of the indexed 
pixels.
2. The OctreeQuantizer will produce compound errors between encodings even if the the number of different colors in the image is already below the threshold. i.e. encode indexed, decode, and with no changes encode as indexed again does not produce exactly …
=> Fix alpha channel generation for indexed PNGs

src/ImageSharp/Colors/Spaces/Conversion/Implementation/Lms/CieXyzAndLmsConverter.cs, tests/ImageSharp.Tests/Colors/Colorspaces/RgbAndCieXyzConversionTest.cs
- [ x ] I have written a descriptive pull-request title
- [ x ] I have verified that there are no overlapping [pull-requests](https://github.com/JimBobSquarePants/ImageSharp/pulls) open
- [ x ] I have verified that I am following matches the existing coding patterns and practise as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [ x ] I have provided test coverage for my change (where applicable)
You forgot the Transpose for the Bradford matrix
Note: Some unit tests still fail due to limited floating point precision, but the actual values are correct, only the last digit is missing in your tests.
=> Add Missing Transpose for Bradford matrix

src/ImageSharp/Formats/Png/PngDecoderCore.cs, src/ImageSharp/Formats/Png/PngEncoderCore.cs, src/ImageSharp/Formats/Png/PngHeader.cs, src/ImageSharp/Formats/Png/Zlib/Adler32.cs, src/ImageSharp/Formats/Png/Zlib/DeframeStream.cs
Stop the copy from deframing to inflate
Removed the pixel by pixel processing for RgbWithAlpha
Cleaned up the Crc check on the inflated stream
Down from ~4x slower than the native System.Drawing method to ~2.5x slower.
=> Performance improvements for PNG Decoding

src/ImageSharp/Formats/Jpeg/Components/Decoder/YCbCrToRgbTables.cs, src/ImageSharp/Formats/Jpeg/Components/Encoder/RgbToYCbCrTables.cs, src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs, src/ImageSharp/Formats/Jpeg/JpegEncoderCore.cs, tests/ImageSharp.Tests/Colors/RgbaVectorTransformTests.cs
This PR improves the accuracy of our YCbCr->Rgb->YcbCr conversions by using the same approach to building lookup tables that libjpeg turbo does. There's very little speed difference to our prior methods ~0.5ms on encode. 
See the following for reference.
https://github.com/libjpeg-turbo/libjpeg-turbo/blob/077e5bb4e0f6761c034e7c1f7e7a4120f580f1a0/jdcolor.c#L211
https://github.com/libjpeg-turbo/libjpeg-turbo/blob/077e5bb4e0f6761c034e7c1f7e7a4120f580f1a0/jccolor.c#L198
With this merged I believe we can close #82 and #155
Here's a comparision between the System.Drawing and Previous ImageSharp outputs and our new one.
**System.Drawing**
**ImageSharp Current 1.0.0-alpha7-00012**
**This PR**
You'll notice the green tint is completely gone and the image much more clear.
=> Use same conversion methods as libjpeg

src/ImageSharp/Common/Helpers/DebugGuard.cs, src/ImageSharp/Common/Helpers/Guard.cs, src/ImageSharp/Formats/Png/Filters/AverageFilter.cs, src/ImageSharp/Formats/Png/Filters/NoneFilter.cs, src/ImageSharp/Formats/Png/Filters/PaethFilter.cs, src/ImageSharp/Formats/Png/Filters/SubFilter.cs, src/ImageSharp/Formats/Png/Filters/UpFilter.cs, src/ImageSharp/Formats/Png/PngDecoderCore.cs, src/ImageSharp/Formats/Png/PngEncoder.cs, src/ImageSharp/Formats/Png/PngEncoderCore.cs
This PR replaces the old `fixed` png filters with methods utilizing `BufferSpan<byte>` + `Unsafe.Add` to bring the format codebase more inline with the newer memory access struct approach.
=> Use Bufferspan + Unsafe.Add for png filters

src/ImageSharp/Image/Image.LoadPixelData.cs, src/ImageSharp/PixelFormats/PixelOperations{TPixel}.cs, tests/ImageSharp.Tests/Image/ImageLoadTests.cs
We've have multiple people recently asking how to push the raw pixel data into imagesharp.
So I've added a couple of new methods (with multiple overloads) of `Image.LoadPixelData(...)`
There are 2 variants one that takes `TPixel[]` and another taking `byte[]`. The version taking `byte[]` processes the bytes as raw memory holding pixel data based on which ever `TPixel` is being used, thus if you have a `byte[]` holding data in argb32 you would have to load that using `Image.LoadPixelData<Argb32>(...)` etc.
=> Load from pixel data methods

src/ImageSharp.Drawing/Pens/Pen{TPixel}.cs, src/ImageSharp.Drawing/Processors/DrawPathProcessor.cs, src/ImageSharp/Numerics/Matrix3x2Extensions.cs, src/ImageSharp/Numerics/Point.cs, src/ImageSharp/Numerics/PointF.cs, src/ImageSharp/Numerics/Rectangle.cs, src/ImageSharp/Numerics/RectangleF.cs, src/ImageSharp/Numerics/Size.cs, src/ImageSharp/Numerics/SizeF.cs, src/ImageSharp/Processing/Processors/Overlays/GlowProcessor.cs, src/ImageSharp/Processing/Processors/Overlays/VignetteProcessor.cs, src/ImageSharp/Processing/Processors/Transforms/RotateProcessor.cs, src/ImageSharp/Processing/Processors/Transforms/SkewProcessor.cs, tests/ImageSharp.Benchmarks/Samplers/Glow.cs, tests/ImageSharp.Tests/Numerics/PointFTests.cs, tests/ImageSharp.Tests/Numerics/PointTests.cs, tests/ImageSharp.Tests/Numerics/RectangleFTests.cs, tests/ImageSharp.Tests/Numerics/RectangleTests.cs, tests/ImageSharp.Tests/Numerics/SizeFTests.cs, tests/ImageSharp.Tests/Numerics/SizeTests.cs
This PR expands on the core primitives `Point`, `PointF`, `Size`, `SizeF`, `Rectangle` and `RectangleF` to add equivalent functionality from System.Drawing. Fixing #227 
Additional the following casting is possible.
- `Rectangle` -> implicit `RectangleF`, `Vector4`
- <strike>`Vector4` <-> implicit `RectangleF`</strike>
- `RectangleF` -> explicit `Rectangle`
- `Point` -> implicit `PointF`, `Vector2`
- `Point` -> explicit `Size`
- `Vector2` <-> implicit `PointF`
- `PointF` -> explicit `Point`, `SizeF`
- `Size` -> implicit `SizeF`
- `Size` -> explicit` Point`
- `SizeF` -> explicit `Size`
All explicit casting from `F` equivalents uses truncation to match existing behavior when explicitly casting from real to integer types.
I've not touched up on changing API calls since we do not use, nor …
=> Expand and test primitives

src/ImageSharp/Processing/Processors/Transforms/ResamplingWeightedProcessor.Weights.cs, src/ImageSharp/Processing/Processors/Transforms/ResamplingWeightedProcessor.cs, tests/ImageSharp.Tests/Processing/Transforms/ResizeProfilingBenchmarks.cs
Fixes #219 by removing the `Span<float>` from the heap utilizing a method call instead.
We incur the cost of creating two spans per `Ptr` request now but the benchmarks still show a 2x speedup over System.Drawing  so I'm comfortable with that. As always, open to better ideas.
=> Remove WeightsWindow.Span

src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs
We failed to ensure we had read all the bytes of a marked segment when we had decided to skip processing an App2 marker due to it not containing the correct header.
I think this is correct, it seems to work and allows me to load up and resize the photo in issue #238 
Fixes #238
=> Ensure we consume stream when failing to read ICC profile

src/ImageSharp/MetaData/Profiles/ICC/IccReader.cs, src/ImageSharp/MetaData/Profiles/ICC/IccWriter.cs, tests/ImageSharp.Tests/MetaData/Profiles/ICC/IccReaderTests.cs, tests/ImageSharp.Tests/MetaData/Profiles/ICC/IccWriterTests.cs, tests/ImageSharp.Tests/TestDataIcc/IccTestDataProfiles.cs
An ICC profile can reuse the same data for multiple tag data entries. This pull request changes the reader to only read each entry once and improves how the writer finds and writes those duplicate entries.
For reference: https://github.com/JimBobSquarePants/ImageSharp/issues/217#issuecomment-301795153
=> Read and write duplicate ICC tag data entries only once

src/ImageSharp/MetaData/Profiles/ICC/DataReader/IccDataReader.TagDataEntry.cs, src/ImageSharp/MetaData/Profiles/ICC/DataWriter/IccDataWriter.TagDataEntry.cs, tests/ImageSharp.Tests/MetaData/Profiles/ICC/DataReader/IccDataReader.TagDataEntryTests.cs, tests/ImageSharp.Tests/MetaData/Profiles/ICC/DataWriter/IccDataWriter.TagDataEntryTests.cs, tests/ImageSharp.Tests/TestDataIcc/IccTestDataTagDataEntry.cs
Reading and writing a multilocalized unicode tag data entry is now more careful about cultures.
When reading:
- an empty language code results in an invariant culture
- an empty country code results in a culture from the language code only
- there's no change when both codes are available
When writing:
- an invariant culture writes "xx" as language code and leaves the country code empty
- a culture with a language only uses that and leaves the country code empty
- no change with a culture with both language and country code
The text of an an entry with duplicate texts but different cultures is only written once now to reduce the size of the profile.
This works because every single culture is stored with an accompanying offset for the text. So multiple cultures can have the same offset and …
=> Refactor reading and writing of ICC multilocalized unicode tag data entry

tests/ImageSharp.Sandbox46/ImageSharp.Sandbox46.csproj, tests/ImageSharp.Tests/Colorspaces/ColorSpaceEqualityTests.cs, tests/ImageSharp.Tests/Image/PixelAccessorTests.cs, tests/ImageSharp.Tests/ImageSharp.Tests.csproj, tests/ImageSharp.Tests/PixelFormats/ColorDefinitionTests.cs
Minor change, but don't wan't to break working test runners for anyone, so created a PR.
- Updated xunit to 2.3.0-beta3-build3705
- Fixed name collisions reported by xunit analyzer
=> Updated xunit to 2.3.0-beta3-build3705, fixed errors reported by xunit analyzer

src/ImageSharp/Processing/Processors/Transforms/RotateProcessor.cs, tests/ImageSharp.Tests/Image/ImageRotationTests.cs
- [x ] I have written a descriptive pull-request title
- [x ] I have verified that there are no overlapping [pull-requests](https://github.com/JimBobSquarePants/ImageSharp/pulls) open
- [x ] I have verified that I am following matches the existing coding patterns and practise as demonstrated in the repository. These follow strict Stylecop rules :cop:.
- [x ] I have provided test coverage for my change (where applicable)
Fixed bug: Rotating an image by negative amount results in the wrong rotation. Switched to correct roation service. 
Fixes #269
=> Rotating an image by negative amount results in the wrong rotation

src/ImageSharp/MetaData/Profiles/ICC/DataReader/IccDataReader.TagDataEntry.cs, tests/ImageSharp.Tests/TestDataIcc/IccTestDataTagDataEntry.cs
On some OS versions creating a `CultureInfo` from an invalid culture throws a `CultureNotFoundException` while on others it accepts it.
This PR handles the exception by trying to create the full culture (languge and country), then trying language only and after that falling back to `CultureInfo.Invariant`
This fixes #304
=> Handle CultureNotFoundException when reading MultilocalizedUnicodeTagDataEntry

src/ImageSharp/Formats/Png/Filters/PaethFilter.cs, src/ImageSharp/Formats/Png/PngDecoderCore.cs
This pull request fixes a couple of issue that occur when decoding a PNG file. With these patches the images from #313 and #314 can be read. 
I have not tested if the images from #301 can be read on the beta-1 branch. Could you check if these patches also fix the tests in the beta-1 branch @JimBobSquarePants?
It is probably also wise to investigate if we don't have the same issues in the PNG encoder. Anyone?
=> Several fixes in the PNG decoder.

src/ImageSharp.Web/Middleware/ImageSharpMiddleware.cs
The current cache key computation doesn't use the `Request.PathBase` (which is like virtual path in IIS) or the domain. This creates collisions when two files with the same name are used in a multi-tenant system (see Orchard) and could leak voluntarily or involuntarily some images from other tenants.
=> Update cache key to handle multi-tenancy

src/ImageSharp.Web/Helpers/FormatHelpers.cs
Or you end up having to duplicate its code when implementing custom `IImageResolver`.
See https://github.com/OrchardCMS/Orchard2/blob/30c9b53b013861f2742c191e18f18c1bf09b93b6/src/OrchardCore.Modules/Orchard.Media/Processing/MediaFileSystemResolver.cs#L75
=> Making FormatHelpers public

src/ImageSharp.Drawing/ImageSharp.Drawing.csproj, src/ImageSharp/ImageSharp.csproj
updates package dependencies 
Current beta1 of ImageSharp.Drawing includes a copy of stylecop.json which is an artefact from an issue inside sixlabors.core. All dependent project are fixed to prevent it from being included here.
=> update dependencies to prevent stylecop.json being included in package

src/ImageSharp/Common/Extensions/StreamExtensions.cs, tests/ImageSharp.Tests/Common/StreamExtensionsTests.cs
This pull request fixes the issue with `StreamExtensions.Skip` reported in #338. Some unit tests have also been added for that method.
=> Added extra check to Skip for when the number of bytes read is not the same as the count

src/ImageSharp/Common/Tuples/Vector4Pair.cs, src/ImageSharp/Formats/Jpeg/Common/Block8x8.cs, src/ImageSharp/Formats/Jpeg/Common/Block8x8F.CopyTo.cs, src/ImageSharp/Formats/Jpeg/Common/Decoder/ColorConverters/JpegColorConverter.FromCmyk.cs, src/ImageSharp/Formats/Jpeg/Common/Decoder/ColorConverters/JpegColorConverter.FromGrayScale.cs, src/ImageSharp/Formats/Jpeg/Common/Decoder/ColorConverters/JpegColorConverter.FromRgb.cs, src/ImageSharp/Formats/Jpeg/Common/Decoder/ColorConverters/JpegColorConverter.FromYCbCr.cs, src/ImageSharp/Formats/Jpeg/Common/Decoder/ColorConverters/JpegColorConverter.FromYCbCrBasic.cs, src/ImageSharp/Formats/Jpeg/Common/Decoder/ColorConverters/JpegColorConverter.FromYCbCrSimd.cs, src/ImageSharp/Formats/Jpeg/Common/Decoder/ColorConverters/JpegColorConverter.FromYCbCrSimdAvx2.cs, src/ImageSharp/Formats/Jpeg/Common/Decoder/ColorConverters/JpegColorConverter.FromYccK.cs, src/ImageSharp/Formats/Jpeg/Common/Decoder/ColorConverters/JpegColorConverter.cs, src/ImageSharp/Formats/Jpeg/Common/Decoder/JpegImagePostProcessor.cs, src/ImageSharp/Formats/Jpeg/Common/SizeExtensions.cs, tests/ImageSharp.Benchmarks/Color/Bulk/PackFromVector4.cs, tests/ImageSharp.Benchmarks/Config.cs, tests/ImageSharp.Benchmarks/General/ArrayCopy.cs, tests/ImageSharp.Benchmarks/Image/EncodeBmpMultiple.cs, tests/ImageSharp.Benchmarks/Image/Jpeg/DecodeJpeg.cs, tests/ImageSharp.Benchmarks/Image/Jpeg/DecodeJpegMultiple.cs, tests/ImageSharp.Benchmarks/Image/Jpeg/EncodeJpeg.cs, tests/ImageSharp.Benchmarks/Image/Jpeg/EncodeJpegMultiple.cs, tests/ImageSharp.Benchmarks/Image/Jpeg/YCbCrColorConversion.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegColorConverterTests.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegProfilingBenchmarks.cs
- Managed to fight `Vector<T>` and now we have a special `JpegColorConverter.FromYCbCrSimdAvx2` execution path for AVX2-enabled (Haswell+) CPU-s with `Vector<float>.Count == 8`.
- The "old" `JpegColorConverter.FromYCbCrSimd` is capable of handling the `Vector<float>.Count == 4` path even when `Vector.IsHardwareAccelerated == false`. It's covered with it's own unit test.
- All converters were moved to the `ColorConverters` subfolder.
`JpegColorConverter.FromYCbCrSimdAvx2` is much faster on CPU-s supporting it:
```
Method |       Mean |     Error |    StdDev | Scaled | Allocated |
------------ |-----------:|----------:|----------:|-------:|----------:|
Scalar | 9,396.9 ns | 696.05 ns | 39.328 ns |   1.00 |       0 B |
SimdVector4 | 1,687.6 ns |  77.52 ns |  4.380 ns |   0.18 |       0 B | …
```
=> AVX2 optimization for Jpeg YCbCr color conversion

tests/ImageSharp.Tests/Formats/Png/PngDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs
=> Add missing test for #359

src/ImageSharp/Formats/Jpeg/GolangPort/JpegEncoderCore.cs, src/ImageSharp/Formats/Jpeg/JpegEncoder.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegEncoderTests.cs
This fixes #260 so that the behaviour matches `System.Drawing` which produces identical output for quality of 0 and 1.
=> Jpeg Quality 0 and 1 should be equal

src/ImageSharp.Drawing/Processors/DrawImageProcessor.cs, tests/ImageSharp.Tests/Drawing/DrawImageTest.cs
This PR fixes #252 where we weren't correctly handling negative x-offset values when drawing images.
=> Handle negative x offset for DrawImage

src/ImageSharp/Formats/Gif/FrameDecodingMode.cs, src/ImageSharp/Formats/Gif/GifDecoder.cs, src/ImageSharp/Formats/Gif/GifDecoderCore.cs, src/ImageSharp/Formats/Gif/GifEncoderCore.cs, src/ImageSharp/Formats/Gif/IGifDecoderOptions.cs, src/ImageSharp/Quantizers/OctreeQuantizer{TPixel}.cs, src/ImageSharp/Quantizers/QuantizerBase{TPixel}.cs, tests/ImageSharp.Tests/Formats/Gif/GifDecoderTests.cs, tests/ImageSharp.Tests/Quantization/QuantizedImageTests.cs
This PR was originally designed to simply add a `FrameDecodingMode` enumeration for decoding animated gifs but I discovered an inconsistency in quantization while I was cleaning up the codebase. 
As such I've combined the fix + tests to this PR.
=> Enable decoding  only single frame from animated gif + fix quantization issue

src/ImageSharp/Formats/Png/Zlib/Adler32.cs, src/ImageSharp/Formats/Png/Zlib/Crc32.cs, tests/ImageSharp.Benchmarks/Image/DecodePng.cs
Minor optimization of png hashing methods changes scaled performance from `2.48` to `2.40` relative to System.Drawing
Method |      TestImage |     Mean |    Error |    StdDev | Scaled | ScaledSD |   Gen 0 |   Gen 1 |   Gen 2 | Allocated |
--------------------- |--------------- |---------:|---------:|----------:|-------:|---------:|--------:|--------:|--------:|----------:|
'System.Drawing Png' | Png/splash.png | 3.949 ms | 3.165 ms | 0.1788 ms |   1.00 |     0.00 | 70.3125 | 70.3125 | 70.3125 | 240.51 KB |
'ImageSharp Png' | Png/splash.png | 9.765 ms | 4.235 ms | 0.2393 ms |   2.48 |     0.11 | 46.8750 |       - |       - |  96.94 KB |
Method |      TestImage |     Mean |     Error |    StdDev | Scaled | ScaledSD |   Gen 0 |   Gen 1 |   Gen 2 | Allocated |
--------------------- …
=> Minor png hashing optimizations

src/ImageSharp.Drawing/Processors/FillRegionProcessor.cs, tests/ImageSharp.Tests/Drawing/SolidPolygonTests.cs, tests/ImageSharp.Tests/Issues/Issue412.cs
Fixes #412
Add a pixel offset to account for the fact that outlining a line causes the rendered box to be +/- pine width/2 compared to origin which isn't intuitive as you would expect a 1 pixel wide line drawn from 1,1 to 1, 10 to fill in the the 2nd pixel in each row.
=> Offset pixel grid when rendering with anti-aliasing turned off

src/ImageSharp/DefaultInternalImageProcessorContext.cs, src/ImageSharp/Processing/Processors/CloningImageProcessor.cs, src/ImageSharp/Processing/Processors/Transforms/AffineTransformProcessor.cs, src/ImageSharp/Processing/Processors/Transforms/CropProcessor.cs, src/ImageSharp/Processing/Processors/Transforms/InterpolatedTransformProcessorBase.cs, src/ImageSharp/Processing/Processors/Transforms/ProjectiveTransformProcessor.cs, src/ImageSharp/Processing/Processors/Transforms/ResamplingWeightedProcessor.cs, src/ImageSharp/Processing/Processors/Transforms/TransformProcessorBase.cs, src/ImageSharp/Processing/Transforms/TransformHelpers.cs, tests/ImageSharp.Tests/Processing/Transforms/TransformsHelpersTest.cs
This PR introduces a helper method and base class to ensure that any EXIF dimensional metadata values are correctly updates should the dimensions of the image change. Fixes #423 and supersedes #424
=> Fix and standardize EXIF dimension transform updates

src/ImageSharp/PixelFormats/PackedPixelConverterHelper.cs, tests/ImageSharp.Tests/Image/ImageCloneTests.cs
A few of the newer pixel formats were missing from our conversion functions. This adds them.
=> Add missing pixel formats

src/ImageSharp/Dithering/ErrorDiffusion/ErrorDiffuserBase.cs, src/ImageSharp/Formats/Png/PngEncoder.cs, src/ImageSharp/Formats/Png/PngEncoderCore.cs, src/ImageSharp/Quantizers/QuantizerBase{TPixel}.cs, src/ImageSharp/Quantizers/WuQuantizer{TPixel}.cs, tests/ImageSharp.Tests/Quantization/QuantizedImageTests.cs
This PR fixes dithering of semi-opaque pixels. It also enables dithering by default for all quantizers.
Original:
Pre-Fix Output:
Fixed Output:
=> Fix and optimize error diffusion

src/ImageSharp/Common/Extensions/ComparableExtensions.cs, src/ImageSharp/Formats/Png/PngDecoderCore.cs, src/ImageSharp/Formats/Png/PngEncoderCore.cs, src/ImageSharp/Image/ImageFrame{TPixel}.cs
It appears that the issue reported in #439 is happening due to some odd bug in Mono. The problem is this line in `PngDecoderCore.cs`:
```C#
Swap(ref this.scanline, ref this.previousScanline);
```
Swapping these two buffers corrupts the value of `this.bytesPerScanline` and makes it `0`. I am guessing that some pointer magic is happening in the swap method that corrupts the value. I tried to reproduce the issue but I could only make it happen with our code and not a simple sample program. Maybe @akoeplinger from the Mono team could take a look at this and try to figure out why this corruption is happening. It can be reproduced  (at e4293f95b3876e51e9e82b8c47555ec91fec1694) with the first image of #439 and the code below. I used the `ImageSharp.Sandbox46` project to build and test it on …
=> Move swap to classes to avoid odd issues on Mono.

src/ImageSharp/Image/IImage.cs, src/ImageSharp/Image/Image{TPixel}.cs, tests/ImageSharp.Tests/ComplexIntegrationTests.cs, tests/ImageSharp.Tests/Formats/Bmp/BmpDecoderTests.cs, tests/ImageSharp.Tests/Formats/Bmp/BmpEncoderTests.cs, tests/ImageSharp.Tests/Formats/Gif/GifDecoderTests.cs, tests/ImageSharp.Tests/Formats/Gif/GifEncoderTests.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegEncoderTests.cs, tests/ImageSharp.Tests/Formats/Png/PngEncoderTests.cs, tests/ImageSharp.Tests/TestUtilities/ImageProviders/TestPatternProvider.cs, tests/ImageSharp.Tests/TestUtilities/ImagingTestCaseUtility.cs, tests/ImageSharp.Tests/TestUtilities/TestImageExtensions.cs, tests/ImageSharp.Tests/TestUtilities/Tests/TestImageProviderTests.cs
I really need better regression testing for codecs to unblock my work on #225. The following tests have been restructured to use reference images:
- BmpEncoderTests
- PngEncoderTests
- GifDecoderTests: 
Single frame tests + 2 multiframe tests using [one reference image per frame](https://github.com/SixLabors/Imagesharp.Tests.Images/tree/master/ReferenceOutput/GifDecoderTests/Decode_VerifyAllFrames_Rgba32_kumin.gif)
- JpegEncoderTests
`GifEncoderTests` are still missing proper coverage, but they are less critical than others, and also the hardest ones to implement. 
@JimBobSquarePants I did my best to cover `PngEncoder` properly. Can you check if my coverage is correct and robust enough? There are some tests utilizing error diffusers with [reference image based …
=> Improved test coverage for Encoders/Decoders

src/ImageSharp.Drawing/DrawImage.cs, src/ImageSharp.Drawing/Processors/DrawImageProcessor.cs, src/ImageSharp/GraphicsOptions.cs, src/ImageSharp/Processing/Processors/Transforms/AffineTransformProcessor.cs, src/ImageSharp/Processing/Processors/Transforms/CenteredAffineTransformProcessor.cs, src/ImageSharp/Processing/Processors/Transforms/CenteredProjectiveTransformProcessor.cs, src/ImageSharp/Processing/Processors/Transforms/ProjectiveTransformProcessor.cs, src/ImageSharp/Processing/Transforms/Transform.cs, src/ImageSharp/Processing/Transforms/TransformHelpers.cs, tests/ImageSharp.Tests/Drawing/DrawImageTest.cs, tests/ImageSharp.Tests/Image/PixelAccessorTests.cs
This PR removes the internal clone from the `DrawImageProcessor` to reduce memory. See #465 
Preserving the original image is now the responsibility of the consuming developer.
=> Remove Clone from DrawImage to reduce memory consumption

src/ImageSharp/Processing/ColorMatrix/Opacity.cs, tests/ImageSharp.Tests/Formats/Bmp/BmpEncoderTests.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegEncoderTests.cs, tests/ImageSharp.Tests/Formats/Png/PngEncoderTests.cs, tests/ImageSharp.Tests/TestUtilities/TestImageExtensions.cs, tests/ImageSharp.Tests/TestUtilities/Tests/ReferenceCodecTests.cs
There were several bugs in the BMP+PNG+Jpeg encoder tests introduced by #469. In fact, those tests weren't verifying anything. This is fixed now.
BMP and Jpeg encoders are now tested without reference images using the `System.Drawing.Common` decoder implementation of the platform running the tests. In case of Jpeg, the tolerance threshold values are set to high values now, the correct values are TBD. (+ I think the encoder's LUT-based RGB->YCbCr conversion is not accurate enough at the moment, making the encoder inaccurate. Like in the decoder, it has to be implemented with `float` + SIMD instead!)
=> Fixing Encoder Tests

src/ImageSharp/Processing/Transforms/Processors/ResizeProcessor.cs, tests/ImageSharp.Tests/Processing/Processors/Transforms/ResizeTests.cs
We were disposing the private weight fields after the first frame was processed. This was introduced during optimization moving the generation of weights from per-image-frame to per-image.
See. https://gitter.im/ImageSharp/General?at=5ab06675e4d1c636041c1283
=> Fix non-nearest-neighbour resize for multi-frame-images

src/ImageSharp.Drawing/Processing/Drawing/DrawImageExtensions.cs, tests/ImageSharp.Tests/PixelFormats/PixelBlenders/PorterDuffCompositorTests.cs
We had both method names, both calling the same processor. It's odd and confusing.
=> Rename Blend to DrawImage

src/ImageSharp/ColorSpaces/Conversion/Implementation/Lms/LmsAdaptationMatrix.cs, src/ImageSharp/ColorSpaces/Conversion/Implementation/Rgb/GammaCompanding.cs, src/ImageSharp/ColorSpaces/Conversion/Implementation/Rgb/LCompanding.cs, src/ImageSharp/ColorSpaces/Conversion/Implementation/Rgb/Rec2020Companding.cs, src/ImageSharp/ColorSpaces/Conversion/Implementation/Rgb/Rec709Companding.cs, src/ImageSharp/ColorSpaces/Conversion/Implementation/Rgb/SRgbCompanding.cs
Hide some colorspace members that should not be public
=> Hide colorspace members

src/ImageSharp.Drawing/ImageSharp.Drawing.csproj, src/ImageSharp.Drawing/Processing/Drawing/DrawRectangleExtensions.cs, src/ImageSharp.Drawing/Processing/Drawing/FillRectangleExtensions.cs, src/ImageSharp/ImageSharp.csproj, tests/ImageSharp.Tests/Drawing/Paths/FillRectangle.cs, tests/ImageSharp.Tests/Drawing/SolidPolygonTests.cs
- update external dependencies
- Replace Rectangular**e**Polygon with RectangularPolygon
=> update external dependencies + fix RectangularPolygon usages

README.md
A minor change in Readme.md, pulling up the reference to our documentation site to the beginning of the document.
=> Readme.md: early documentation reference

tests/ImageSharp.Tests/Memory/SpanUtilityTests.cs, tests/ImageSharp.Tests/Memory/TestStructs.cs
Changes the SpanUtility tests to skip an equality test in 32bit mode as the differences are too small to accurately measure in 32bit mode causing them to fail sporadically.
We should refactor the test in the future but this shall do for now to stop blocking great PR's like #528
=> Update SpanUtility Test

src/ImageSharp/Common/Helpers/DebugGuard.cs, src/ImageSharp/Formats/Gif/GifDecoderCore.cs, src/ImageSharp/Formats/Gif/GifEncoderCore.cs, src/ImageSharp/Formats/Gif/LzwDecoder.cs, src/ImageSharp/Formats/Gif/LzwEncoder.cs, src/ImageSharp/Formats/Gif/PackedField.cs, src/ImageSharp/Processing/Quantization/FrameQuantizers/PaletteFrameQuantizer{TPixel}.cs, tests/ImageSharp.Tests/Formats/Gif/GifEncoderTests.cs, tests/ImageSharp.Tests/TestUtilities/TestImageExtensions.cs
Nothing fancy just a bit of a performance improvement reading and writing gifs. 33% faster decoding but no noticeable change with the encoder. 
We've got 250 GC Generation 2 collects per 1k Operations when encoding that I haven't identified the reason for yet. Possibly caused by multiple short writes to the stream.
**Before**
Method | Runtime |     TestImage |       Mean |      Error |   StdDev | Scaled | ScaledSD |   Gen 0 | Allocated |
--------------------- |-------- |-------------- |-----------:|-----------:|---------:|-------:|---------:|--------:|----------:|
'System.Drawing Gif' |    Core | Gif/rings.gif |   440.1 us |   966.4 us | 54.60 us |   1.00 |     0.00 | 51.2695 |  105.3 KB |
'ImageSharp Gif' |    Core | Gif/rings.gif | 1,231.9 us |   594.7 us | 33.60 us |   2.83 |     0.27 …
=> Faster Gif Decoding

src/ImageSharp/Formats/Png/PngDecoderCore.cs
The new `Image.Identify` API was introduced in #292. In #475 memory management was significantly improved, but there is still a case for `png` format when `ArrayPool` is used directly when calling `Image.Identify`, not with `IManagedByteBuffer` API.
This leads to the issue when `ArgumentException` is throwing in `ArrayPool.Return` method with this message:
```
The buffer is not associated with this pool and may not be returned to it.
Parameter name: array
```
This PR fixes this problem.
=> Disposing data chunk instead of explicit returning it to ArrayPool in PngDecoderCore.Identify

src/ImageSharp/Formats/Jpeg/GolangPort/Components/Decoder/OrigComponent.cs, src/ImageSharp/Formats/Jpeg/GolangPort/OrigJpegDecoderCore.cs
Image.Identify was allocating unnecessary memory. This PR is supposed to fix this.
=> fix for unnecessary memory allocation, if Identify is used to retrieve the metadata of an image only

src/ImageSharp.Drawing/Processing/Drawing/Processors/FillRegionProcessor.cs, src/ImageSharp/Formats/Png/Filters/AverageFilter.cs, src/ImageSharp/Formats/Png/Filters/PaethFilter.cs, src/ImageSharp/Formats/Png/Filters/SubFilter.cs, src/ImageSharp/Formats/Png/Filters/UpFilter.cs, src/ImageSharp/Formats/Png/PngEncoderCore.cs, src/ImageSharp/PixelFormats/Bgra32.cs, tests/ImageSharp.Tests/Image/ImageFramesCollectionTests.cs
Ditched the use of modulo (%). Modulo is slow, and if you use it to just get the lower 8 bits (1 byte), you can just directly cast to byte.
Also moved one if < out of the loop for speed. The less branching the better.
Similarly replaced an if < 128 by cast to sbyte and taking its abs value.
Performance gain in writing to PNG file seems to be roughly 20% (release mode, 1000x1000 bitmap).
In ImageFramesCollectionTests I've set the culture to en-US to ensure getting english exception texts.
Edit: I've just done similar changes to the PNG decoding, but there's no or little performance improvement there.
EncodePng benchmark (before change):
``` ini
BenchmarkDotNet=v0.10.12, OS=Windows 10 Redstone 3 [1709, Fall Creators Update] (10.0.16299.371)
Intel Core i7-6500U CPU 2.50GHz (Skylake), 1 CPU, …
```
=> Performance improvements in the PNG filtering (roughly 20% gain on my machine).

src/ImageSharp/Formats/Png/IPngEncoderOptions.cs, src/ImageSharp/Formats/Png/PngEncoder.cs, src/ImageSharp/Formats/Png/PngEncoderCore.cs, src/ImageSharp/Formats/PngFilterMethod.cs, tests/ImageSharp.Tests/Formats/Png/PngEncoderTests.cs
Prior to this PR the png encoder always used adaptive filtering when choosing the filter method to use to provide optimum compression. This generally provides the smallest output but comes at a performance cost since the scanline has to be filtered several times before compression.
This PR adds the ability to choose each of the 5 filtering methods to use per scanline row, plus adaptive filtering which gives the developer great flexibility to encode pngs to their requirements.
=> Add the ability to choose the filter method to use when encoding a png

src/ImageSharp.Drawing/Processing/Drawing/Processors/FillProcessor.cs, tests/ImageSharp.Tests/Drawing/FillSolidBrushTests.cs, tests/ImageSharp.Tests/TestUtilities/Attributes/WithSolidFilledImagesAttribute.cs, tests/ImageSharp.Tests/TestUtilities/TestImageExtensions.cs, tests/ImageSharp.Tests/TestUtilities/TestUtils.cs
I just realized that `FillProcessor` and `FillRegionProcessor` are two different things, so the tests in #553 do not cover `FillProcessor` thus are insufficient to safely merge #552. 
This PR:
- Changes FillSolidBrushTests to cover most of the `SolidBrush` scenarios/parameters
- Fixes a bug in `FillProcessor`: unlike in `FillRegionProcessor`, `BlendPercentage` was applied two times: once in `FillProcessor`, once in `SolidBrushApplicator`. The easiest way to see this is to undo the change and run `BlendFillColorOverBackround`.
=> better FillSolidBrushTests + bugfix in FillProcessor

src/ImageSharp/ImageSharp.csproj, tests/ImageSharp.Benchmarks/ImageSharp.Benchmarks.csproj, tests/ImageSharp.Sandbox46/ImageSharp.Sandbox46.csproj, tests/ImageSharp.Tests/ImageSharp.Tests.csproj
Updates System.* deps to 4.5.0-rc1. there were no breaking changes. The API surface for System.Memory should finally be stable!
=> Update System.* deps to 4.5.0-rc1

tests/ImageSharp.Tests/Processing/Transforms/AffineTransformTests.cs, tests/ImageSharp.Tests/TestUtilities/ImageProviders/BlankProvider.cs, tests/ImageSharp.Tests/TestUtilities/ImageProviders/SolidProvider.cs, tests/ImageSharp.Tests/TestUtilities/ImageProviders/TestPatternProvider.cs, tests/ImageSharp.Tests/TestUtilities/ImagingTestCaseUtility.cs, tests/ImageSharp.Tests/TestUtilities/TestImageExtensions.cs, tests/ImageSharp.Tests/TestUtilities/TestUtils.cs
I hope this will fix [some of the "reference output file missing" issues](https://gist.github.com/jongleur1983/cc54584d6420fbf5c90471dfbbfcfe22#file-powershelloutput-log-L1763) non-EN Windows users experience.
=> Better test file name formatting

tests/ImageSharp.Tests/Processing/Processors/Transforms/ResizeTests.cs, tests/ImageSharp.Tests/Processing/Transforms/ProjectiveTransformTests.cs, tests/ImageSharp.Tests/TestUtilities/TestImageExtensions.cs
More `FormattableString` -> more reliable test output file name formatting.
=> Use FormattableString instead of string in tests

src/ImageSharp/ImageExtensions.cs, tests/ImageSharp.Tests/Image/ImageSaveTests.cs, tests/ImageSharp.Tests/Processing/Transforms/AffineTransformTests.cs
removed all the `SavePixelData()` apis (as they can cause confusion people see a save method with a byte array and assume its an encoded image they can pass into something else and its not it was just a raw dump of our internal buffer).
To get a copy of the image buffer now you should instead add the `using SixLabors.ImageSharp.Advanced;`  which will expose our Span<T> apis which can be used to access the raw pixel buffer for any inter-op scenarios.
resolves #623
=> remove `SavePixelData()` apis in favour of `GetPixelSpan()`

src/ImageSharp/Processing/Dithering/ErrorDiffusion/ErrorDiffuserBase.cs
I came across this `NotNull` guard on a `DenseMatrix` while checking out the dithering code ;) (JetBrains' Heap Allocations Viewer plugin for Rider drew my attention to it, because it got boxed!)
=> Remove NotNull guard on value type

src/ImageSharp/Common/Helpers/DebugGuard.cs, src/ImageSharp/Common/Helpers/Guard.cs, tests/ImageSharp.Tests/Helpers/GuardTests.cs
A tiny improvement. See [this comment](https://github.com/SixLabors/ImageSharp/pull/631#issuecomment-399770900) for explanation.
=> Make Guard.NotNull() and DebugGuard.NotNull() generic

tests/ImageSharp.Benchmarks/Codecs/Jpeg/LoadResizeSave.cs, tests/ImageSharp.Benchmarks/Samplers/Resize.cs
- Adding a LoadResizeSave benchmark aka. Bertrand Le Roy's golden standard for comparing image scaling solutions
- Adding EnableParallelExecution to Resize becnhmark, because it's an important parameter
This is part of a work updating the SixLabors documentation for beta5, and adding a new short article about ImageSharp performance.
```
BenchmarkDotNet=v0.10.14, OS=Windows 10.0.17134
Intel Core i7-7700HQ CPU 2.80GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
Frequency=2742188 Hz, Resolution=364.6723 ns, Timer=TSC
.NET Core SDK=2.1.300
[Host]     : .NET Core 2.0.7 (CoreCLR 4.6.26328.01, CoreFX 4.6.26403.03), 64bit RyuJIT
Job-ILXLYY : .NET Framework 4.7.1 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.3110.0
Job-OSTKHA : .NET Core 2.0.7 (CoreCLR 4.6.26328.01, CoreFX 4.6.26403.03), 64bit …
```
=> Add LoadResizeSave benchmark

src/ImageSharp.Drawing/Processing/Processors/Drawing/DrawImageProcessor.cs, src/ImageSharp.Drawing/Processing/Processors/Drawing/FillProcessor.cs, src/ImageSharp/Common/Extensions/ConfigurationExtensions.cs, src/ImageSharp/Common/Helpers/ParallelFor.cs, src/ImageSharp/Configuration.cs, src/ImageSharp/ImageFrame{TPixel}.cs, src/ImageSharp/Processing/Processors/Binarization/BinaryThresholdProcessor.cs, src/ImageSharp/Processing/Processors/Convolution/Convolution2DProcessor.cs, src/ImageSharp/Processing/Processors/Convolution/Convolution2PassProcessor.cs, src/ImageSharp/Processing/Processors/Convolution/ConvolutionProcessor.cs, src/ImageSharp/Processing/Processors/Convolution/EdgeDetectorCompassProcessor.cs, src/ImageSharp/Processing/Processors/Effects/OilPaintingProcessor.cs, src/ImageSharp/Processing/Processors/Effects/PixelateProcessor.cs, src/ImageSharp/Processing/Processors/Filters/FilterProcessor.cs, src/ImageSharp/Processing/Processors/Overlays/BackgroundColorProcessor.cs, src/ImageSharp/Processing/Processors/Overlays/GlowProcessor.cs, src/ImageSharp/Processing/Processors/Overlays/VignetteProcessor.cs, src/ImageSharp/Processing/Processors/Transforms/AffineTransformProcessor.cs, src/ImageSharp/Processing/Processors/Transforms/CropProcessor.cs, src/ImageSharp/Processing/Processors/Transforms/FlipProcessor.cs, src/ImageSharp/Processing/Processors/Transforms/ProjectiveTransformProcessor.cs, src/ImageSharp/Processing/Processors/Transforms/ResizeProcessor.cs, src/ImageSharp/Processing/Processors/Transforms/RotateProcessor.cs, tests/ImageSharp.Benchmarks/Codecs/CopyPixels.cs, tests/ImageSharp.Benchmarks/Codecs/Jpeg/LoadResizeSave.cs, tests/ImageSharp.Benchmarks/Samplers/Glow.cs, tests/ImageSharp.Benchmarks/Samplers/Resize.cs, tests/ImageSharp.Tests/ConfigurationTests.cs, tests/ImageSharp.Tests/Drawing/SolidPolygonTests.cs, tests/ImageSharp.Tests/Image/ImageTests.WrapMemory.cs
Fixes #651. 
Internal helpers `ParallelFor.WithConfiguration(...)` and  `ParallelFor.WithTemporaryBuffer<T>(...)` are utilized more heavily.
=> Replace Configuration.ParallelOptions with Configuration.MaxDegreeOfParallelism

.travis.yml, ImageSharp.sln, README.md, appveyor.yml, run-tests.ps1, tests/CodeCoverage/CodeCoverage.cmd, tests/ImageSharp.Tests/ImageSharp.Tests.csproj
With the declaration of 2.1.3 as the LTS release and NET Core 2.0 reaching end of life in October -- this PR removes .NET Core 2.0 from our test library.
This should help speed up the CI pipeline, simplify building the test library, and increase the feedback cycle when submitting PRs.  Things take a really long time now.
[0] https://blogs.msdn.microsoft.com/dotnet/2018/06/20/net-core-2-0-will-reach-end-of-life-on-september-1-2018/
=> Drop  .NET Core 2.0 from continuous integration test coverage

src/ImageSharp.Drawing/Processing/BrushApplicator.cs, src/ImageSharp.Drawing/Processing/DrawImageExtensions.cs, src/ImageSharp.Drawing/Processing/Processors/Drawing/DrawImageProcessor.cs, src/ImageSharp.Drawing/Processing/Processors/Drawing/FillProcessor.cs, src/ImageSharp.Drawing/Processing/TextGraphicsOptions.cs, src/ImageSharp/GraphicsOptions.cs, src/ImageSharp/PixelFormats/PixelAlphaCompositionMode.cs, src/ImageSharp/PixelFormats/PixelColorBlendingMode.cs, src/ImageSharp/PixelFormats/PixelOperations{TPixel}.PixelBenders.cs, src/ImageSharp/Processing/Processors/Overlays/BackgroundColorProcessor.cs, src/ImageSharp/Processing/Processors/Overlays/GlowProcessor.cs, src/ImageSharp/Processing/Processors/Overlays/VignetteProcessor.cs, tests/ImageSharp.Tests/Drawing/DrawImageTest.cs, tests/ImageSharp.Tests/Drawing/FillSolidBrushTests.cs, tests/ImageSharp.Tests/Drawing/SolidFillBlendedShapesTests.cs, tests/ImageSharp.Tests/PixelFormats/PixelBlenders/PorterDuffCompositorTests.cs, tests/ImageSharp.Tests/PixelFormats/PixelOperationsTests.Blender.cs, tests/ImageSharp.Tests/PixelFormats/PixelOperationsTests.cs, tests/ImageSharp.Tests/TestUtilities/TestImageExtensions.cs
This continues the process started with #535 
As described in the issue, GraphicsOptions now has two separated modes for configuring Color Blending and Alpha Composition.
PixelAlphaCompositionMode has "SrcOver" as first value to ensure that a default GraphicsOptions structure will always be SrcOver-Normal which is the mode everybody expects by default.
Now there's a lot more possible combinations, so creating tests for all of them might take a while. Specially considering the test images are in a separate repository.
=> Split PixelBlendMode into PixelColorBlendingMode and PixelAlphaCompositionMode

src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs
This patch allows reading exif resolution values that have an invalid datatype. When the image is saved the values will be corrected. This should fix the issues reported in #521.
=> Allow several invalid data types when reading the exif resolution.

src/ImageSharp/Common/Extensions/ComparableExtensions.cs, src/ImageSharp/Formats/Png/PngDecoderCore.cs, src/ImageSharp/Formats/Png/PngEncoderCore.cs, src/ImageSharp/Processing/Processors/Quantization/WuFrameQuantizer{TPixel}.cs
- Fixes png encoding when 256 colors are used.
- Optimized Wu Quantizer to reduce memory usage by > half.
=> Png and Wu Quantizer fixes

src/ImageSharp/Formats/Png/PngDecoderCore.cs, src/ImageSharp/Formats/Png/Zlib/ZlibInflateStream.cs
This fixes #598 when decoding PNG data chunks in mono.  
Some people might appreciate this fix, as: 
- it will take a while for the [fix in mono](https://github.com/mono/mono/pull/10329) to make it to a stable release (looks like it is back ported to 5.18 at least)
- sometimes you are developing for software that embeds an old version of mono (like we do)
- or, you might not have control over what version of mono you get to target
What this does is changes `PngDecoderCore` and `ZlibInflateStream` so that when it is finished with the current chunk, it attempts to read the next data chunk before returning less than the buffer count from its `Read()` method.  Doing so would stop the `DeflateStream` from continuing, even on Windows.  It will only return less than the buffer count after it …
=> Fix issue on mono <= 5.14 when reading multiple png data chunks.

tests/ImageSharp.Tests/TestUtilities/Tests/ReferenceDecoderBenchmarks.cs
Oops, I left some benchmark tests enabled accidentally in #640
=> Skip tests in ReferenceDecoderBenchmarks

src/ImageSharp/Image.Decode.cs, tests/ImageSharp.Tests/Formats/ImageFormatManagerTests.cs
=> Use clean buffer when detecting format

src/ImageSharp/Formats/Png/IPngEncoderOptions.cs, src/ImageSharp/Formats/Png/PngDecoderCore.cs, src/ImageSharp/Formats/Png/PngEncoder.cs, src/ImageSharp/Formats/Png/PngEncoderCore.cs, src/ImageSharp/Formats/Png/PngScanlineProcessor.cs, src/ImageSharp/Processing/Processors/Quantization/QuantizedFrame{TPixel}.cs, tests/ImageSharp.Tests/Formats/Png/PngEncoderTests.cs, tests/ImageSharp.Tests/TestUtilities/ReferenceCodecs/MagickReferenceDecoder.cs, tests/ImageSharp.Tests/TestUtilities/Tests/MagickReferenceCodecTests.cs
This PR will add 1,2, and 4 bit encoding to png.
=> Add 1, 2, and 4 bit Png Encoding

src/ImageSharp/Common/Extensions/EncoderExtensions.cs, src/ImageSharp/Formats/Png/Chunks/PhysicalChunkData.cs, src/ImageSharp/Formats/Png/Chunks/PngPhysicalChunkData.cs, src/ImageSharp/Formats/Png/PngConstants.cs, src/ImageSharp/Formats/Png/PngDecoderCore.cs, src/ImageSharp/Formats/Png/PngEncoderCore.cs, src/ImageSharp/Formats/Png/PngHeader.cs, src/ImageSharp/MetaData/Profiles/Exif/ExifReader.cs
- Unify buffers in PngDecoder 
- Add Encoding.GetString(ROS<byte>) polyfill
- Utilize polyfill
- Move ColorTypes to PngConstants
- Optimize ReadTextChunk
- Move PngHeader validation to struct
- Improve descriptions on PNG exceptions
- Breakout the PhysicalChunkData conversion and encoding logic and add parse method
=> Improve PNG CQ2

ColorSpaceGenerator/ColorSpaceGenerator.csproj, src/ImageSharp/Processing/CropExtensions.cs, src/ImageSharp/Processing/Processors/Transforms/CropProcessor.cs, src/ImageSharp/Processing/Processors/Transforms/EntropyCropProcessor.cs, tests/ImageSharp.Tests/BaseImageOperationsExtensionTest.cs, tests/ImageSharp.Tests/ImageOperationTests.cs, tests/ImageSharp.Tests/Processing/Processors/Transforms/CropTest.cs, tests/ImageSharp.Tests/Processing/Transforms/CropTest.cs
We should throw when a crop rectangle exceeds the image bounds. This helps prevent users misappropriating the method and expecting unintended results. Fixes #605
=> Throw when crop rectangle exceeds source bounds.

src/ImageSharp/PixelFormats/Bgr24.cs, src/ImageSharp/PixelFormats/Bgra32.cs
Bgr24 and Bgra32 did not yet override ToString(). Did that now, following the same pattern as other Pixel formats (printing the components)
=> Add ToString implementations to Bgr24 and Bgra32

README.md, src/ImageSharp.Drawing/ImageSharp.Drawing.csproj, src/ImageSharp/Common/Extensions/EncoderExtensions.cs, src/ImageSharp/Common/Helpers/TestHelpers.cs, src/ImageSharp/Configuration.cs, src/ImageSharp/Formats/Gif/GifConstants.cs, src/ImageSharp/Formats/Jpeg/Components/Decoder/ProfileResolver.cs, src/ImageSharp/Formats/Png/PngConstants.cs, src/ImageSharp/Formats/Png/PngDecoderCore.cs, src/ImageSharp/IO/IFileSystem.cs, src/ImageSharp/IO/LocalFileSystem.cs, src/ImageSharp/Image.FromBytes.cs, src/ImageSharp/Image.FromFile.cs, src/ImageSharp/ImageExtensions.cs, src/ImageSharp/ImageSharp.csproj, src/ImageSharp/MetaData/Profiles/ICC/DataReader/IccDataReader.Primitives.cs, src/ImageSharp/MetaData/Profiles/ICC/DataReader/IccDataReader.cs, src/ImageSharp/MetaData/Profiles/ICC/DataWriter/IccDataWriter.Primitives.cs, src/ImageSharp/MetaData/Profiles/ICC/DataWriter/IccDataWriter.cs, src/ImageSharp/MetaData/Profiles/ICC/IccProfile.cs, src/ImageSharp/MetaData/Profiles/ICC/IccWriter.cs, src/ImageSharp/MetaData/Profiles/ICC/TagDataEntries/IccDataTagDataEntry.cs, tests/ImageSharp.Benchmarks/ImageSharp.Benchmarks.csproj, tests/ImageSharp.Tests/Formats/Png/PngChunkTypeTests.cs, tests/ImageSharp.Tests/Formats/Png/PngDecoderTests.Chunks.cs, tests/ImageSharp.Tests/MetaData/Profiles/ICC/IccProfileTests.cs, tests/ImageSharp.Tests/TestDataIcc/IccTestDataProfiles.cs
Drops support for netstandard1.1.
=> Drop netstandard1.1

appveyor.yml, src/ImageSharp/Common/Helpers/SimdUtils.ExtendedIntrinsics.cs, src/ImageSharp/Common/Helpers/SimdUtils.cs, src/ImageSharp/Common/Helpers/TestHelpers.cs, src/ImageSharp/ImageSharp.csproj, tests/ImageSharp.Tests/ImageSharp.Tests.csproj, tests/ImageSharp.Tests/RunExtendedTests.cmd
This PR cross targets NET472 and introduces a SUPPORTS_EXTENDED_INTRINSICS symbol to enable the new extended intrinsics support on modern runtimes (NET472+ & NETCOREAPP2.1+).
This PR also retarget the NET471 tests to NET472. Extended tests continue to run against NET471.
=> Cross target NET472 and enable extended intrinsics behind symbol

src/ImageSharp/MetaData/Profiles/Exif/ExifProfile.cs, src/ImageSharp/MetaData/Profiles/Exif/ExifReader.cs, src/ImageSharp/MetaData/Profiles/Exif/ExifWriter.cs, src/ImageSharp/MetaData/Profiles/ICC/IccProfile.cs, src/ImageSharp/MetaData/Profiles/ICC/IccReader.cs, src/ImageSharp/MetaData/Profiles/ICC/IccWriter.cs, src/ImageSharp/MetaData/Profiles/ICC/TagDataEntries/IccCurveTagDataEntry.cs, tests/ImageSharp.Tests/MetaData/Profiles/ICC/DataWriter/IccDataWriter.PrimitivesTests.cs, tests/ImageSharp.Tests/MetaData/Profiles/ICC/IccReaderTests.cs
- Uses Array.Empty<> where possible
- Eliminates a few ICC allocations
- Eliminates a few Exif allocations when profiles are valid
- Annotates a few readonly fields
=> Improve CQ8

src/ImageSharp.Drawing/Processing/SolidBrush{TPixel}.cs, tests/ImageSharp.Tests/Drawing/Text/DrawTextOnImageTests.cs
ensure we constrain the the spans we use in solid brushes.
resolves #688 
this will also resolve the exception being thrown in SixLabors/Samples#4
=> constrain destination span and scanline to same length

src/ImageSharp.Drawing/Processing/Processors/Text/DrawTextProcessor.cs, tests/ImageSharp.Tests/Drawing/Text/DrawTextOnImageTests.cs
this fixes #685 
The issue was the fact we where being to aggressive when caching rendered/repeated glyphs.
We now should be allowing approx 4 slightly offset variants of a single glyph (+/- 1 pixel on both axis).
=> Prevent text wandering from baseline

src/ImageSharp/Formats/Gif/GifDecoderCore.cs, tests/ImageSharp.Sandbox46/ImageSharp.Sandbox46.csproj, tests/ImageSharp.Tests/Formats/Gif/GifDecoderTests.cs
When the last frame of a GIF isn't properly terminated, Skip loops forever.
This ensures we break at the EOF.
This PR also renames Skip to SkipBlock to better describe it's behavior.
=> Fix infinite loop when a GIF prematurely terminates

src/ImageSharp/Processing/Processors/Convolution/BoxBlurProcessor.cs
old code seemed to be a relict from the GaussianBlurProcessor where this pattern made sense.
Here each value of the matrix is just 1.0/size as a result, and we can leverage DenseMatrix.Fill() for that.
=> simplify BoxBlurProcessor kernel initialization

src/ImageSharp/MetaData/Profiles/ICC/DataReader/IccDataReader.Curves.cs, src/ImageSharp/MetaData/Profiles/ICC/DataReader/IccDataReader.TagDataEntry.cs, src/ImageSharp/Processing/Processors/Convolution/KirschKernels.cs, src/ImageSharp/Processing/Processors/Convolution/KirschProcessor.cs
fixes typos in class name (and usages of that class) as well as for a local variable in code.
=> Fix naming of variable and class

src/ImageSharp/Processing/Processors/Transforms/ProjectiveTransformProcessor.cs, src/ImageSharp/Processing/Processors/Transforms/TransformUtils.cs, tests/ImageSharp.Tests/Processing/Transforms/ProjectiveTransformTests.cs
Previously we were modifying the wrong row/column in our taper matrices and then flattening the transform using `Vector3` to compensate when we should have been using `Vector4` instead to take into account perspective changes. These changes update the code to fix this.
=> Fix Projective Transforms

src/ImageSharp/Primitives/DenseMatrix{T}.cs, src/ImageSharp/Processing/Processors/Convolution/BoxBlurProcessor.cs, src/ImageSharp/Processing/Processors/Convolution/GaussianBlurProcessor.cs, src/ImageSharp/Processing/Processors/Convolution/GaussianSharpenProcessor.cs, tests/ImageSharp.Tests/Primitives/DenseMatrixTests.cs
Our current gaussian kernels are too small and fail to capture the full curve leading to boxed output. I've updated the algorithm based on the information found at http://chemaguerra.com/gaussian-filter-radius/ to correct the output.
=> Use correct Kernel dimensions and optimize. Fix #786

src/ImageSharp/Advanced/AotCompilerTools.cs
Adds some calls to `Unsafe.SizeOf` for various primitives and structs to prevent JIT errors on iOS.
Also seeds the decoders for a given pixel format, which should solve #776.
Note that although JPEG will now also load without crashing, it is incredibly slow on Xamarin.iOS.  A 1366x768 JPEG takes about 5 seconds to load on an iPad Pro.
As per the previous PR #767, this is a difficult one to write tests for.
=> Add more seeding to the AoT compiler for iOS

src/ImageSharp/Common/Helpers/Vector4Utils.cs, src/ImageSharp/Primitives/ColorMatrix.cs, src/ImageSharp/Primitives/Matrix5x4.cs, src/ImageSharp/Processing/FilterExtensions.cs, src/ImageSharp/Processing/KnownFilterMatrices.cs, src/ImageSharp/Processing/Processors/Filters/FilterProcessor.cs, tests/ImageSharp.Tests/Formats/GeneralFormatTests.cs, tests/ImageSharp.Tests/Helpers/Vector4UtilsTests.cs, tests/ImageSharp.Tests/Primitives/ColorMatrixTests.cs, tests/ImageSharp.Tests/Primitives/Matrix5x4Tests.cs, tests/ImageSharp.Tests/Processing/Processors/Filters/BrightnessTest.cs, tests/ImageSharp.Tests/Processing/Processors/Filters/ColorBlindnessTest.cs, tests/ImageSharp.Tests/Processing/Processors/Filters/FilterTest.cs, tests/ImageSharp.Tests/TestUtilities/ApproximateFloatComparer.cs
This PR replaces the incorrect `Matrix4x4` filter implementation with a new `ColorMatrix` transform.
All color matrices normally have a minimum of [5x4](https://developer.android.com/reference/android/graphics/ColorMatrix) indices which are used to transform the vector. While our implementation gave accurate output in fully opaque images, images with an alpha component were incorrect. In addition, the Hue filter was using an incorrect operator in its calculation which led to output error.
This PR.
- Introduces a new `ColorMatrix` struct modelled after the `Matrix4x4` struct. This contains all the properties required to implement color transforms.
- Updates the `KnownFilterMatrices` generation code to reflect the new struct layout and fix bugs. #802
- Optimizes the filter process using …
=> Fix Color Filters

.gitmodules, ImageSharp.sln, src/ImageSharp.Drawing/ImageSharp.Drawing.csproj, src/ImageSharp/Common/Helpers/SimdUtils.ExtendedIntrinsics.cs, src/ImageSharp/Common/Helpers/TestHelpers.cs, src/ImageSharp/Common/ParallelUtils/ParallelExecutionSettings.cs, src/ImageSharp/Common/ParallelUtils/ParallelHelper.cs, src/ImageSharp/Common/Tuples/Octet.cs, src/ImageSharp/Common/Tuples/Vector4Pair.cs, src/ImageSharp/Formats/Bmp/BmpInfoHeaderType.cs, src/ImageSharp/Formats/Bmp/BmpThrowHelper.cs, src/ImageSharp/Formats/Gif/Sections/IGifExtension.cs, src/ImageSharp/Formats/Jpeg/Components/Decoder/ScanDecoder.cs, src/ImageSharp/Formats/Jpeg/Components/Encoder/YCbCrForwardConverter{TPixel}.cs, src/ImageSharp/Formats/Jpeg/JpegEncoderCore.cs, src/ImageSharp/Formats/Png/Chunks/PhysicalChunkData.cs, src/ImageSharp/Formats/Png/Filters/UpFilter.cs, src/ImageSharp/Formats/Png/PngConstants.cs, src/ImageSharp/ImageSharp.csproj, src/ImageSharp/Memory/RowInterval.cs, src/ImageSharp/MetaData/Profiles/Exif/ExifConstants.cs, src/ImageSharp/MetaData/Profiles/Exif/ExifTags.cs, src/ImageSharp/MetaData/Profiles/ICC/TagDataEntries/IccLut16TagDataEntry.cs, src/ImageSharp/MetaData/Profiles/ICC/TagDataEntries/IccLut8TagDataEntry.cs, src/ImageSharp/PixelFormats/Utils/Vector4Converters.Default.cs, src/ImageSharp/PixelFormats/Utils/Vector4Converters.RgbaCompatible.cs
Updates all dependencies and uses new standards submodule for linting.
=> Update dependencies + fix stylecop

src/ImageSharp/IO/DoubleBufferedStreamReader.cs
We weren't tracking input stream positional offsets when loading which leads to issues. Fix #818
=> Track input stream position on load.

src/ImageSharp.Drawing/ImageSharp.Drawing.csproj, src/ImageSharp/ImageSharp.csproj, tests/ImageSharp.Tests/ImageSharp.Tests.csproj
Visual Studio for Mac has a pretty sever limitation when building multitargeting projects.
>The current implementation allows multi-target frameworks projects to be opened and compiled but treats them as though they have a single target framework.
https://bugzilla.xamarin.com/show_bug.cgi?id=55508#c5
This PR reorders the target frameworks so that `netcoreapp2.1` is the first target in all relevant projects and adds the target to **ImageSharp.Drawing** (we'll probably need it for future perf work anyway).
=> Allow Build with Visual Studio For Mac

tests/ImageSharp.Benchmarks/Drawing/DrawBeziers.cs, tests/ImageSharp.Benchmarks/Drawing/DrawLines.cs, tests/ImageSharp.Benchmarks/Drawing/DrawPolygon.cs, tests/ImageSharp.Benchmarks/Drawing/DrawText.cs, tests/ImageSharp.Benchmarks/Drawing/DrawTextOutline.cs, tests/ImageSharp.Benchmarks/Drawing/FillWithPattern.cs, tests/ImageSharp.Tests/TestUtilities/ReferenceCodecs/SystemDrawingBridge.cs
Some changes to make the usages of GDI in benchmarks and tests more stable, this should hopefully prevent "a generic error occurred in GDI+". Hopefully I didn't miss one...
If you new Pen, Brush or Fonts, these need to be disposed.
=> GDI+ stability fixes for the benchmark and tests

README.md
=> #852 Adding instructions to add submodules when cloning the repository

src/ImageSharp/Common/Extensions/StreamExtensions.cs, src/ImageSharp/Formats/Jpeg/JpegEncoderCore.cs
This is a partial fix of https://github.com/SixLabors/ImageSharp/issues/854 and shows how to take advantage of the underlying compiler functionality.
=> Updating some readonly static data in JpegEncoderCore to take advantage of compiler functionality.

src/ImageSharp/Formats/Gif/GifEncoderCore.cs, src/ImageSharp/Formats/Png/PngEncoderCore.cs
Replaces `enum.Equals(object)` with `enum == enum`. Fixes #862
=> Remove Enum Comparison Boxing

src/ImageSharp/ColorSpaces/CieXyChromaticityCoordinates.cs, src/ImageSharp/ColorSpaces/Companding/GammaCompanding.cs, src/ImageSharp/ColorSpaces/Companding/LCompanding.cs, src/ImageSharp/ColorSpaces/Companding/Rec2020Companding.cs, src/ImageSharp/ColorSpaces/Companding/Rec709Companding.cs, src/ImageSharp/ColorSpaces/Conversion/ColorSpaceConverter.CieLch.cs, src/ImageSharp/ColorSpaces/Conversion/Implementation/Converters/CieXyzAndCieXyyConverter.cs, src/ImageSharp/ColorSpaces/Conversion/Implementation/Converters/CieXyzToLinearRgbConverter.cs, src/ImageSharp/ColorSpaces/Conversion/Implementation/Converters/CmykAndRgbConverter.cs, src/ImageSharp/ColorSpaces/Conversion/Implementation/Converters/LinearRgbToRgbConverter.cs, src/ImageSharp/ColorSpaces/Conversion/Implementation/Converters/RgbToLinearRgbConverter.cs, src/ImageSharp/ColorSpaces/Conversion/Implementation/Converters/YCbCrAndRgbConverter.cs, src/ImageSharp/ColorSpaces/Conversion/Implementation/WorkingSpaces/GammaWorkingSpace.cs, tests/ImageSharp.Tests/Colorspaces/Companding/CompandingTests.cs
A few more things in colorspaces.
=> Nits - Colorspaces

src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeHelper.cs, tests/ImageSharp.Tests/Processing/Processors/Transforms/ResizeHelperTests.cs
Fixes #892 
When resizing an image that is smaller than the target image using Mode.Min, the resulting image is padded to be square instead of keeping the size of the original image.
=> Pass correct output size source image is smaller than the Target in ResizeMode.Min

src/ImageSharp/Processing/Extensions/PadExtensions.cs, tests/ImageSharp.Tests/Processing/Processors/Transforms/PadTest.cs
=> Add Color overload to Pad method.

src/ImageSharp/Formats/Jpeg/Components/Decoder/ProfileResolver.cs, src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs, src/ImageSharp/Formats/Jpeg/JpegEncoderCore.cs, src/ImageSharp/Formats/Png/PngEncoderCore.cs, src/ImageSharp/MetaData/Profiles/ICC/Curves/IccOneDimensionalCurve.cs, src/ImageSharp/MetaData/Profiles/ICC/Curves/IccResponseCurve.cs, src/ImageSharp/MetaData/Profiles/ICC/DataWriter/IccDataWriter.TagDataEntry.cs, src/ImageSharp/MetaData/Profiles/ICC/IccWriter.cs, src/ImageSharp/MetaData/Profiles/ICC/MultiProcessElements/IccCurveSetProcessElement.cs, src/ImageSharp/MetaData/Profiles/ICC/TagDataEntries/IccChromaticityTagDataEntry.cs, src/ImageSharp/MetaData/Profiles/ICC/TagDataEntries/IccColorantTableTagDataEntry.cs, src/ImageSharp/MetaData/Profiles/ICC/TagDataEntries/IccLut16TagDataEntry.cs, src/ImageSharp/MetaData/Profiles/ICC/TagDataEntries/IccLut8TagDataEntry.cs, src/ImageSharp/MetaData/Profiles/ICC/TagDataEntries/IccLutAToBTagDataEntry.cs, src/ImageSharp/MetaData/Profiles/ICC/TagDataEntries/IccLutBToATagDataEntry.cs, src/ImageSharp/MetaData/Profiles/ICC/TagDataEntries/IccMultiLocalizedUnicodeTagDataEntry.cs, src/ImageSharp/MetaData/Profiles/ICC/TagDataEntries/IccMultiProcessElementsTagDataEntry.cs, src/ImageSharp/MetaData/Profiles/ICC/TagDataEntries/IccNamedColor2TagDataEntry.cs, src/ImageSharp/MetaData/Profiles/ICC/TagDataEntries/IccProfileSequenceDescTagDataEntry.cs, src/ImageSharp/MetaData/Profiles/ICC/TagDataEntries/IccResponseCurveSet16TagDataEntry.cs, src/ImageSharp/MetaData/Profiles/ICC/TagDataEntries/IccUInt64ArrayTagDataEntry.cs, src/ImageSharp/MetaData/Profiles/ICC/Various/IccClut.cs, src/ImageSharp/MetaData/Profiles/ICC/Various/IccNamedColor.cs, src/ImageSharp/MetaData/Profiles/ICC/Various/IccProfileDescription.cs, src/ImageSharp/MetaData/Profiles/ICC/Various/IccProfileSequenceIdentifier.cs, src/ImageSharp/Processing/ResizeOptions.cs
Removes usage of linq in several  performance critical paths and cleans up a rather nasty allocation that was taking place during the encoding of jpegs with large EXIF metadata. Formatting fixes also.
=> Removes usage of linq in several critical paths

Directory.Build.props, Directory.Build.targets
A few updates to the project to get build/tests running locally again.
=> Fix local build/tests

src/ImageSharp.Drawing/Processing/Processors/Drawing/FillRegionProcessor{TPixel}.cs, tests/ImageSharp.Tests/Drawing/FillRegionProcessorTests.cs
This is a fix for an issue that I have discovered as well as the reported issue #928.  I have added two tests to illustrate the issue that fail on `master` as well as a possible fix.
The issue arises due to this code:
https://github.com/SixLabors/ImageSharp/blob/aac8eae64aab06ecd8aa0210e49fb0ba67e9a4ea/src/ImageSharp.Drawing/Processing/Processors/Drawing/FillRegionProcessor%7BTPixel%7D.cs#L99-L112
If `pointsFound` is odd (such as 3) and equal to the size of the buffer, the loop will go up to `buffer.Length - 1`, but that means that `buffer[point + 1]` will be out of bounds and cause an exception.
My solution was to add a second condition to the loop: `point < buffer.Length - 1`  Unfortunately, I don't know enough about the algorithm to know if this will result in an incorrect result.
=> Fix IndexOutOfRangeException in FillRegionProcessor

src/ImageSharp/Advanced/AotCompilerTools.cs, src/ImageSharp/Formats/Jpeg/Components/Decoder/HuffmanScanDecoder.cs, src/ImageSharp/Processing/Processors/Normalization/AdaptiveHistogramEqualizationProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Transforms/TransformKernelMap.cs, tests/ImageSharp.Tests/Formats/Gif/GifEncoderTests.cs, tests/ImageSharp.Tests/Image/ImageSaveTests.cs
u may want to squash this one since i decided to revert the sum commit
=> remove some redundant variables and type params

src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromCmyk.cs, src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromGrayScale.cs, src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromRgb.cs, src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.FromYccK.cs
not sure if this is a fast path?
=> cache max in ConvertToRgba

src/ImageSharp/Memory/MemoryOwnerExtensions.cs
See [this issue comment](https://github.com/SixLabors/ImageSharp/issues/987#issuecomment-525491787) for explanation. May workaround #987 for (some? all?) users.
=> Patch MemoryOwnerExtensions to workaround #987

src/ImageSharp/PixelFormats/PixelImplementations/RgbaVector.cs
Fixed XML docs for `RgbaVector` from "16-bit" to "32-bit" (as it uses `float` values)
=> Fixed XML docs for RgbaVector pixel type

src/ImageSharp/ColorSpaces/Conversion/Implementation/Converters/HslAndRgbConverter.cs, tests/ImageSharp.Tests/Colorspaces/Conversion/RgbAndHslConversionTest.cs
Fixes the calculation issue discovered in #997
=> Fix RGB to HSL conversion

src/ImageSharp/Processing/Extensions/ResizeExtensions.cs, src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeHelper.cs, src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeProcessor.cs, src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeProcessor{TPixel}.cs, src/ImageSharp/Processing/ResizeMode.cs, src/ImageSharp/Processing/ResizeOptions.cs, tests/ImageSharp.Tests/Processing/Processors/Transforms/ResizeHelperTests.cs, tests/ImageSharp.Tests/Processing/Transforms/PadTest.cs, tests/ImageSharp.Tests/Processing/Transforms/ResizeTests.cs, tests/ImageSharp.Tests/xunit.runner.json
Fixes #999 and adds addition `ResizeHelper` tests
=> Fix #999 and add tests

src/ImageSharp/IImage.cs, src/ImageSharp/Image.cs, src/ImageSharp/ImageExtensions.cs, src/ImageSharp/ImageFrame.cs, src/ImageSharp/ImageFrame{TPixel}.cs, src/ImageSharp/Image{TPixel}.cs, src/ImageSharp/Processing/Processors/CloningImageProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/ImageProcessor{TPixel}.cs
Touches #967 
- Refactor of `IDisposable` pattern for images, frames, and processors to work better with inheritance and ensure finalizer suppression.
- `Image<TPixel>` is no longer sealed as that prevents extending for potential types like `IntegralImage<TPixel>`. `ImageFrame<TPixel>` is left sealed as inheritance should not be required.
=> Refactor IDisposable pattern

src/ImageSharp.Drawing/Processing/Processors/Drawing/DrawImageProcessor.cs, src/ImageSharp/Advanced/AdvancedImageExtensions.cs, src/ImageSharp/Advanced/IImageVisitor.cs, src/ImageSharp/Image.cs, src/ImageSharp/Image{TPixel}.cs, src/ImageSharp/Processing/Extensions/ProcessingExtensions.cs, src/ImageSharp/Processing/Processors/ImageProcessorExtensions.cs
- Adds new `AcceptVisitor` extension method to the `Advanced` namespace and redirects all calls to that method.
=> Expose visitor through advanced namespace.

src/ImageSharp.Drawing/Processing/Processors/Drawing/DrawImageProcessor{TPixelBg,TPixelFg}.cs, src/ImageSharp/Advanced/AotCompilerTools.cs, src/ImageSharp/Processing/DefaultImageProcessorContext{TPixel}.cs, src/ImageSharp/Processing/Processors/CloningImageProcessor.cs, src/ImageSharp/Processing/Processors/CloningImageProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Convolution/EdgeDetector2DProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Convolution/EdgeDetectorCompassProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Convolution/EdgeDetectorProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Filters/LomographProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Filters/PolaroidProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/ICloningImageProcessor.cs, src/ImageSharp/Processing/Processors/ICloningImageProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/IImageProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/ImageProcessorExtensions.cs, src/ImageSharp/Processing/Processors/ImageProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Transforms/AffineTransformProcessor.cs, src/ImageSharp/Processing/Processors/Transforms/AffineTransformProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Transforms/AutoOrientProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Transforms/CropProcessor.cs, src/ImageSharp/Processing/Processors/Transforms/CropProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Transforms/EntropyCropProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Transforms/ProjectiveTransformProcessor.cs, src/ImageSharp/Processing/Processors/Transforms/ProjectiveTransformProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeProcessor.cs, src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Transforms/RotateProcessor.cs, src/ImageSharp/Processing/Processors/Transforms/SkewProcessor.cs, tests/ImageSharp.Tests/Drawing/FillRegionProcessorTests.cs, tests/ImageSharp.Tests/Processing/ImageProcessingContextTests.cs
Touches. #967 
- Refactors the image processors to make the interfaces and base classes public. 
- Removes double pixel processor creation.
- Simplified cloned target image creation.
<strike>I've marked this as draft as I want to do something more extreme and remove `ICloningImageProcessor<TPixel>` moving the interface method into the base class. This makes additional methods impossible to test against though via mocking. </strike>
Changed my mind and figured out a better way to create contracts for cloned/regular processors.
Thoughts please!
=> Make processors public, refactor cloning.

src/ImageSharp/Color/Color.NamedColors.cs
Update the hex value for DarkSeaGreen color to 0xFF8FBC8F.
Based on W3 definition, the hex value for DarkSeaGreen color needs to be fixed:
https://www.w3.org/wiki/CSS/Properties/color/keywords
Fix issue: https://github.com/SixLabors/ImageSharp/issues/1015
=> Update the hex value for DarkSeaGreen color

src/ImageSharp/Formats/Jpeg/Components/Decoder/HuffmanScanBuffer.cs, src/ImageSharp/Formats/Jpeg/Components/Decoder/HuffmanTable.cs, src/ImageSharp/Formats/Jpeg/JpegConstants.cs, src/ImageSharp/Processing/Processors/ImageProcessor{TPixel}.cs
Some minor optimizations to the HuffmanScanDecoder plus a little cleanup. For baseline jpegs we're sitting at around 25-30% for the total processing time.
``` bash
Full decoder
|                         Method |            TestImage |       Mean |      Error |     StdDev | Ratio | RatioSD |     Gen 0 | Gen 1 | Gen 2 |   Allocated |
|------------------------------- |--------------------- |-----------:|-----------:|-----------:|------:|--------:|----------:|------:|------:|------------:|
| 'Decode Jpeg - System.Drawing' | Jpg/b(...)e.jpg [21] |   6.121 ms |   3.134 ms |  0.1718 ms |  1.00 |    0.00 |   46.8750 |     - |     - |   205.83 KB |
|     'Decode Jpeg - ImageSharp' | Jpg/b(...)e.jpg [21] |  16.796 ms |   9.187 ms |  0.5036 ms |  2.74 |    0.03 |         - |     - |     - |    14.37 …
```
=> Huffman decode optimizations

src/ImageSharp/Advanced/AotCompilerTools.cs, src/ImageSharp/Processing/Extensions/DiffuseExtensions.cs, src/ImageSharp/Processing/Processors/Binarization/BinaryErrorDiffusionProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Dithering/AtkinsonDiffuser.cs, src/ImageSharp/Processing/Processors/Dithering/BurksDiffuser.cs, src/ImageSharp/Processing/Processors/Dithering/ErrorDiffuser.cs, src/ImageSharp/Processing/Processors/Dithering/ErrorDiffusionPaletteProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Dithering/FloydSteinbergDiffuser.cs, src/ImageSharp/Processing/Processors/Dithering/IErrorDiffuser.cs, src/ImageSharp/Processing/Processors/Dithering/JarvisJudiceNinkeDiffuser.cs, src/ImageSharp/Processing/Processors/Dithering/OrderedDitherPaletteProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Dithering/PaletteDitherProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Dithering/Sierra2Diffuser.cs, src/ImageSharp/Processing/Processors/Dithering/Sierra3Diffuser.cs, src/ImageSharp/Processing/Processors/Dithering/SierraLiteDiffuser.cs, src/ImageSharp/Processing/Processors/Dithering/StevensonArceDiffuser.cs, src/ImageSharp/Processing/Processors/Dithering/StuckiDiffuser.cs, src/ImageSharp/Processing/Processors/Dithering/error_diffusion.txt, src/ImageSharp/Processing/Processors/Quantization/FrameQuantizer{TPixel}.cs, src/ImageSharp/Processing/Processors/Quantization/OctreeFrameQuantizer{TPixel}.cs, src/ImageSharp/Processing/Processors/Quantization/PaletteFrameQuantizer{TPixel}.cs, src/ImageSharp/Processing/Processors/Quantization/WuFrameQuantizer{TPixel}.cs, tests/ImageSharp.Benchmarks/Samplers/Diffuse.cs
- Optimizes the error diffusion algorithm providing a minor speedup and memory reduction. Touches #757
- Fixes an issue where too much error was being introduced.
``` bash
BenchmarkDotNet=v0.11.5, OS=Windows 10.0.18362
Intel Core i7-8650U CPU 1.90GHz (Kaby Lake R), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=3.0.100
[Host] : .NET Core 2.1.13 (CoreCLR 4.6.28008.01, CoreFX 4.6.28008.01), 64bit RyuJIT
Clr    : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.8.4018.0
Core   : .NET Core 2.1.13 (CoreCLR 4.6.28008.01, CoreFX 4.6.28008.01), 64bit RyuJIT
IterationCount=3  LaunchCount=1  WarmupCount=3
```
**Before**
|    Method |  Job | Runtime |      Mean |    Error |   StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------- |----- |-------- …
=> Optimize Error Diffusion

src/ImageSharp/PixelFormats/PixelBlenders/PorterDuffFunctions.cs
Explanation of the changes:
line 167:
dstW + srcW + blendW
= dstW + (source.W - blendW) + blendW
= dstW + source.W - blendW + blendW
= dstW + source.W
line 194:
dstW + blendW
= (destination.W - blendW) + blendW
= destination.W - blendW + blendW
= destination.W
removes two additions that are not necessary.
=> small improvements on the PorterDuff functions

src/ImageSharp/Formats/Bmp/BmpImageFormatDetector.cs, src/ImageSharp/Formats/Tga/TgaImageFormatDetector.cs, src/ImageSharp/Image.Decode.cs, src/ImageSharp/Image.FromStream.cs, tests/ImageSharp.Tests/Formats/GeneralFormatTests.cs
This PR adds the following method:
```c#
IImageInfo Image.Identify(stream, out IImageFormat format);
```
Which mirrors the `Image.Load` method. I spotted a need for it when writing a PR for PeachPie. 
It also fixes the issue identified here. Where it was possible to misidentify an image as TGA.
https://github.com/SixLabors/ImageSharp/pull/1026#issuecomment-546713541
=> Allow returning the image format with the info.

Directory.Build.targets, src/ImageSharp/Formats/Tga/TgaDecoderCore.cs, src/ImageSharp/Image.FromBytes.cs, tests/ImageSharp.Benchmarks/Codecs/DecodeTga.cs, tests/ImageSharp.Benchmarks/Codecs/Jpeg/DecodeJpeg_ImageSpecific.cs, tests/ImageSharp.Benchmarks/Codecs/MultiImageBenchmarkBase.cs, tests/ImageSharp.Benchmarks/Config.cs, tests/ImageSharp.Benchmarks/ImageSharp.Benchmarks.csproj
Couldn't help myself when I discovered a new best-in-class decoder. 
**Before** (Both benchmarks made using `Bgr24` after update to benchmark)
|            Method |       Runtime |           TestImage |         Mean |        Error |      StdDev | Ratio |  Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------ |-------------- |-------------------- |-------------:|-------------:|------------:|------:|-------:|------:|------:|----------:|
| 'ImageMagick Tga' |    .NET 4.7.2 | Tga/targa_24bit.tga | 2,244.805 us | 3,012.486 us | 165.1245 us | 1.000 |      - |     - |     - |   13680 B |
|  'ImageSharp Tga' |    .NET 4.7.2 | Tga/targa_24bit.tga |    98.776 us |    45.871 us |   2.5144 us | 0.044 | 0.2441 |     - |     - |    1260 B |
|        'Pfim Tga' |    .NET 4.7.2 | Tga/targa_24bit.tga | …
=> Speed up tga decoding and add new benchmark comparison

src/ImageSharp/ImageFrameCollection.cs, src/ImageSharp/Image{TPixel}.cs, src/ImageSharp/Processing/Processors/CloningImageProcessor{TPixel}.cs
We were allowing enumerating our source `ImageFrame<TPixel>` collection more than once on clone causing memory leaks so I've switched the code to explicitly enumerate once and pass an array to the new image constructor.
Fixes #1073
=> Enumerate once on clone. Fix #1073

.gitattributes, Directory.Build.props, src/ImageSharp.Drawing/ImageSharp.Drawing.csproj, src/ImageSharp/Common/Extensions/EncoderExtensions.cs, src/ImageSharp/Common/Extensions/StreamExtensions.cs, src/ImageSharp/Formats/Bmp/BmpDecoderCore.cs, src/ImageSharp/Formats/Bmp/BmpEncoderCore.cs, src/ImageSharp/Formats/Gif/LzwDecoder.cs, src/ImageSharp/Formats/Tga/TgaDecoderCore.cs, src/ImageSharp/Formats/Tga/TgaEncoderCore.cs, src/ImageSharp/ImageSharp.csproj
As part of the move to externalize ImageSharp.Drawing and import Core I thought it wise to simplify and normalize our use of #ifdefs throughout the library.
Once we have a CI build environment that works on .NET Core 3.1 we can easily add additional target frameworks.
Touch #1002
=> Simplify and cleanup build constants

src/ImageSharp.Drawing/Processing/BrushApplicator.cs, src/ImageSharp.Drawing/Processing/PathGradientBrush.cs, src/ImageSharp.Drawing/Processing/Processors/Drawing/FillProcessor{TPixel}.cs, tests/ImageSharp.Tests/Drawing/FillLinearGradientBrushTests.cs
Added pooled buffer generation to the edge class to make it threadsafe. Also did some very low hanging optimization fruit. Fix #1044 
@jongleur1983 can you also have a look at the fix please to confirm. Thanks!
=> Use per-edge buffer + minor optimizations.

GitVersion.yml
Replaces `dev` nightly prefix with `unstable` fixing Nuget ordering. Also means that `rc` can be overwritten also.
=> Fix build number

src/ImageSharp/Advanced/IRowAction.cs, src/ImageSharp/Advanced/IRowAction{TBuffer}.cs, src/ImageSharp/Advanced/ParallelRowIterator.cs, src/ImageSharp/ImageFrame{TPixel}.cs, src/ImageSharp/Processing/Processors/Binarization/BinaryThresholdProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Convolution/BokehBlurProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Convolution/Convolution2DProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Convolution/Convolution2PassProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Convolution/ConvolutionProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Convolution/EdgeDetectorCompassProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Drawing/DrawImageProcessor{TPixelBg,TPixelFg}.cs, src/ImageSharp/Processing/Processors/Effects/OilPaintingProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Effects/PixelRowDelegateProcessor{TPixel,TDelegate}.cs, src/ImageSharp/Processing/Processors/Filters/FilterProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Normalization/GlobalHistogramEqualizationProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Overlays/BackgroundColorProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Overlays/GlowProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Overlays/VignetteProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Transforms/AffineTransformProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Transforms/CropProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Transforms/FlipProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Transforms/ProjectiveTransformProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Transforms/RotateProcessor{TPixel}.cs
Follow up for #1107 with value delegates operating on one row at a time.
=> WIP: single row value delegates for parallel iterator

src/ImageSharp/Processing/Processors/Convolution/BokehBlurProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Convolution/Parameters/BokehBlurKernelData.cs, src/ImageSharp/Processing/Processors/Convolution/Parameters/BokehBlurKernelDataProvider.cs
The previous implementation of the `BokehBlurProcessor<TPixel>` was using a `static ConcurrentDictionary<BokehBlurParameters, BokehBlurKernelData>` field to store the preprocessed bokeh blur kernels for a pair of input parameters. The issue was that that static field was **inside a generic class**, meaning each concrete `<TPixel>` instantiation would've seen a completely different dictionary. As a result, running the same bokeh blur effect on multiple images of different pixel formats, even with the same parameters, would've caused the kernels to be recomputed every time, and stored separately in each dictionary, despite the kernels actually being exactly the same (they're not dependent on the pixel type they'll be used on).
This PR moves all the kernel preprocessing logic into a separate …
=> Bokeh blur cache optimization

src/ImageSharp/Formats/Jpeg/Components/Block8x8.cs
Optimization to the `Block8x8` constructor, as discussed with @JimBobSquarePants.
**Before (Release x64):**
```asm
SixLabors.ImageSharp.Formats.Jpeg.Components.Block8x8..ctor(System.Span`1<Int16>)
L0000: sub rsp, 0x28
L0004: mov r8, [rdx]
L0007: mov edx, [rdx+0x8]
L000a: shl rdx, 1
L000d: cmp rdx, 0x7fffffff
L0014: ja L002a
L0016: mov rdx, r8
L0019: mov r8d, 0x80
L001f: call 0x7ffa28883850
L0024: nop
L0025: add rsp, 0x28
L0029: ret
L002a: call 0x7ffa289aed50
L002f: int3
```
**After:**
```asm
SixLabors.ImageSharp.Formats.Jpeg.Components.Block8x8..ctor(System.Span`1<Int16>)
L0000: mov rdx, [rdx]
L0003: mov r8d, 0x80
L0009: call 0x7ffa28883850
L000e: nop
L000f: ret
```
=> Removed unnecessary MemoryMarshal.Cast call

src/ImageSharp/Formats/Jpeg/Components/Decoder/ColorConverters/JpegColorConverter.cs
While browsing the code, spotted that an `int` was accidentally passed as `float`.
=> small fix in JpegColorConverter

.editorconfig, .gitmodules, ImageSharp.sln, src/Directory.Build.props, src/Directory.Build.targets, src/ImageSharp/Common/Extensions/StreamExtensions.cs, src/ImageSharp/Common/Helpers/Guard.Numeric.cs, src/ImageSharp/Common/Helpers/Guard.cs, src/ImageSharp/Formats/Gif/GifConstants.cs, src/ImageSharp/Formats/Gif/GifEncoderCore.cs, src/ImageSharp/Formats/Gif/Sections/GifNetscapeLoopingApplicationExtension.cs, src/ImageSharp/Formats/Jpeg/Components/Decoder/ProfileResolver.cs, src/ImageSharp/Formats/Jpeg/Components/ZigZag.cs, src/ImageSharp/Formats/Png/PngConstants.cs, src/ImageSharp/Formats/Png/PngEncoderCore.cs, src/ImageSharp/Formats/Png/Zlib/DeflaterHuffman.cs, src/ImageSharp/ImageSharp.csproj, src/ImageSharp/Metadata/Profiles/Exif/ExifConstants.cs, src/ImageSharp/Metadata/Profiles/Exif/ExifWriter.cs, src/ImageSharp/PixelFormats/PixelBlenders/PorterDuffFunctions.Generated.cs, src/ImageSharp/Processing/Processors/Quantization/OctreeFrameQuantizer{TPixel}.cs, tests/ImageSharp.Tests/Formats/Jpg/ProfileResolverTests.cs, tests/ImageSharp.Tests/Image/ImageFrameCollectionTests.Generic.cs, tests/ImageSharp.Tests/Image/ImageFrameCollectionTests.NonGeneric.cs, tests/ImageSharp.Tests/Metadata/Profiles/Exif/ExifProfileTests.cs
This PR includes a couple of minor optimizations:
- Replaced some `static readonly byte[]` arrays with static `ReadOnlySpan<byte>` values that directly map over constant data in the `.text` segment (see [here](https://vcsjones.dev/2019/02/01/csharp-readonly-span-bytes-static/)).
- Removed some bound checks when accessing those static sections (added some DEBUG checks)
- Removed some type initialization calls to `Encoding.ASCII.GetBytes`, no longer necessary
- Switched the `Stream.Write` calls to the `ReadOnlySpan<byte>` overloads.
No rush at all for this, just saw those `byte[]` arrays and thought I'd have some fun optimizing them away. Pinging @antonfirsov for the reviews as he's the official performance guru. 😄
=> Text segment ReadOnlySpan<byte> initialization

src/ImageSharp/Image.FromBytes.cs, src/ImageSharp/Image.FromFile.cs, src/ImageSharp/Image.FromStream.cs, tests/ImageSharp.Tests/Image/ImageTests.Identify.cs, tests/ImageSharp.Tests/Image/ImageTests.ImageLoadTestBase.cs
Adds additional overloads to `Image.Identify` to handle both file paths and byte arrays.
=> Add overloads. Fix #1144

src/ImageSharp/Processing/Processors/Convolution/ConvolutionProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Convolution/EdgeDetector2DProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Convolution/EdgeDetectorCompassProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Convolution/EdgeDetectorProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Filters/OpaqueProcessor{TPixel}.cs, tests/ImageSharp.Tests/Processing/Processors/Transforms/EntropyCropTest.cs
Edge detection now produces fully opaque output. This stabilizes the output across platforms and also fixes entropy cropping.
=> Fix edge detection and reenable entropy crop tests

src/ImageSharp/Formats/Tga/ImageExtensions.cs, tests/ImageSharp.Tests/Formats/GeneralFormatTests.cs, tests/ImageSharp.Tests/Formats/ImageFormatManagerTests.cs
This PR adds SaveAsTga extension method.
=> Add image extension method for save as tga

src/ImageSharp/Common/Helpers/ImageMaths.cs
GetMaxY must return height, this was ok.
GetMaxX must return width, but it returns height instead.
The PR change it to width.
All of you, keep up the good work.
=> Simple copy & paste error fixed, GetMaxX must return width not height.

tests/ImageSharp.Tests/Processing/Processors/Transforms/EntropyCropTest.cs
=> Add unit test for #1154: entropy crop on white image should not crop

src/ImageSharp/Memory/Buffer2D{T}.cs, src/ImageSharp/Memory/DiscontiguousBuffers/MemoryGroupExtensions.cs, tests/ImageSharp.Tests/Memory/DiscontiguousBuffers/MemoryGroupTests.cs
=> Cast to long and add test/guard. 

Directory.Build.props
The docs have changed since we implemented them and the icon does not appear in the Nuget Package Manager
https://github.com/NuGet/Home/wiki/Packaging-Icon-within-the-nupkg#icon
Proof of fix in package explorer
=> Fix nuget package icon.

src/ImageSharp/Formats/Png/PngMetadata.cs
Removed obsolete `PngTextProperties`, `TextData` Property should be used instead.
=> Remove obsolete PngTextProperties from png metadata

src/ImageSharp/Common/Exceptions/InvalidImageContentException.cs, src/ImageSharp/Formats/Bmp/BmpDecoder.cs, src/ImageSharp/Formats/Gif/GifDecoder.cs, src/ImageSharp/Formats/Gif/GifDecoderCore.cs, src/ImageSharp/Formats/Gif/GifThrowHelper.cs, src/ImageSharp/Formats/Jpeg/JpegDecoder.cs, src/ImageSharp/Formats/Jpeg/JpegThrowHelper.cs, src/ImageSharp/Formats/Png/PngDecoder.cs, src/ImageSharp/Formats/Png/PngThrowHelper.cs, src/ImageSharp/Formats/Tga/TgaDecoder.cs, src/ImageSharp/Formats/Tga/TgaThrowHelper.cs, tests/ImageSharp.Tests/Formats/Bmp/BmpDecoderTests.cs, tests/ImageSharp.Tests/Formats/Gif/GifDecoderTests.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.cs, tests/ImageSharp.Tests/Formats/Png/PngDecoderTests.cs, tests/ImageSharp.Tests/Formats/Tga/TgaDecoderTests.cs
Change a few exceptions to `InvalidImageContentException` which were missed in #1179
=> Change ImageFormatException to InvalidImageContentException

src/ImageSharp/Formats/Png/IPngEncoderOptions.cs, src/ImageSharp/Formats/Png/PngCompressionLevel.cs, src/ImageSharp/Formats/Png/PngEncoder.cs, src/ImageSharp/Formats/Png/PngEncoderOptions.cs, src/ImageSharp/Formats/Png/Zlib/ZlibDeflateStream.cs, tests/ImageSharp.Tests/Formats/Png/PngEncoderTests.cs
We were previously using an `int` which was nasty. This PR introduces a new `PngCompressionLevel` which constrains this property properly.
=> Introduce PngCompressionLevel

src/ImageSharp/Formats/Gif/GifDecoderCore.cs, src/ImageSharp/Formats/Jpeg/Components/Block8x8F.ScaledCopyTo.cs, src/ImageSharp/Memory/Buffer2DExtensions.cs, src/ImageSharp/Memory/Buffer2DRegion{T}.cs, src/ImageSharp/Processing/Processors/Quantization/DefaultPixelSamplingStrategy.cs, src/ImageSharp/Processing/Processors/Quantization/ExtensivePixelSamplingStrategy.cs, src/ImageSharp/Processing/Processors/Quantization/IPixelSamplingStrategy.cs, src/ImageSharp/Processing/Processors/Quantization/IQuantizer{TPixel}.cs, src/ImageSharp/Processing/Processors/Quantization/OctreeQuantizer{TPixel}.cs, src/ImageSharp/Processing/Processors/Quantization/PaletteQuantizer{TPixel}.cs, src/ImageSharp/Processing/Processors/Quantization/QuantizerUtilities.cs, src/ImageSharp/Processing/Processors/Quantization/WuQuantizer{TPixel}.cs, src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeWorker.cs, tests/ImageSharp.Benchmarks/Codecs/Jpeg/BlockOperations/Block8x8F_CopyTo2x2.cs, tests/ImageSharp.Tests/Formats/Jpg/Block8x8FTests.CopyToBufferArea.cs, tests/ImageSharp.Tests/Memory/BufferAreaTests.cs, tests/ImageSharp.Tests/Quantization/PixelSamplingStrategyTests.cs
Updates struct name, method, and any comment references to match.
=> BufferRegion => Buffer2DRegion

src/ImageSharp/Formats/Jpeg/Components/Decoder/JpegFrame.cs, src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs
This fixes an issue with very large jpeg images. For example: [This](https://pointlesswaymarks.com/Photos/2019/2019-october-sea-of-sand/1910-Sea-of-Sand-Full-Resolution.jpg)
I have not added a test image, because i dont want such super large test files in the repo. Im not sure how we can properly test it without it.
=> Change Scanlines and SamplesPerLine from short to int

src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeHelper.cs, tests/ImageSharp.Tests/Processing/Processors/Transforms/ResizeTests.cs
When calculating a target size/rectangle during resizing ensure that rounding doesn't leave a width/height of zero. Fixes #1195
=> Ensure min dimension of 1px following rounding.

src/ImageSharp/Formats/Png/Zlib/Adler32.cs, src/ImageSharp/Formats/Png/Zlib/Crc32.cs, tests/ImageSharp.Tests/Formats/Png/Adler32Tests.cs, tests/ImageSharp.Tests/Formats/Png/Crc32Tests.cs
Found an issue in the new hash implementations where the default value was returned rather than the input value on buffers with zero length.
=> Return input checksum value on empty buffer

src/ImageSharp/Formats/Tga/TgaImageFormatDetector.cs, tests/ImageSharp.Tests/Formats/Tga/TgaFileHeaderTests.cs
- If all color map spec bytes are zero when color map type is zero
- Width and height are not zero
The heuristic for detecting a TGA file now additionally checks:
- If all color map spec bytes are zero when color map type is zero.
- Width and height are not zero.
=> Additionally checks in DetectFormat for TGA files

src/ImageSharp/Formats/Png/PngEncoderCore.cs, tests/ImageSharp.Tests/Formats/Png/PngEncoderTests.cs
We weren't swapping the scanline buffers after collecting the filtered pixel in palette mode so certain filters were failing to encode correctly. 
Fixes #1211
=> Swap buffers when encoding PNG with Filtered Adam7 Palette mode

.github/workflows/build-and-test.yml
Turns out there's now an official CodeCov action. Giving it a shot to see if it fixes our issues.
https://github.com/marketplace/actions/codecov
=> Use official Codecov action

src/ImageSharp/Formats/Png/Zlib/Adler32.cs, tests/ImageSharp.Tests/Formats/Png/PngEncoderTests.cs, tests/ImageSharp.Tests/TestUtilities/TestEnvironment.Features.cs
Introduces the correct intrinsics support check in the enhanced Adler32 implementation. Fix #1228
@antonfirsov if you have any idea how to test this please let me know if you have any thoughts.
=> Update Adler32 to correctly filter intrinsics. 

src/ImageSharp/Configuration.cs, src/ImageSharp/GraphicOptionsDefaultsExtensions.cs, src/ImageSharp/Processing/DefaultImageProcessorContext{TPixel}.cs, tests/ImageSharp.Tests/GraphicOptionsDefaultsExtensionsTests.cs, tests/ImageSharp.Tests/Processing/FakeImageOperationsProvider.cs
Fix #1230 #1224 
The two dictionaries used in `Configuration `and `DefaultImageProcessorContext` were not thread safe and would throw when accessed in a parallel context.
I've replaced them with `ConcurrentDictionary` instances which fixes the issue but I wonder whether we should be exposing the property as `IDictionary<object, object>` over the concrete type since we require thread safety.
=> Use ConcurrentDictionary for options properties.

THIRD-PARTY-NOTICES.TXT
Adds a Third Party Notices file, closes #856 . Opening language copied from dotnet/runtime, license information copied from the various sources in the code base.
One thing to note, the shared infrastructure repo also has a file with MIT and BSD licensing. I didn't include that reference here as I see the shared infrastructure to be its own dependency. It probably deserves to have its own Third Party Notices file.
=> Added Third Party Notices document

.github/workflows/build-and-test.yml, Directory.Build.props, Directory.Build.targets, GitVersion.yml, ci-build.ps1, ci-pack.ps1, src/Directory.Build.props, src/Directory.Build.targets, src/ImageSharp/ImageSharp.csproj, tests/Directory.Build.targets
- Fixes  #1233 by replacing broken GitVersion with MinVer. This changes the nightly build numbers (unavoidable) but creates a better format in my opinion. Nightly builds now use the tag with added commit height e.g `1.0.0-rc.3.{height}`.
- Adds Source Link and Deterministic builds to the resultant output. A separate `snupkg` file is generated following best practice to keep package sizes down for consumers during restore. Fixes #1251
=> Better Builds

src/ImageSharp/Image.FromFile.cs, tests/ImageSharp.Tests/Image/ImageTests.Load_FileSystemPath_UseDefaultConfiguration.cs
Add LoadAsync methods that accepts `string path`.
This solves #1255
=> LoadAsync methods accepting string path.

src/ImageSharp/Image.Decode.cs
It was no async version of DiscoverDecoder, so I added DiscoverDecoderAsync. Since async methods can’t have out parameters, I return a tuple instead. I would not mind doing the same change on DiscoverDecoder so they look the same.
=> Async version of DiscoverDecoder

src/ImageSharp/Formats/Bmp/ImageExtensions.cs, src/ImageSharp/Formats/Gif/ImageExtensions.cs, src/ImageSharp/Formats/Jpeg/ImageExtensions.cs, src/ImageSharp/Formats/Png/ImageExtensions.cs, src/ImageSharp/Formats/Tga/ImageExtensions.cs, tests/ImageSharp.Tests/Formats/Bmp/ImageExtensionsTest.cs, tests/ImageSharp.Tests/Formats/Gif/ImageExtensionsTest.cs, tests/ImageSharp.Tests/Formats/Jpg/ImageExtensionsTest.cs, tests/ImageSharp.Tests/Formats/Png/ImageExtensionsTest.cs, tests/ImageSharp.Tests/Formats/Tga/ImageExtensionsTest.cs
This add several methods for saving images. Id addresses #1255.
There were no unit test for the existing extensions so I did not ceate anyone for this either. But I did make sure that all extensions for all file formats produced identical files with this code:
using SixLabors.ImageSharp;
using System;
using System.IO;
using System.Threading.Tasks;
namespace ConsoleAppImageSharpTester
{
class Program
{
static async Task Main(string[] args)
{
var img = Image.Load(@"testimage.png");
Directory.CreateDirectory(@".\test");
{
img.SaveAsTga(@".\test\norm_name.tga");
img.SaveAsTga(@".\test\norm_name_enc.tga", new SixLabors.ImageSharp.Formats.Tga.TgaEncoder());
await img.SaveAsTgaAsync(@".\test\async_name.tga");
await img.SaveAsTgaAsync(@".\test\async_name_enc.tga", new …
=> Save as extensions

.github/CONTRIBUTING.md
Add a section on building locally (I missed that the submodels existed when I first tried to build it)
I also changed the help link to go to the discussions section on GitHub rather than Gitter, because when I went to Gitter 
to ask for help I noticed the message:
> I'm leaving this channel open until Friday (GMT) and then I'm removing it. I can't keep following it when there is the Discussions pages available.
from @JimBobSquarePants
=> Add submodule info to CONTRIBUTING.md

Directory.Build.targets, tests/Directory.Build.targets, tests/ImageSharp.Tests/Formats/Tga/TgaTestUtils.cs, tests/ImageSharp.Tests/ImageSharp.Tests.csproj, tests/ImageSharp.Tests/TestUtilities/ReferenceCodecs/MagickReferenceDecoder.cs
Just a simple update to all reference dependencies. Might help with any .NET FX type forwarding issues
=> Update all dependency references.

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/config.yml, src/ImageSharp/Configuration.cs, src/ImageSharp/Formats/Bmp/BmpDecoder.cs, src/ImageSharp/Formats/Gif/GifDecoder.cs, src/ImageSharp/Formats/Jpeg/JpegDecoder.cs, src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs, src/ImageSharp/Formats/Png/PngDecoder.cs, src/ImageSharp/Formats/Png/PngDecoderCore.cs, src/ImageSharp/Formats/Tga/TgaDecoder.cs, src/ImageSharp/IO/BufferedReadStream.cs, src/ImageSharp/Image.FromStream.cs, tests/ImageSharp.Benchmarks/Codecs/Jpeg/DecodeJpegParseStreamOnly.cs, tests/ImageSharp.Benchmarks/General/IO/BufferedStreams.cs, tests/ImageSharp.Tests/ConfigurationTests.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.cs, tests/ImageSharp.Tests/Formats/Jpg/SpectralJpegTests.cs, tests/ImageSharp.Tests/Formats/Jpg/Utils/JpegFixture.cs, tests/ImageSharp.Tests/Formats/Png/PngDecoderTests.Chunks.cs, tests/ImageSharp.Tests/IO/BufferedReadStreamTests.cs
Adds a new property `Configuration.StreamProcessingBufferSize` which allows the configuration of internal buffers used to reduce synchronization costs of network streaming.  The value defaults to 8096 with a minimum of 128.
Fixes #1276
=> Make stream buffer size configurable. 

src/ImageSharp/Formats/WebP/EntropyIx.cs, src/ImageSharp/Formats/WebP/Lossless/Vp8LEncoder.cs
I have had a punt at EncoderAnalyze and think the crunch config should now come out of that OK.
The rest is very much WIP, I started carrying these configs through the EncodeStream in the Vp8LEncoder. The reference implementation starts spinning up threads and then comparing sizes and picking the best. There was nothing so far for that, is that something we want to do. It might be simpler, for now, to get it all working on a single thread save some headaches.
=> Work out the crunch configs for lossless webp

src/ImageSharp/IO/BufferedReadStream.cs, tests/ImageSharp.Tests/IO/BufferedReadStreamTests.cs
As the title says: The guard of the position was a bit too strict.
=> Change position guard from MustBeLessThanTo to MustBeLessThanOrEqualTo

.github/workflows/build-and-test.yml, README.md, src/ImageSharp/IO/ChunkedMemoryStream.cs
Increase `ChunkedMemoryStream` chunk length to 128k inline with `RecycledMemoryStream`
=> Bump ChunkedMemoryStream buffer length

src/ImageSharp/Processing/Processors/Convolution/BokehBlurProcessor.cs, tests/ImageSharp.Tests/Processing/Processors/Convolution/BokehBlurTest.cs
This PR does two things:
- Adds missing input validation for the blur radius and number of components (with tests)
- Reduces the overhead of the default constructor and skips the input validation there
=> Bokeh blur constructor tweaks (input validation, tiny speedup)

.github/workflows/build-and-test.yml, src/ImageSharp/Advanced/AdvancedImageExtensions.cs, src/ImageSharp/ImageExtensions.cs, tests/ImageSharp.Tests/Image/ImageTests.SaveAsync.cs
Adds the missing `Image.SaveAsync(Stream, IImageformat, CancellationToken)` extension. 
See https://stackoverflow.com/q/63639644/427899
I also cleaned up some bad copy/paste in the extension method documentation.
=> Add missing SaveAsync method

src/ImageSharp/Common/Helpers/Guard.cs
Small follow-up for https://github.com/SixLabors/SharedInfrastructure/pull/12 for the `ImageSharp`-specific `Guard` API.
=> Improved codegen in ImageSharp.Guard

src/Directory.Build.props, src/Directory.Build.targets, tests/ImageSharp.Tests/ImageSharp.Tests.csproj
.NET 5 bring a native `InternalVisibleTo` target implementation that is incompatible with our current implementation. The fix is simple, update our property to use the same `Key` attribute rather than `PublicKey`.
Tested using Visual Studio 16.8.0 Preview 2.1 and .NET 5 SDK 5.0.100-preview.8.20417.9
See issue first identified by @Sergio0694 
https://github.com/SixLabors/ImageSharp/pull/1314#issuecomment-673523488
And explanation from @tannergooding 
https://github.com/dotnet/sdk/issues/13289#issuecomment-684917354
=> Fix compatibility with NET 5 SDK InternalsVisibleTo

src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeProcessor{TPixel}.cs, tests/ImageSharp.Tests/Processing/Processors/Transforms/ResizeTests.cs
=> Use interest for target bounds. Fixes #1342

src/ImageSharp/Processing/Processors/Binarization/AdaptiveThresholdProcessor{TPixel}.cs, tests/ImageSharp.Tests/Processing/Binarization/AdaptiveThresholdTests.cs
I saw a clear typo in the code. So I added a new test which would validate the change. All the images used in the tests were previously grayscale so that the typo would go unnoticed. That being said, using adaptive thresholding on a color image is not a usual use case.
=> Fixed typo in AdaptiveThreshold

.github/workflows/build-and-test.yml, Directory.Build.props, Directory.Build.targets, src/Directory.Build.targets, tests/Directory.Build.targets
According to my [independent testing](https://github.com/dotnet/arcade/issues/6371#issuecomment-706291633) the RemoteExecutor still works with Ubuntu so we can use that OS as a workaround for #1376 for now.
=> Use Ubuntu for Code Coverage.

tests/Directory.Build.targets, tests/ImageSharp.Tests/Formats/Tga/TgaTestUtils.cs, tests/ImageSharp.Tests/TestUtilities/ReferenceCodecs/MagickReferenceDecoder.cs
This updates Magick.NET and sets an option for the BMP coder that fixes #1380. This option was added because the BMP coder in ImageMagick is now stricter and you need to set it to be able to read all files.
=> Upgraded Magick.NET.

src/ImageSharp/Formats/Bmp/BmpEncoderCore.cs, tests/ImageSharp.Tests/Formats/Bmp/BmpDecoderTests.cs, tests/ImageSharp.Tests/Formats/Bmp/BmpEncoderTests.cs, tests/ImageSharp.Tests/TestUtilities/ReferenceCodecs/MagickReferenceDecoder.cs
The `colorPaletteSize` is also part of the file size.
Fixes #1380.
=> Fixed setting the file size when the BMP encoder has a color palette

src/ImageSharp/Processing/Processors/Normalization/GlobalHistogramEqualizationProcessor{TPixel}.cs
Fixes #1204
From conversations with the .NET Native team. Thanks @Sergio0694 for arranging that.
>the crash happens while compiling CdfApplicationRowOperation.Invoke. I’m unclear what the best workaround would be. You can always place a NoOptimization flag on the method and that will probably get rid of the issue because the optimizer won’t be involved. From what I see on the stack, the optimizer is trying to hoist some operation out of the loop when it hits the problem.
The compiler actually fails unless both `CdfApplicationRowOperation.Invoke` and `GrayscaleLevelsRowOperation.Invoke` are marked with `MethodImplOptions.NoOptimization`. 
I attempted to work around the problem by manually inlining the luminance method call and better managing scope per loop iteration. While this didn't …
=> Fix ARM Build for UWP Release

src/ImageSharp/Formats/Jpeg/Components/Block8x8F.Generated.cs, src/ImageSharp/Formats/Jpeg/Components/Block8x8F.Generated.tt, src/ImageSharp/Formats/Jpeg/Components/Block8x8F.cs, src/ImageSharp/Formats/Jpeg/Components/Decoder/JpegBlockPostProcessor.cs, src/ImageSharp/Formats/Jpeg/Components/FastFloatingPointDCT.cs, tests/ImageSharp.Benchmarks/Codecs/Jpeg/BlockOperations/Block8x8F_AddInPlace.cs, tests/ImageSharp.Benchmarks/Codecs/Jpeg/BlockOperations/Block8x8F_MultiplyInPlaceBlock.cs, tests/ImageSharp.Benchmarks/Codecs/Jpeg/BlockOperations/Block8x8F_MultiplyInPlaceScalar.cs, tests/ImageSharp.Tests/Formats/Jpg/Block8x8FTests.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.Progressive.cs
Adds some AVX variants to some of the Block8x8F methods used in the DCT classes. The code was already fast so a 2X speedup isn't possible.
Managed to trim a little more off the jpeg benchmarks compared to #1374 
I also fixed some naming "Inplace" => "InPlace".
I think that's probably the most I can do in this area now. Colorspace translation and PixelOperations are the bottlenecks.
Benchmarks.
```
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19041.572 (2004/?/20H1)
Intel Core i7-8650U CPU 1.90GHz (Kaby Lake R), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=5.0.100-rc.2.20479.15
[Host]          : .NET Core 3.1.9 (CoreCLR 4.700.20.47201, CoreFX 4.700.20.47203), X64 RyuJIT
AVX             : .NET Core 3.1.9 (CoreCLR 4.700.20.47201, CoreFX 4.700.20.47203), X64 RyuJIT
SSE             : .NET …
```
=> Optimize Block8x8F low hanging fruit and fix naming

src/ImageSharp/Common/Helpers/IComponentShuffle.cs, src/ImageSharp/Common/Helpers/SimdUtils.HwIntrinsics.cs, src/ImageSharp/Common/Helpers/SimdUtils.Shuffle.cs, src/ImageSharp/PixelFormats/PixelImplementations/Generated/Argb32.PixelOperations.Generated.cs, src/ImageSharp/PixelFormats/PixelImplementations/Generated/Bgra32.PixelOperations.Generated.cs, src/ImageSharp/PixelFormats/PixelImplementations/Generated/Rgba32.PixelOperations.Generated.cs, src/ImageSharp/PixelFormats/PixelImplementations/Generated/_Common.ttinclude, src/ImageSharp/PixelFormats/Utils/PixelConverter.cs, tests/ImageSharp.Benchmarks/Color/Bulk/ShuffleByte4Channel.cs, tests/ImageSharp.Benchmarks/Color/Bulk/ShuffleFloat4Channel.cs, tests/ImageSharp.Benchmarks/Config.HwIntrinsics.cs, tests/ImageSharp.Benchmarks/General/PixelConversion/PixelConversion_ConvertFromRgba32.cs, tests/ImageSharp.Benchmarks/ImageSharp.Benchmarks.csproj, tests/ImageSharp.Tests/Common/SimdUtilsTests.Shuffle.cs, tests/ImageSharp.Tests/Common/SimdUtilsTests.cs, tests/ImageSharp.Tests/Formats/Png/PngEncoderTests.cs, tests/ImageSharp.Tests/PixelFormats/PixelConverterTests.ReferenceImplementations.cs, tests/ImageSharp.Tests/PixelFormats/PixelConverterTests.cs, tests/ImageSharp.Tests/TestUtilities/FeatureTesting/FeatureTestRunner.cs, tests/ImageSharp.Tests/TestUtilities/Tests/FeatureTestRunnerTests.cs
Adds new `SimdUtils.Shuffle4Channel` methods with overloads for `float` and `byte`. This is the first part of a series of PRs that will complete #1354 
Methods are SIMD optimized on NET Core 3.1+
`public static void Shuffle4Channel(ReadOnlySpan<float> source, Span<float> dest, byte control)` Avx, Sse
`public static void Shuffle4Channel(ReadOnlySpan<byte> source, Span<byte> dest, byte control)` Avx2, Ssse3.
There don't appear to be any equivalent methods for [`System.Numerics`](https://github.com/dotnet/runtime/issues/14362) so I don't think we can add any optimization there.
Additional utility methods have also been added to `SimdUtils.Shuffle` which allow the generation of shuffle controls.
**Benchmarks**
**4 Channel Float**
```
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19041.572 …
```
=> Add 4 Channel Shuffle Intrinsics

src/ImageSharp/Image{TPixel}.cs
Saw someone complaining on Discord about this so fixed it.
=> Optimize TryGetSinglePixelSpan 

src/ImageSharp/Common/Helpers/Shuffle/IComponentShuffle.cs, src/ImageSharp/Common/Helpers/Shuffle/IPad3Shuffle4.cs, src/ImageSharp/Common/Helpers/Shuffle/IShuffle3.cs, src/ImageSharp/Common/Helpers/Shuffle/IShuffle4Slice3.cs, src/ImageSharp/Common/Helpers/SimdUtils.HwIntrinsics.cs, src/ImageSharp/Common/Helpers/SimdUtils.Shuffle.cs, src/ImageSharp/PixelFormats/PixelImplementations/Generated/Argb32.PixelOperations.Generated.cs, src/ImageSharp/PixelFormats/PixelImplementations/Generated/Bgr24.PixelOperations.Generated.cs, src/ImageSharp/PixelFormats/PixelImplementations/Generated/Bgra32.PixelOperations.Generated.cs, src/ImageSharp/PixelFormats/PixelImplementations/Generated/Rgb24.PixelOperations.Generated.cs, src/ImageSharp/PixelFormats/PixelImplementations/Generated/Rgba32.PixelOperations.Generated.cs, src/ImageSharp/PixelFormats/PixelImplementations/Generated/_Common.ttinclude, src/ImageSharp/PixelFormats/Utils/PixelConverter.cs, tests/ImageSharp.Benchmarks/Color/Bulk/FromVector4.cs, tests/ImageSharp.Benchmarks/Color/Bulk/FromVector4_Rgb24.cs, tests/ImageSharp.Benchmarks/Color/Bulk/Pad3Shuffle4Channel.cs, tests/ImageSharp.Benchmarks/Color/Bulk/Shuffle3Channel.cs, tests/ImageSharp.Benchmarks/Color/Bulk/Shuffle4Slice3Channel.cs, tests/ImageSharp.Benchmarks/Color/Bulk/ShuffleFloat4Channel.cs, tests/ImageSharp.Benchmarks/Color/Bulk/ToVector4_Rgb24.cs, tests/ImageSharp.Tests/Common/SimdUtilsTests.Shuffle.cs, tests/ImageSharp.Tests/Common/SimdUtilsTests.cs
Adds three methods to `SimdUtils`:
1.  `Pad3Shuffle4` Pads a buffer representing 3 channel pixels to 4 channels and shuffles the result.
2.  `Shuffle4Slice3` Shuffles a buffer representing 4 channel pixels and slices it to 3 channels.
3. `Shuffle3` Shuffles a buffer representing 3 channel pixels.
All fallbacks are better than or equal two current implementations.
~I've completed a basic implementation for now with results in ~2.5-3x speedup. I looked into more loop unrolling based on this [example](https://stackoverflow.com/a/2974266/427899) but kept messing up my offsets so I left it. @saucecontrol if you fancy helping me here please do.~ Fixed, thanks @saucecontrol!
~Once the initial implementation is reviewed I will make the methods generic and add optimized fallback versions of `XYZW` …
=> 3 <==> 4 Channel Shuffling with Hardware Intrinsics

src/ImageSharp/Formats/Bmp/BmpEncoderCore.cs
Just a small improvement in writing 8 bit bitmaps with a palette: Converting the quantized colors to rgb is now done as bulk convert.
=> Use bulk conversion in Write8BitColor

src/ImageSharp/Processing/Processors/Normalization/AdaptiveHistogramEqualizationProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Normalization/GlobalHistogramEqualizationProcessor{TPixel}.cs, tests/ImageSharp.Benchmarks/Processing/HistogramEqualization.cs
This PR changes the histogram equalization to use GetPixelRowSpan to access pixel data to fix an Access Violation issue for very large images reported in #1429.
=> Use GetPixelRowSpan to access pixel data in Histogram equalization

src/ImageSharp/PixelFormats/PixelImplementations/PixelOperations/RgbaVector.PixelOperations.cs
When using any of the generic [`Image.CloneAs<TPixel>` APIs](https://github.com/SixLabors/ImageSharp/blob/521fae35a14c7953f720a094d24b59b2f7d98555/src/ImageSharp/Image.cs#L124), if the target format was `RgbaVector`, the selected code paths was not optimized to take advantage of the fact that `RgbaVector` is blittable to `Vector4`. In particular, this `PixelOperations<TPixel>.To` method was called:
https://github.com/SixLabors/ImageSharp/blob/521fae35a14c7953f720a094d24b59b2f7d98555/src/ImageSharp/PixelFormats/PixelOperations%7BTPixel%7D.cs#L103-L134
You can see the method is virtual but was not overridden by `RgbaVector`, so this slower implementation was used, which required both chunking of the target span as well as doing an extra copy to a temporary buffer. This PR adds a new …
=> PixelOperations<TPixel>.From<RgbaVector> speedup

.gitignore, src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeHelper.cs, tests/ImageSharp.Tests/Processing/Processors/Transforms/ResizeTests.cs, tests/ImageSharp.Tests/TestUtilities/TestEnvironment.cs
The 3 resize tests skipped on macOS are working on my machine. I'm opening this to see what is happening on CI.
=> Enable resize tests on MacOs

src/ImageSharp/Processing/Processors/Convolution/BokehBlurProcessor.cs, src/ImageSharp/Processing/Processors/Convolution/BokehBlurProcessor{TPixel}.cs
The `BokehBlurProcessor<TPixel>` type had one of the internal row iterators that worked on non-generic types, but having that nested type defined within the generic processor class caused the code to be duplicated and compiled again for every single pixel type that the process was applied to. I moved that to the non-generic processor type so the same generic instantiation can be reduced. This will reduce the binary size in AOT scenarios, and reduce the load on the JIT otherwise.
=> Reduce code duplication due to reified generics

.github/workflows/build-and-test.yml
- Added cache action for Nuget packages for speedup Nuget restore before each CI builds
=> Add cache for Nuget packages

.github/workflows/build-and-test.yml
- Added action to store images `tests/Images/ActualOutput/*` as build artifacts
=> Add action to save Output Images for failed tests

src/ImageSharp/Processing/Processors/Filters/FilterProcessor{TPixel}.cs, tests/ImageSharp.Tests/Processing/Filters/BrightnessTest.cs
Use scaled vectors in FilterProcessor to fix #1459.
=> Filter processor should use scaled vectors.

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/config.yml, .github/workflows/build-and-test.yml
Discussions moved the cheese and broke our links.
=> Fix link + other docs tweaks.

src/ImageSharp/ColorSpaces/Companding/SRgbCompanding.cs, src/ImageSharp/Common/Helpers/Numerics.cs, src/ImageSharp/PixelFormats/Utils/Vector4Converters.cs, src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeKernel.cs, src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeWorker.cs, tests/ImageSharp.Benchmarks/Processing/Resize.cs, tests/ImageSharp.Tests/PixelFormats/PixelOperations/PixelOperationsTests.cs, tests/ImageSharp.Tests/TestUtilities/ApproximateFloatComparer.cs
Updates the bulk sRGB Companding method to use the similar LUT approach as MagicScaler (_thanks @saucecontrol !_ )
Results are awesome. Massive speedup in real world scenarios.
I noticed some oddities (_I'd previously introduced_) in the existing unit tests during the work which I cleaned up also.
=> Much Faster sRGB Companding

src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeProcessor.cs, src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeProcessor{TPixel}.cs, src/ImageSharp/Processing/ResizeOptions.cs, tests/ImageSharp.Tests/Processing/Processors/Transforms/ResizeTests.cs
Added PremultiplyAlpha to the ResizeOptions. This option was always on by default, but now the user has the ability to turn it off through the options.
Fixes #1498
=> Add PremultiplyAlpha to ResizeOptions

src/ImageSharp/Formats/Jpeg/Components/Encoder/RgbToYCbCrConverterLut.cs, src/ImageSharp/Formats/Jpeg/Components/Encoder/RgbToYCbCrConverterVectorized.cs, src/ImageSharp/Formats/Jpeg/Components/Encoder/YCbCrForwardConverter{TPixel}.cs, tests/ImageSharp.Benchmarks/Format/Jpeg/Components/Encoder/YCbCrForwardConverterBenchmark.cs, tests/ImageSharp.Tests/Formats/Jpg/RgbToYCbCrConverterTests.cs
Touches #1476 with a vectorized implementation of the RGB -> YCbCr conversions.
It is worth noting, that the following benchmarks don't show the entire picture. The current lookup table converter uses 3kB of lookup tables that pollute the cache and likely negatively impact subsequent operations in the encoding chain.
``` ini
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19042
Intel Core i7-9750H CPU 2.60GHz, 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=5.0.102
[Host]     : .NET Core 3.1.11 (CoreCLR 4.700.20.56602, CoreFX 4.700.20.56604), X64 RyuJIT
DefaultJob : .NET Core 3.1.11 (CoreCLR 4.700.20.56602, CoreFX 4.700.20.56604), X64 RyuJIT
```
|            Method |      Mean |    Error |   StdDev | Ratio |
|------------------ |----------:|---------:|---------:|------:|
|        ConvertLut …
=> Vectorize Jpeg Encoder Color Conversion

src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeKernel.cs, tests/ImageSharp.Tests/Processing/Processors/Transforms/ResizeTests.cs
Related to #1476, this PR includes some speed improvements to the resize kernels.
In particular, it introduces a new vectorized path using AVX2/FMA operations to perform the convolutions.
For those interested, [here is](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEBDAzgWwB8ABABgAJiBGAOgDkBXfGKASzFwG4BYAKDMq0ASgwB2GVsxoBhCPgAOrADYsAyiwBu7GFz4DqNEeMkwaASXFtRudrv4UDRiVIsYrNjjQAaADiQ9ePlZxFlFsJXJYbAATCFElAE9yMVxsADMYclw3BjAMciEdVgAvGABpUJglPgBvPnIG8nk2DWwMTKjY+KS0pQg2gCpyYAY0jKgABTcAxvJ6xuIAZnJg/IAZGFEAcwwAC3mGut5Z2YBtAFkYPYhoswUlAApL69v7gHl5CTjcGgBBLa2sFwNg0MAsSmCwS2AEoALoHE5bK4zRoAXwRCKW5AAajA8tAUORZKINBAlKDZLAHrA0ji8RgCZEIAB3VQYbBQDCFNLQhFHE6NXr9DBDEZjNTsznkAC85D2rB+YvGUygKIFQsGw1G4wAoqJojKteKoGyOfkANTkB7yn4bbZ7cgAMnIAD9FtC1SdcfioAAmACsSAAPBqMAA+SI6BhKDABpAAfQosu9DL9gZDfTaYZoAC0WBBPbMU9 …
=> Speed improvements to resize kernel (w/ SIMD)

src/ImageSharp/Common/Helpers/SimdUtils.HwIntrinsics.cs, src/ImageSharp/Formats/Jpeg/Components/Block8x8F.cs, tests/ImageSharp.Benchmarks/Codecs/Jpeg/BlockOperations/Block8x8F_Scale16X16To8X8.cs
In the context of #1476 I looked for low hanging fruit on the hot path of the JPEG encoding pipeline.
Using a benchmark (encoding a 4K image) with the ETW Profiler attached, I've noticed that `Block8x8F.Scale16X16To8X8` is responsible for 9.8% of the total time taken. I've noticed that the method is the optimal candidate for vectorization (AVX2) and went for it. 
* The benchmarks below show a **12x improvement** in `Block8x8F.Scale16X16To8X8` 🚀
* This reduces the total encoding time of my sample image by **~9%** from 475.9 ms to 434.1 ms
``` ini
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19042
Intel Core i7-9750H CPU 2.60GHz, 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=5.0.102
[Host] : .NET Core 3.1.11 (CoreCLR 4.700.20.56602, CoreFX 4.700.20.56604), X64 RyuJIT
main   : .NET Core …
```
=> Vectorize Scale16X16To8X8

.github/workflows/build-and-test.yml, src/ImageSharp/ImageSharp.csproj, tests/ImageSharp.Benchmarks/ImageSharp.Benchmarks.csproj, tests/ImageSharp.Tests.ProfilingSandbox/ImageSharp.Tests.ProfilingSandbox.csproj, tests/ImageSharp.Tests/ImageSharp.Tests.csproj
=> Add net5.0 targetframework

src/ImageSharp/Image.WrapMemory.cs, tests/ImageSharp.Tests/Image/ImageTests.WrapMemory.cs
Changes memory length guards in Image.WrapMemory() methods to allow passing blocks that are larger than the image size. Fixes #1522.
=> Change size guards for WrapMemory to allow Memory/IMemoryOwner blocks to be larger than the image size

src/ImageSharp/Formats/Jpeg/Components/Block8x8F.cs, src/ImageSharp/Formats/Jpeg/Components/RowOctet.cs, src/ImageSharp/Formats/Jpeg/JpegEncoderCore.cs, tests/ImageSharp.Benchmarks/Codecs/Jpeg/EncodeJpeg.cs, tests/ImageSharp.Tests.ProfilingSandbox/Program.cs, tests/ImageSharp.Tests/ProfilingBenchmarks/JpegProfilingBenchmarks.cs
This is a test/benchmark only change.
Been playing around with `JpegEncoder` to get some detailed data about our current performance numbers. In order to have proper profiler results (with `PROFILING` constant enabled), I had to change some of the `[MethodImpl]` attributes. Namely: switch to conditional inlining (`[MethodImpl(InliningOptions.ShortMethod)]`) in huffmann methods, and always inline in `Block8x8F` indexer.
Additionally:
- Changed the `EncodeJpeg`  benchmark to work with a bigger image, and move `MemoryStream` creation to GlobalSetup
- Added `JpegProfilingBenchmarks.EncodeJpeg_SingleMidSize`
```
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19042
Intel Core i7-8650U CPU 1.90GHz (Kaby Lake R), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=5.0.200-preview.20614.14
[Host]     : …
```
=> Better JpegEncoder profiling & benchmarks

src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeKernel.cs, tests/ImageSharp.Tests/Processing/Transforms/ResizeTests.cs, tests/ImageSharp.Tests/TestUtilities/Tests/FeatureTestRunnerTests.cs
Adds a check for Avx2 in ResizeKernel, fix for #1546
=> Add check for Avx2 in ResizeKernel

src/ImageSharp/Formats/Jpeg/Components/Block8x8F.cs
Fixes the bug reported by @jrdiver and @JimBobSquarePants in #1547/#1549 introduced in #1517.
=> Fix vectorized 4:2:0 subsampling

src/ImageSharp/Processing/BinaryThresholdMode.cs, src/ImageSharp/Processing/Extensions/Binarization/BinaryThresholdExtensions.cs, src/ImageSharp/Processing/Processors/Binarization/BinaryThresholdProcessor.cs, src/ImageSharp/Processing/Processors/Binarization/BinaryThresholdProcessor{TPixel}.cs, tests/ImageSharp.Tests/Processing/Binarization/BinaryThresholdTest.cs, tests/ImageSharp.Tests/Processing/Processors/Binarization/BinaryThresholdTest.cs
=> BinaryThresholdColorComponent -> BinaryThresholdMode

src/ImageSharp/Processing/Extensions/ProcessingExtensions.IntegralImage.cs, src/ImageSharp/Processing/Extensions/ProcessingExtensions.cs, tests/ImageSharp.Tests/Processing/IntegralImageTests.cs
This pull request replaces #1536.
=> Added image integral algorithm.

src/ImageSharp/Image.FromBytes.cs, tests/ImageSharp.Tests/Formats/Gif/GifDecoderTests.cs
Discovered an API bug while answering #1571. The fix is a breaking change, but very scoped one.
=> Image.Load(byte[]) should return non-generic Image

src/ImageSharp/Advanced/AotCompilerTools.cs, src/ImageSharp/Advanced/PreserveAttribute.cs, src/ImageSharp/Processing/Processors/Dithering/PaletteDitherProcessor{TPixel}.cs
If you upcast a class that implements a virtual generic method to a superclass or interface, the AoT build may not work properly.
They must be seeded appropriately.
[Details are explained here.](https://github.com/SixLabors/ImageSharp/issues/946#issuecomment-792549374)
=> Seed more methods with AotCompilerTools.

src/ImageSharp/Formats/Bmp/BmpBitsPerPixel.cs, src/ImageSharp/Formats/Bmp/BmpDecoderCore.cs, src/ImageSharp/Formats/Bmp/BmpEncoderCore.cs, tests/ImageSharp.Tests/Formats/Bmp/BmpEncoderTests.cs
As the title says, this will change the bitmap encoder to support encoding 4 bits per pixel bitmaps.
=> Add support for encoding 4 bit per pixel bitmaps

src/ImageSharp/Formats/Bmp/BmpBitsPerPixel.cs, src/ImageSharp/Formats/Bmp/BmpDecoderCore.cs, src/ImageSharp/Formats/Bmp/BmpEncoder.cs, src/ImageSharp/Formats/Bmp/BmpEncoderCore.cs, src/ImageSharp/Formats/Bmp/IBmpEncoderOptions.cs, tests/ImageSharp.Tests/Formats/Bmp/BmpEncoderTests.cs
Add support for encoding 1 bit per pixel bitmaps.
@JimBobSquarePants: The bitmap encoder uses Octree Quantizer as a default. This quantizer does seem to have problems with just 2 colors. Im not so familiar with the Octree Quantizer. Is not possible to quantize with just to colors or is it maybe an issue we should look into? All indices seem to be 0.
If i change it to Wu quantizer it works with two colors.
=> Add support for encoding 1 bit per pixel bitmaps

src/ImageSharp/Common/Helpers/Numerics.cs, src/ImageSharp/Formats/Png/Filters/AverageFilter.cs, src/ImageSharp/Formats/Png/Filters/PaethFilter.cs, src/ImageSharp/Formats/Png/Filters/SubFilter.cs, src/ImageSharp/Formats/Png/Filters/UpFilter.cs, tests/ImageSharp.Tests/Formats/Png/PngFilterTests.cs, tests/ImageSharp.Tests/Formats/Png/ReferenceImplementations.cs
=> Vectorize Png encoder filters

src/ImageSharp/Processing/Processors/Normalization/AdaptiveHistogramEqualizationProcessor.cs, src/ImageSharp/Processing/Processors/Normalization/AdaptiveHistogramEqualizationProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Normalization/HistogramEqualizationProcessor.cs, src/ImageSharp/Processing/Processors/Normalization/HistogramEqualizationProcessor{TPixel}.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegEncoderTests.cs, tests/ImageSharp.Tests/Processing/Normalization/HistogramEqualizationTests.cs, tests/Images/External/ReferenceOutput/HistogramEqualizationTests/Issue1640_L16_TestPattern5120x9234.png
Fixes the issue identified in #1640 
Ensures that the `cdfLutSpan` buffer is cleared before each use. I also did a couple of code style cleanup bits to remove squigglies and an indexer check removal.
I spotted areas where we could improve performance but did not touch them at this time.
=> AdaptiveHistogramEqualizationProcessor. Fix for large images

src/ImageSharp/Formats/Tiff/TiffDecoderCore.cs, src/ImageSharp/Formats/Tiff/Writers/TiffPaletteWriter{TPixel}.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffDecoderTests.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffEncoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Tiff/flower-minisblack-04.tiff, tests/Images/Input/Tiff/flower-palette-04.tiff
This **PR** makes sure to write padding when encoding 4-bit paletted tiff's with uneven width.
=> Make sure encoding 4bit paletted tiff rows are byte aligned

src/ImageSharp/Formats/Tiff/Constants/TiffConstants.cs, src/ImageSharp/Formats/Tiff/PhotometricInterpretation/Rgb444TiffColor{TPixel}.cs, src/ImageSharp/Formats/Tiff/PhotometricInterpretation/RgbPlanarTiffColor{TPixel}.cs, src/ImageSharp/Formats/Tiff/PhotometricInterpretation/TiffColorDecoderFactory{TPixel}.cs, src/ImageSharp/Formats/Tiff/PhotometricInterpretation/TiffColorType.cs, src/ImageSharp/Formats/Tiff/TiffBitsPerPixel.cs, src/ImageSharp/Formats/Tiff/TiffBitsPerSample.cs, src/ImageSharp/Formats/Tiff/TiffBitsPerSampleExtensions.cs, src/ImageSharp/Formats/Tiff/TiffDecoderCore.cs, src/ImageSharp/Formats/Tiff/TiffDecoderOptionsParser.cs, src/ImageSharp/Formats/Tiff/TiffEncoderCore.cs, src/ImageSharp/Formats/Tiff/TiffEncoderEntriesCollector.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffDecoderTests.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffEncoderTests.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffMetadataTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/ImageSharp.Tests/TestUtilities/ReferenceCodecs/MagickReferenceDecoder.cs, tests/Images/Input/Tiff/flower-rgb-contig-02.tiff, tests/Images/Input/Tiff/flower-rgb-contig-04.tiff, tests/Images/Input/Tiff/flower-rgb-contig-10.tiff, tests/Images/Input/Tiff/flower-rgb-contig-14.tiff, tests/Images/Input/Tiff/flower-rgb-planar-02.tiff, tests/Images/Input/Tiff/flower-rgb-planar-04.tiff, tests/Images/Input/Tiff/flower-rgb-planar-10.tiff, tests/Images/Input/Tiff/flower-rgb-planar-14.tiff
This **PR** adds support for decoding:
- 12 bit (4 bits per channel, RGB chunky) TIFF images.
- 6 bit (2 bits per channel, RGB chunky) TIFF images.
- 30 bit (10 bits per channel, RGB chunky) TIFF images.
- 42 bit (14 bits per channel, RGB chunky) TIFF images.
/cc @IldarKhayrutdinov
=> Add support for decoding 6, 12, 30, 42 bits per pixel tiff's

src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeKernelMap.cs, tests/ImageSharp.Tests/Processing/Processors/Transforms/ResizeKernelMapTests.cs
Fixes #1616
Updates the period calculation to use `GreatestCommonDivisor` as per issue.
=> Use GreatestCommonDivisor to prevent overflow

src/ImageSharp/Formats/Gif/GifDecoderCore.cs, tests/ImageSharp.Tests/Formats/Gif/GifDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/External/ReferenceOutput/GifDecoderTests/Issue1668_InvalidColorIndex_Rgba32_issue1668_invalidcolorindex.png, tests/Images/Input/Gif/issues/issue1668_invalidcolorindex.gif
As reported by #1668, the image seem to have a wrong color index at frame 16. This **PR** clamps the index between 0 and the color map size.
=> GifDecoder: Clamp color map index

src/ImageSharp/Memory/Buffer2DExtensions.cs, src/ImageSharp/Memory/Buffer2D{T}.cs, src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeKernelMap.cs, src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeWorker.cs, tests/ImageSharp.Tests/Formats/Jpg/SpectralJpegTests.cs, tests/ImageSharp.Tests/Helpers/ParallelRowIteratorTests.cs, tests/ImageSharp.Tests/Image/ImageTests.WrapMemory.cs, tests/ImageSharp.Tests/Memory/Buffer2DTests.cs, tests/ImageSharp.Tests/TestUtilities/TestImageExtensions.cs
We need to ensure we don't incorrectly use the single memory/span methods and prevent having to do work like #1662 
Should also help with refactoring #1625
=> Rename unsafe memory methods to use Dangerous prefix.

src/ImageSharp/Formats/Gif/GifEncoderCore.cs, src/ImageSharp/Processing/Processors/Quantization/EuclideanPixelMap{TPixel}.cs, src/ImageSharp/Processing/Processors/Quantization/OctreeQuantizer{TPixel}.cs, src/ImageSharp/Processing/Processors/Quantization/PaletteQuantizer.cs, src/ImageSharp/Processing/Processors/Quantization/PaletteQuantizer{TPixel}.cs, src/ImageSharp/Processing/Processors/Quantization/WuQuantizer{TPixel}.cs
Disposing and recreating a pixel map puts pressure on the allocator when processing multi-frame gifs. By clearing the map we can avoid this.
=> Allow clearing and reusing a pixel map.

src/ImageSharp/Common/Extensions/StreamExtensions.cs, src/ImageSharp/Formats/Bmp/BmpDecoderCore.cs, src/ImageSharp/Formats/Bmp/BmpEncoderCore.cs, src/ImageSharp/Formats/Tga/TgaDecoderCore.cs, src/ImageSharp/Formats/Tga/TgaEncoderCore.cs, src/ImageSharp/Memory/MemoryAllocatorExtensions.cs
Refactors `MemeoryAllocatorExtensions.AllocatePaddedPixelRowBuffer` to return `IMemoryOwner<byte>`.
Touches #1675
=> Update AllocatePaddedPixelRowBuffer to use IMemoryOwner<byte>

src/ImageSharp/Formats/Bmp/BmpDecoderCore.cs, src/ImageSharp/Formats/Gif/GifDecoderCore.cs, src/ImageSharp/Formats/Gif/GifEncoderCore.cs, src/ImageSharp/Formats/Tga/TgaDecoderCore.cs, src/ImageSharp/Formats/Tiff/Compression/Compressors/PackBitsCompressor.cs, src/ImageSharp/Formats/Tiff/PhotometricInterpretation/RgbPlanarTiffColor{TPixel}.cs, src/ImageSharp/Formats/Tiff/TiffDecoderCore.cs, src/ImageSharp/Formats/Tiff/Writers/TiffCompositeColorWriter{TPixel}.cs, src/ImageSharp/IO/ChunkedMemoryStream.cs, src/ImageSharp/Image.Decode.cs, tests/ImageSharp.Tests/Formats/Bmp/BmpEncoderTests.cs
More refactoring to use `IMemoryOwner<byte>`.
=> Remove IManagedByteBuffer Part 2

tests/ImageSharp.Tests/Formats/Bmp/BmpDecoderTests.cs, tests/ImageSharp.Tests/Formats/Bmp/BmpEncoderTests.cs
There is no need anymore to skip the 4 bit and 1 bit bitmap tests on linux. This ****PR**** removes skipping those tests.
=> Do not skip 4-bit and 1-bit bmp tests on linux

src/ImageSharp/Common/Extensions/StreamExtensions.cs, src/ImageSharp/Common/Helpers/DebugGuard.cs, src/ImageSharp/Formats/Png/Filters/AverageFilter.cs, src/ImageSharp/Formats/Png/Filters/PaethFilter.cs, src/ImageSharp/Formats/Png/Filters/SubFilter.cs, src/ImageSharp/Formats/Png/Filters/UpFilter.cs, src/ImageSharp/Formats/Png/PngChunk.cs, src/ImageSharp/Formats/Png/PngDecoderCore.cs, src/ImageSharp/Formats/Png/PngEncoderCore.cs, tests/ImageSharp.Tests/Formats/Png/ReferenceImplementations.cs
Migration to `IMemoryOwner<byte>` for png decoder/encoder
=> Migrate ManagedByteBuffer 3

src/ImageSharp/Compression/Zlib/Deflater.cs, src/ImageSharp/Compression/Zlib/DeflaterEngine.cs, src/ImageSharp/Compression/Zlib/DeflaterHuffman.cs, src/ImageSharp/Compression/Zlib/DeflaterOutputStream.cs, src/ImageSharp/Compression/Zlib/DeflaterPendingBuffer.cs, src/ImageSharp/Formats/Bmp/BmpEncoderCore.cs, src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs, src/ImageSharp/Formats/Png/PngDecoderCore.cs, src/ImageSharp/Formats/Tiff/Writers/TiffBiColorWriter{TPixel}.cs, src/ImageSharp/Formats/Tiff/Writers/TiffPaletteWriter{TPixel}.cs, src/ImageSharp/Memory/Allocators/MemoryAllocator.cs, tests/ImageSharp.Tests/Formats/Tiff/PhotometricInterpretation/RgbPlanarTiffColorTests.cs
Removes the last usage outside of tests for `IManagedByteBuffer` and `MemoryAllocator.AllocateManagedByteBuffer(...)` to make it easier to refactor the memory allocator.
=> Migrate ManagedByteBuffer 4

src/ImageSharp/Formats/Jpeg/Components/Encoder/YCbCrForwardConverter{TPixel}.cs, tests/ImageSharp.Tests/Formats/Bmp/BmpDecoderTests.cs, tests/ImageSharp.Tests/Formats/Bmp/BmpEncoderTests.cs, tests/ImageSharp.Tests/Formats/Gif/GifDecoderTests.cs, tests/ImageSharp.Tests/Formats/Gif/GifEncoderTests.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegEncoderTests.cs, tests/ImageSharp.Tests/Formats/Png/PngDecoderTests.cs, tests/ImageSharp.Tests/Formats/Png/PngEncoderTests.cs, tests/ImageSharp.Tests/Formats/Tga/TgaDecoderTests.cs, tests/ImageSharp.Tests/Formats/Tga/TgaEncoderTests.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffDecoderTests.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffEncoderTests.cs
We are seeing lately alot of OOM issues with the CI. This is an attempt to reduce the memory pressure by running high memory  tests serial. This can be achieved by putting them in the same test collection with the attribute:
```[Collection("RunSerial")]```
Since i have no better measure, what tests are using the most memory, i guessed the Encoder/Decoder tests are possible candidates, so i have put them in one Collection.
=> Run some high memory tests serial

tests/Directory.Build.targets, tests/ImageSharp.Benchmarks/Color/ColorspaceCieXyzToCieLabConvert.cs, tests/ImageSharp.Benchmarks/Color/ColorspaceCieXyzToHunterLabConvert.cs, tests/ImageSharp.Benchmarks/Color/ColorspaceCieXyzToLmsConvert.cs, tests/ImageSharp.Benchmarks/Color/ColorspaceCieXyzToRgbConvert.cs, tests/ImageSharp.Benchmarks/Color/RgbWorkingSpaceAdapt.cs
The Colourful library is used in the benchmarks, and recently, there was a [version 3.0.0](https://github.com/tompazourek/Colourful/releases/tag/3.0.0) released. I updated the package reference, and the converter code to reflect the new API.
=> Updated Colourful from 2.0.5 to 3.0.0 (only benchmarks affected)

src/ImageSharp/Formats/Jpeg/Components/Decoder/HuffmanScanDecoder.cs, src/ImageSharp/Formats/Jpeg/Components/Decoder/IRawJpegData.cs, src/ImageSharp/Formats/Jpeg/Components/Decoder/JpegBlockPostProcessor.cs, src/ImageSharp/Formats/Jpeg/Components/Decoder/JpegComponent.cs, src/ImageSharp/Formats/Jpeg/Components/Decoder/JpegComponentPostProcessor.cs, src/ImageSharp/Formats/Jpeg/Components/Decoder/JpegFrame.cs, src/ImageSharp/Formats/Jpeg/Components/Decoder/SpectralConverter{TPixel}.cs, src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.Images.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.cs, tests/ImageSharp.Tests/Formats/Jpg/ParseStreamTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Jpg/issues/fuzz/Issue1693-IndexOutOfRangeException-A.jpg, tests/Images/Input/Jpg/issues/fuzz/Issue1693-IndexOutOfRangeException-B.jpg
- SOF/SOS marker parsing code refactoring, added comments
- Fixed #1693, added tests for them
- Huffman tables are now part of the `HuffmanScanDecoder`
=> Jpeg decoder refactoring, fixed 1693

src/ImageSharp/Formats/Png/PngDecoderCore.cs, src/ImageSharp/Formats/Tiff/Compression/Decompressors/DeflateTiffCompression.cs
(68 of the 71 _existing_ PngDecoder tests already fail when run against `master`, before and after this change, and I'm not sure if that's expected... presumably not?  Maybe I'm just doing something wrong?  I'm running them in test explorer in VS2022.)
The code is assuming Stream.Read always returns the requested number of bytes unless it hits EOF, but that's not guaranteed; the Stream.Read contract only guarantees at least 1 byte will be returned until EOF even if more are requested.
Fixes https://github.com/SixLabors/ImageSharp/issues/1704
https://github.com/dotnet/runtime/issues/55866
=> Fix a few uses of DeflateStream.Read

src/ImageSharp/Formats/Tiff/PhotometricInterpretation/Rgb161616TiffColor{TPixel}.cs, src/ImageSharp/Formats/Tiff/PhotometricInterpretation/TiffColorDecoderFactory{TPixel}.cs, src/ImageSharp/Formats/Tiff/TiffDecoderCore.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Tiff/Issues/Issue1716.tiff
…channel data, fixes #1716
Use same byte order as IFD directory to decode pixels for 16 bit per channel data, fixes #1716.
=> Use same byte order as IFD directory to decode pixels for 16 bit per channel images

src/ImageSharp/Formats/Tiff/PhotometricInterpretation/BlackIsZero16TiffColor{TPixel}.cs, src/ImageSharp/Formats/Tiff/PhotometricInterpretation/BlackIsZero8TiffColor{TPixel}.cs, src/ImageSharp/Formats/Tiff/PhotometricInterpretation/BlackIsZeroTiffColor{TPixel}.cs, src/ImageSharp/Formats/Tiff/PhotometricInterpretation/PaletteTiffColor{TPixel}.cs, src/ImageSharp/Formats/Tiff/PhotometricInterpretation/Rgb161616TiffColor{TPixel}.cs, src/ImageSharp/Formats/Tiff/PhotometricInterpretation/Rgb16PlanarTiffColor{TPixel}.cs, src/ImageSharp/Formats/Tiff/PhotometricInterpretation/Rgb888TiffColor{TPixel}.cs, src/ImageSharp/Formats/Tiff/PhotometricInterpretation/RgbPlanarTiffColor{TPixel}.cs, src/ImageSharp/Formats/Tiff/PhotometricInterpretation/RgbTiffColor{TPixel}.cs, src/ImageSharp/Formats/Tiff/PhotometricInterpretation/TiffBasePlanarColorDecoder{TPixel}.cs, src/ImageSharp/Formats/Tiff/PhotometricInterpretation/TiffColorDecoderFactory{TPixel}.cs, src/ImageSharp/Formats/Tiff/PhotometricInterpretation/TiffColorType.cs, src/ImageSharp/Formats/Tiff/PhotometricInterpretation/WhiteIsZero16TiffColor{TPixel}.cs, src/ImageSharp/Formats/Tiff/PhotometricInterpretation/WhiteIsZero8TiffColor{TPixel}.cs, src/ImageSharp/Formats/Tiff/PhotometricInterpretation/WhiteIsZeroTiffColor{TPixel}.cs, src/ImageSharp/Formats/Tiff/TiffDecoderCore.cs, src/ImageSharp/Formats/Tiff/TiffDecoderOptionsParser.cs, src/ImageSharp/Formats/Tiff/Utils/TiffUtils.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Tiff/flower-minisblack-16_lsb.tiff, tests/Images/Input/Tiff/flower-miniswhite-16.tiff, tests/Images/Input/Tiff/flower-miniswhite-16_lsb.tiff, tests/Images/Input/Tiff/flower-rgb-contig-16_lsb.tiff, tests/Images/Input/Tiff/flower-rgb-planar-16_lsb.tiff
This **PR** changes the tiff decoder, so it will respect the byte order for 16 bit gray tiff images and 16 bit rgb planar images.
=> Respect byte order with 16 bit tiff images

src/ImageSharp/Processing/Processors/Dithering/ErrorDither.cs, src/ImageSharp/Processing/Processors/Dithering/OrderedDither.cs, src/ImageSharp/Processing/Processors/Quantization/OctreeQuantizer.cs, src/ImageSharp/Processing/Processors/Quantization/PaletteQuantizer.cs, src/ImageSharp/Processing/Processors/Quantization/WebSafePaletteQuantizer.cs, src/ImageSharp/Processing/Processors/Quantization/WernerPaletteQuantizer.cs, src/ImageSharp/Processing/Processors/Quantization/WuQuantizer.cs, tests/ImageSharp.Tests/Processing/Processors/Dithering/DitherTests.cs, tests/ImageSharp.Tests/Processing/Processors/Quantization/QuantizerTests.cs
While investigating #1583 I realized that the static default options in all the quantizer instances could be overwritten which we should not allow. 
I've also ensured we throw a better exception should someone use the default current struct instances to dither.
=> Do not use static options for default quantizer constructors.

src/ImageSharp/Formats/Tiff/PhotometricInterpretation/BlackIsZero16TiffColor{TPixel}.cs, src/ImageSharp/Formats/Tiff/PhotometricInterpretation/BlackIsZero8TiffColor{TPixel}.cs, src/ImageSharp/Formats/Tiff/PhotometricInterpretation/Rgb161616TiffColor{TPixel}.cs, src/ImageSharp/Formats/Tiff/PhotometricInterpretation/Rgb888TiffColor{TPixel}.cs, src/ImageSharp/Formats/Tiff/PhotometricInterpretation/TiffColorDecoderFactory{TPixel}.cs, src/ImageSharp/Formats/Tiff/TiffDecoderCore.cs, tests/ImageSharp.Tests/Formats/Tiff/PhotometricInterpretation/BlackIsZeroTiffColorTests.cs, tests/ImageSharp.Tests/Formats/Tiff/PhotometricInterpretation/RgbTiffColorTests.cs
As the title says: Use bulk pixel conversion for some tiff color decoders
This should be a bit faster the converting pixel by pixel.
=> Use bulk pixel conversion for some tiff color decoders

src/ImageSharp/Formats/Tiff/Compression/Decompressors/ModifiedHuffmanTiffCompression.cs, src/ImageSharp/Formats/Tiff/Compression/Decompressors/T4BitReader.cs, src/ImageSharp/Formats/Tiff/Compression/Decompressors/T4TiffCompression.cs, src/ImageSharp/Formats/Tiff/Compression/TiffDecompressorsFactory.cs, src/ImageSharp/Formats/Tiff/README.md, src/ImageSharp/Formats/Tiff/TiffDecoderCore.cs, src/ImageSharp/Formats/Tiff/TiffDecoderOptionsParser.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffDecoderTests.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffEncoderTests.cs, tests/ImageSharp.Tests/Memory/Allocators/ArrayPoolMemoryAllocatorTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Tiff/7324fcaff3aad96f27899da51c1bb5d9.tiff, tests/Images/Input/Tiff/Calliphora_ccitt_fax3.tiff, tests/Images/Input/Tiff/b0350_fillorder2.tiff, tests/Images/Input/Tiff/basi3p02_fax3_lowerOrderBitsFirst.tiff, tests/Images/Input/Tiff/basi3p02_huffman_rle_lowerOrderBitsFirst.tiff, tests/Images/Input/Tiff/f8179f8f5e566349cf3583a1ff3ea95c.tiff, tests/Images/Input/Tiff/g3test.tiff
This **PR** adds support for decoding 1bit tiff's encoded with LeastSignificantBitFirst: pixels are arranged within a byte such that pixels with lower column values are stored in the lower-order bits of the byte.
Also reduce test images size for some images to reduce memory usage and time it takes to execute the tiff tests.
=> Add support for decoding tiff's encoded with LeastSignificantBitFirst

.github/workflows/build-and-test.yml, Directory.Build.props, ci-build.ps1, src/ImageSharp/ImageSharp.csproj, src/ImageSharp/Processing/Processors/Normalization/AdaptiveHistogramEqualizationSlidingWindowProcessor{TPixel}.cs, tests/ImageSharp.Benchmarks/ImageSharp.Benchmarks.csproj, tests/ImageSharp.Tests.ProfilingSandbox/ImageSharp.Tests.ProfilingSandbox.csproj, tests/ImageSharp.Tests/ImageSharp.Tests.csproj
<strike>Just use the environment compiler to build things. When consumers build their applications they're already consuming a prebuilt binary. We only need to test with individual frameworks.</strike>
Added .NET 6 Preview builds to the matrix and fixed up the solution to handle that scenario. Also fixed the langversion to C#9
This allows us to use features like `nint` and also build/test against .NET 6 previews which we sorely need to do.
=> Enable .NET 6 Preview Builds

src/ImageSharp/Formats/Tiff/Compression/Decompressors/CcittReferenceScanline.cs, src/ImageSharp/Formats/Tiff/Compression/Decompressors/CcittTwoDimensionalCode.cs, src/ImageSharp/Formats/Tiff/Compression/Decompressors/CcittTwoDimensionalCodeType.cs, src/ImageSharp/Formats/Tiff/Compression/Decompressors/DeflateTiffCompression.cs, src/ImageSharp/Formats/Tiff/Compression/Decompressors/LzwTiffCompression.cs, src/ImageSharp/Formats/Tiff/Compression/Decompressors/ModifiedHuffmanBitReader.cs, src/ImageSharp/Formats/Tiff/Compression/Decompressors/ModifiedHuffmanTiffCompression.cs, src/ImageSharp/Formats/Tiff/Compression/Decompressors/NoneTiffCompression.cs, src/ImageSharp/Formats/Tiff/Compression/Decompressors/PackBitsTiffCompression.cs, src/ImageSharp/Formats/Tiff/Compression/Decompressors/T4BitReader.cs, src/ImageSharp/Formats/Tiff/Compression/Decompressors/T4TiffCompression.cs, src/ImageSharp/Formats/Tiff/Compression/Decompressors/T6BitReader.cs, src/ImageSharp/Formats/Tiff/Compression/Decompressors/T6TiffCompression.cs, src/ImageSharp/Formats/Tiff/Compression/TiffBaseDecompressor.cs, src/ImageSharp/Formats/Tiff/Compression/TiffDecoderCompressionType.cs, src/ImageSharp/Formats/Tiff/Compression/TiffDecompressorsFactory.cs, src/ImageSharp/Formats/Tiff/README.md, src/ImageSharp/Formats/Tiff/TiffDecoderCore.cs, src/ImageSharp/Formats/Tiff/TiffDecoderOptionsParser.cs, tests/ImageSharp.Tests/Formats/Tiff/Compression/DeflateTiffCompressionTests.cs, tests/ImageSharp.Tests/Formats/Tiff/Compression/LzwTiffCompressionTests.cs, tests/ImageSharp.Tests/Formats/Tiff/Compression/NoneTiffCompressionTests.cs, tests/ImageSharp.Tests/Formats/Tiff/Compression/PackBitsTiffCompressionTests.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Tiff/Calliphora_ccitt_fax4.tiff, tests/Images/Input/Tiff/basi3p02_fax4.tiff, tests/Images/Input/Tiff/basi3p02_fax4_lowerOrderBitsFirst.tiff, tests/Images/Input/Tiff/basi3p02_fax4_minisblack.tiff
This **PR** adds support for decoding tiff image with ccitt T.6 fax compression (some call the compression fax4).
For the specification see pdf `T-REC-T.6-198811` in the Tiff folder.
=> Add support for decoding tiff's with T.6 fax compression

src/ImageSharp/Memory/Allocators/Internals/ManagedBufferBase.cs, tests/ImageSharp.Tests/Memory/Allocators/ArrayPoolMemoryAllocatorTests.cs, tests/ImageSharp.Tests/Memory/Allocators/SimpleGcMemoryAllocatorTests.cs
Fixes #1755.
Although `ArrayPoolMemoryAllocator` is about to be dumped with #1730 we'll keep `SimpleGcMemoryAllocator` so filing a separate fix.
=> Fix ManagedBufferBase pinning behavior

tests/ImageSharp.Tests/Image/ImageFrameTests.cs, tests/ImageSharp.Tests/Image/ImageTests.cs, tests/ImageSharp.Tests/TestUtilities/ImageProviders/TestImageProvider.cs, tests/ImageSharp.Tests/TestUtilities/TestImageExtensions.cs
I realized that the main reason behind the 32 bit test OOM-s is that every `TestImageProvider` creates a new `ArrayPoolMemoryAllocator` which practically disables pooling for the entire test run. Except for a few cases using `LimitBufferCapacity` which the PR addresses, we should be safe to use the shared allocator.
#1730 is also contains this fix, but it makes sense to get rid of the OOM pain on master now.
=> Use shared ArrayPoolMemoryAllocator in tests to avoid OOM

tests/ImageSharp.Tests/TestUtilities/ReferenceCodecs/MagickReferenceDecoder.cs
This is causing intermittent failures on 32 bit. If `destinationGroup` contains of 2 `Memory<TPixel>` blocks, `rgbaBytes` is double of `destBuffer`, which is an invalid call to `PixelOperations.FromRgba32(Bytes)`, which wants to convert `source.Length` amount of pixels.
=> Fix a bug in MagickReferenceDecoder

src/ImageSharp/Formats/Webp/BitWriter/BitWriterBase.cs, src/ImageSharp/Formats/Webp/BitWriter/Vp8BitWriter.cs, src/ImageSharp/Formats/Webp/BitWriter/Vp8LBitWriter.cs, src/ImageSharp/Formats/Webp/Lossless/Vp8LEncoder.cs, src/ImageSharp/Formats/Webp/Lossy/Vp8Encoder.cs, src/ImageSharp/Formats/Webp/WebpEncoderCore.cs, tests/ImageSharp.Tests/Formats/WebP/WebpMetaDataTests.cs
This PR fixes #1796: adds a padding byte to the exif profile, if needed.
~There still seems to be an issue with lossless.~ The issue was due to a mismatch of the alpha flag in VP8X and VP8L chunk.
=> Write exif profile with padding if needed

src/ImageSharp/Formats/Webp/Lossless/LosslessUtils.cs, src/ImageSharp/Formats/Webp/Lossless/PredictorEncoder.cs, tests/ImageSharp.Tests/Formats/WebP/LosslessUtilsTests.cs
This adds a SSE2 version of the method Select(), which is used during lossless encoding. Its a bit faster, but its very specific to the image which is encoded, since this only gets used in `Predictor11`
TODO:
Before:
After with sse2:
=> Add sse2 version of select

src/ImageSharp/Image.Decode.cs
The buffer allocation/disposal has shown up as a small but visible bottleneck in PNG decoder profiling results. Headers  are always very small, we should `stackalloc` the buffer for them.
=> stackalloc header buffer in InternalDetectFormat

src/ImageSharp/Formats/Webp/IWebpEncoderOptions.cs, src/ImageSharp/Formats/Webp/WebpEncoder.cs, tests/ImageSharp.Benchmarks/Codecs/DecodeWebp.cs, tests/ImageSharp.Benchmarks/Codecs/EncodeWebp.cs
This PR makes sure magick.net and imagesharp use the same configuration for encoding benchmarks, so we comparing the same thing.
=> Make sure magick.net and imagesharp use the same configuration for webp encoding

src/ImageSharp/Formats/Png/PngDecoderCore.cs, src/ImageSharp/Formats/Webp/WebpDecoderCore.cs, src/ImageSharp/IO/ChunkedMemoryStream.cs, src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeKernelMap.cs
This PR collapses all AsSpan().Slice(..) calls into AsSpan(..) (excluding test code), as it is less code and potentially a bit faster.
=> Collapse AsSpan().Slice(..) calls into AsSpan(..)

src/ImageSharp/Formats/Webp/Lossy/LossyUtils.cs, tests/ImageSharp.Tests/Formats/WebP/LossyUtilsTests.cs
This adds a SSE41 version of the Hadamard transform which is used during lossy webp encoding.
Relates to #1786
Profiling results:
Before:
After:
**note the number of calls is halfed, because the sse version does two transformas at once**
=> SSE41 version of Hadamard transform

src/ImageSharp/Formats/Webp/Lossy/QuantEnc.cs, src/ImageSharp/Formats/Webp/Lossy/Vp8Encoder.cs, src/ImageSharp/Formats/Webp/Lossy/Vp8Matrix.cs, src/ImageSharp/Formats/Webp/Lossy/Vp8SegmentInfo.cs, tests/ImageSharp.Tests/Formats/WebP/QuantEncTests.cs
This PR add SSE41 version of Quantize block, which is used during lossy encoding.
Before:
After:
=> Add SSE41 version of Quantize block

src/ImageSharp/Formats/Webp/Lossy/LossyUtils.cs, src/ImageSharp/Formats/Webp/Lossy/Vp8EncIterator.cs, src/ImageSharp/Formats/Webp/Lossy/WebpLossyDecoder.cs, src/ImageSharp/Formats/Webp/Lossy/YuvConversion.cs, tests/ImageSharp.Tests/Formats/WebP/LossyUtilsTests.cs
This PR add SSE2 version of Mean16x4 which is used during lossy encoding with mode 1.
Before:
After:
The overall encoding time was 9002 ms. 
Its an improvement, but only a small one. I guess every bit counts.
=> Add SSE2 version of Mean16x4

src/ImageSharp/Formats/Webp/Lossy/LossyUtils.cs, src/ImageSharp/Formats/Webp/Lossy/QuantEnc.cs, src/ImageSharp/Formats/Webp/Lossy/Vp8Encoding.cs, src/ImageSharp/Formats/Webp/Lossy/Vp8Histogram.cs, src/ImageSharp/Formats/Webp/Lossy/Vp8ModeScore.cs, tests/ImageSharp.Tests/Formats/WebP/LossyUtilsTests.cs
This adds a SSE2 version of the method `Vp8Sse4X4`, which is used during lossy encoding of webp images.
P.S. im not sure again why the call count is different, it was the same image
=> Add SSE2 version of Vp8Sse4X4

ImageSharp.sln, codecov.yml
- Update coverlet.collector to 3.1.0
- Use integer precision  for coverage calculation.
- Ignore patch coverage for checks.
- Use shared codecov.yml config from submodule
=> Update codcov and config

src/ImageSharp/Formats/Jpeg/JpegEncoderCore.cs, src/ImageSharp/Formats/Tiff/Compression/Compressors/TiffLzwEncoder.cs, src/ImageSharp/Formats/Tiff/Compression/Decompressors/T6TiffCompression.cs, src/ImageSharp/Formats/Webp/Lossless/CostModel.cs, src/ImageSharp/Formats/Webp/Lossless/HistogramEncoder.cs, src/ImageSharp/Formats/Webp/Lossless/HuffmanUtils.cs, src/ImageSharp/Formats/Webp/Lossless/Vp8LHistogram.cs, src/ImageSharp/Formats/Webp/Lossy/Vp8EncIterator.cs, src/ImageSharp/Formats/Webp/Lossy/Vp8Encoder.cs
1st commit:
Revert a `stackalloc` de-optimization from #1734 (it was probably forgotten in #1750) and add a comment 
2nd commit:
Replace all `Span<T>.Fill(default)` calls with `Span<T>.Clear()` , as `Span<T>.Clear()` is more optimized than `Span<T>.Fill(default)`
=> Some minor optimizations

src/ImageSharp/Formats/Webp/Lossless/ColorSpaceTransformUtils.cs, src/ImageSharp/Formats/Webp/Lossless/LosslessUtils.cs, src/ImageSharp/Formats/Webp/Lossless/PredictorEncoder.cs, tests/ImageSharp.Tests/Formats/WebP/ColorSpaceTransformUtilsTests.cs, tests/ImageSharp.Tests/Formats/WebP/PredictorEncoderTests.cs
This PR adds a AVX version of CollectColorBlueTransforms and CollectColorRedTransforms, which is used during encoding of lossless webp images.
Related to: #1786
TODO:
~- There are still 2 failing tests.~ Fixed by @JimBobSquarePants with 55f04f6
Profiling results with test image: `Images\Input\Webp\earth_lossless.webp` :
=> Add AVX version of CollectColorBlueTransforms and CollectColorRedTransforms

src/ImageSharp/Formats/Webp/Lossless/LosslessUtils.cs, tests/ImageSharp.Tests/Formats/WebP/LosslessUtilsTests.cs
This PR add AVX2 versions of `TransformColor` and `TransformColorInverse` which are used during webp encoding and decoding.
Relates to #1786
Profiling results:
=> Add AVX version of TransformColor and TransformColorInverse

src/ImageSharp/Processing/Processors/Convolution/Convolution2PassProcessor{TPixel}.cs, tests/ImageSharp.Tests/Processing/Processors/Convolution/Basic1ParameterConvolutionTests.cs, tests/Images/External/ReferenceOutput/Convolution/BoxBlurTest/InBox_Rgba32_blur_3.png, tests/Images/External/ReferenceOutput/Convolution/BoxBlurTest/InBox_Rgba32_blur_5.png, tests/Images/External/ReferenceOutput/Convolution/BoxBlurTest/OnFullImage_Rgba32_blur_3.png, tests/Images/External/ReferenceOutput/Convolution/BoxBlurTest/OnFullImage_Rgba32_blur_5.png, tests/Images/External/ReferenceOutput/Convolution/GaussianBlurTest/InBox_Rgba32_blur_3.png, tests/Images/External/ReferenceOutput/Convolution/GaussianBlurTest/InBox_Rgba32_blur_5.png, tests/Images/External/ReferenceOutput/Convolution/GaussianBlurTest/OnFullImage_Rgba32_blur_3.png, tests/Images/External/ReferenceOutput/Convolution/GaussianBlurTest/OnFullImage_Rgba32_blur_5.png, tests/Images/External/ReferenceOutput/Convolution/GaussianSharpenTest/InBox_Rgba32_blur_3.png, tests/Images/External/ReferenceOutput/Convolution/GaussianSharpenTest/InBox_Rgba32_blur_5.png, tests/Images/External/ReferenceOutput/Convolution/GaussianSharpenTest/OnFullImage_Rgba32_blur_3.png, tests/Images/External/ReferenceOutput/Convolution/GaussianSharpenTest/OnFullImage_Rgba32_blur_5.png
Firstly, all credit goes to @JimBobSquarePants for [identifying the fix](https://twitter.com/James_M_South/status/1460931447766749193).
Blurring an image that has a transparent background can lead to strange results depending on the colour.
For example, take this code:
```csharp
using var image = new Image<Rgba32>(400, 400);
image.Mutate(x => x.Fill(Color.ParseHex("48f25b"), new Rectangle(100, 100, 200, 200)).GaussianBlur(20));
```
Master generates this:
This PR generates:
I do want to add tests for it, just working out how to do it like how you have your Bokeh blur tests.
=> Fix gaussian blurring changing the blur colour when transperancy is used

src/ImageSharp/Processing/Extensions/Normalization/HistogramEqualizationExtensions.cs, src/ImageSharp/Processing/Processors/Normalization/HistogramEqualizationOptions.cs, tests/ImageSharp.Tests/Formats/WebP/LossyUtilsTests.cs
We should not expose an arbitrary mutable variable like this. The common practice in the library is to use constructor to new-up instances of similar `XyzOptions` objects.
=> Remove HistogramEqualizationOptions.Default

src/ImageSharp/Processing/Processors/Quantization/EuclideanPixelMap{TPixel}.cs
I wonder if it was result of IDE0044 suggestion? It [may report false recommendations](https://stackoverflow.com/questions/58452638/ide0044-make-field-readonly-depending-on-target-framework) for us.
=> Make ColorDistanceCache non-readonly

src/ImageSharp/Image.FromFile.cs, src/ImageSharp/Image.FromStream.cs
I noticed that a few asynchronous overloaded methods on the Image class were needlessly omitting a CancellationToken parameter when the underlying code supported cancellation.  This PR adds the cancel token parameter, but keeps them optional for backwards compatibility.
=> Added missing CancellationToken parameters to Image

src/ImageSharp/Formats/Webp/Lossy/QuantEnc.cs, src/ImageSharp/Formats/Webp/Lossy/Vp8Encoding.cs, tests/ImageSharp.Tests/Formats/WebP/Vp8EncodingTests.cs
This PR adds a SSE2 version of `FTransform` and `FTransform2` (two transforms at once), which are used for webp lossy encoding.
Profiling results:
Test image was Calliphora.png
=> Add SSE2 version of FTransform

src/ImageSharp/Formats/Webp/Lossy/LossyUtils.cs, src/ImageSharp/Formats/Webp/Lossy/Vp8EncIterator.cs, tests/ImageSharp.Tests/Formats/WebP/LossyUtilsTests.cs
This PR adds a AVX2 version of Vp8_Sse4X4, which is used during lossy webp encoding.
Profiler results:
Test image was Calliphora.png
=> Add AVX2 version of Vp8_Sse4X4

src/ImageSharp/Color/Color.cs, tests/ImageSharp.Tests/Color/ColorTests.CastTo.cs
Our new high precision `Color` boxing was missing an important scenario when converting via `ToPixel()` - Converting from a high precision input to a different type. This was actually breaking the `LinearGradientBrush` in ImageSharp.Drawing.
CC @Turnerj
=> Fix Color conversion for differing types

src/ImageSharp/Formats/Webp/Lossless/Vp8LEncoder.cs, tests/ImageSharp.Tests/Formats/WebP/WebpEncoderTests.cs
This PR fixes a bug in `AnalyzeEntropy` which did not allocate a clean buffer from the memory allocator, resulting in possible unpredictable results.
Closes #1872
=> Allocate clean buffer in AnalyzeEntropy

src/ImageSharp/Formats/Jpeg/Components/Encoder/HuffmanScanEncoder.cs
I've made quite a mistake during jpeg encoder optimization for last bytes flushing to the stream:
```csharp
int valuableBytesCount = (int)Numerics.DivideCeil((uint)this.bitCount, 8);
uint packedBytes = this.accumulatedBits | (uint.MaxValue >> this.bitCount);
this.emitBuffer[--this.emitWriteIndex] = packedBytes;
int endIndex = (this.emitWriteIndex * 4) - 4 + valuableBytesCount;
this.FlushToStream(endIndex);
```
`uint` buffer size is 4 for simplicity. Let's say we have 3 bits to pad with 1's for full byte and write to the stream:
```
bufferSize = 4
emitWriteIndex = 4
bitCount = 3
accumulatedBits = 101|0_0000_...
int valuableBytesCount = 1
uint packedBytes = 101|1_1111_...
--emitWriteIndex = 3
int endIndex = 3 * 4 - 4 + 1 = 12 - 4 + 1 = 9
// bytes indices written to the stream:
15 14 13 12 …
```
=> Fixed jpeg encoder last bytes flushing bug

src/ImageSharp/Formats/Png/PngDecoderCore.cs, tests/ImageSharp.Tests/Formats/Png/PngDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Png/xcsn0g01.png
This PR changes the PNG decoder to verify that the CRC of IDAT chunk is correct.
=> PNG: Verify CRC of IDAT chunk is correct

src/ImageSharp/Common/Helpers/Numerics.cs, src/ImageSharp/Formats/Jpeg/Components/Decoder/JpegComponent.cs, src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs, src/ImageSharp/Formats/Jpeg/JpegThrowHelper.cs, tests/ImageSharp.Tests/Common/NumericsTests.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.Images.cs
Closes #1894. Moved mentioned image from decoder tests to 'throws exception' tests.
=> Jpeg sampling factor validation #1894

src/ImageSharp/ImageFrame{TPixel}.cs
We need to expose this property to allow migrating the ImageSharp.Drawing brush API to the latest ImageSharp v2 versions without runtime error.
=> Expose ImageFrame<TPixel>.PixelBuffer

src/ImageSharp/Formats/ImageExtensions.Save.cs, src/ImageSharp/Formats/ImageExtensions.Save.tt
Very minor code documentation fixes.
=> Remove return value documentation for void return types.

src/ImageSharp/Formats/Jpeg/Components/FastFloatingPointDCT.cs, tests/ImageSharp.Tests/Formats/Jpg/DCTTests.cs
Fixes #1917.
Fix is simple: I've removed `Debug` check for `Vector4.IsHardwareAccelerated` as `Vector4` code can be compiled to a scalar implementation. That check was deprecated long ago - when I've merged de-zigzag and single transpose call so now every IDCT implementation must do a single transpose call.
FDCT method does have a scalar implementation right now because current encoding pipeline does not have a merged zig-zag/transpose code. I'm yet to implement it in #1778 (coding those sse/avx zigzag tables is a horror). Because of two transpose calls scalar code can do DCT stuff a little trickier than simd without transpose calls at all but with a tranposed block input we must transpose it second time durint IDCT call.
=> Fixed Jpeg IDCT missing scalar implementation

src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs, src/ImageSharp/Formats/Jpeg/JpegThrowHelper.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.Images.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Jpg/issues/issue-1900-malformed-unsupported-255-components.jpg
Fixes #1900.
I've actually found another image from fuzz issue which has 131 components and was throwing `InvalidImageContentException`. Moved it to the `NotSupportedException` test suite.
=> Jpeg ArgumentException fix

src/ImageSharp/Formats/Jpeg/Components/Decoder/HuffmanScanDecoder.cs, src/ImageSharp/Formats/Jpeg/Components/Decoder/HuffmanTable.cs, src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs
This PR removes redundant `Configure()` calls for `HuffmanTable` and removes stack pressure from `stackalloc` calls.
=> Jpeg HuffmanTable improvements

src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs
Fix for Jpeg Decoding Metadata for unknown APP13 profiles. Without this fix the parser will continue parsing any non-Photoshop profile looking for markers and under the right circumstances cause the SOS marker to get missed. Sorry not able to provide the image where this issue was originally encountered for a test case.
=> Fix for Jpeg Metadata Decoding with unknown APP13 profile

.github/workflows/build-and-test.yml, .github/workflows/code-coverage.yml, ImageSharp.sln
Speed up our CI times by moving code coverage checks to a scheduled workflow. Tue,Thur at 2AM
Note: I've done the bare minimum required to enable this. I didn't want to edit `*.ps1` files.
https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
=> Use a scheduled job for codecov

src/ImageSharp/Formats/PixelTypeInfo.cs, src/ImageSharp/Metadata/ImageMetadata.cs
Case a user implements `IImageInfo` and supports user-specific image formats:
`IImageInfo` has `PixelTypeInfo` and `ImageMetadata` properties. But
* `ImageMetadata` cannot be instanced because it has an internal constructor.
* `PixelTypeInfo` cannot be instanced because it has an internal constructor.
So change the constructor of `PixelTypeInfo` and `ImageMetadata` from internal to public
Related discussion: https://github.com/SixLabors/ImageSharp/discussions/1914
=> Change the constructor of PixelTypeInfo and ImageMetadata from internal to public so that a user can implement IImageInfo

src/ImageSharp/Formats/Jpeg/Components/Decoder/JFifMarker.cs, src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.Metadata.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Jpg/issues/issue-1932-app0-resolution.jpg
Immediately following the JFIF APP0 marker segment may be a JFIF extension APP0 marker segment. This segment may only be present for JFIF versions 1.02 and above. This PR ensures that we do not attempt to decode secondary JFIF markers in an image. Fix #1932
=> Only attempt to decode the first JFIF marker instance

src/ImageSharp/Configuration.cs, src/ImageSharp/Formats/ImageFormatManager.cs
Updates around `ImageFormatDetector`. Fixes #1850 
Minimum changes. 
- Removes the public setter from the `Configuration` type
- Minor style cleanup.
This still leaves it possible to clear the collection of detectors, therefore limiting the collection of available image formats.
=> ImageFormatDetector Configuration Cleanup

src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeWorker.cs, tests/ImageSharp.Tests/Processing/Processors/Transforms/ResizeTests.cs, tests/Images/External/ReferenceOutput/ResizeTests/Issue1625_LimitedAllocator.png
=> Ensure ResizeProcessor working buffer is contiguous

src/ImageSharp/Memory/Buffer2DRegion{T}.cs, src/ImageSharp/Processing/Processors/CloningImageProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Transforms/Linear/AffineTransformProcessor.cs, src/ImageSharp/Processing/Processors/Transforms/Linear/AffineTransformProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Transforms/Linear/LinearTransformUtility.cs, src/ImageSharp/Processing/Processors/Transforms/Linear/ProjectiveTransformProcessor.cs, src/ImageSharp/Processing/Processors/Transforms/Linear/ProjectiveTransformProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeWorker.cs, tests/ImageSharp.Tests/Memory/BufferAreaTests.cs, tests/ImageSharp.Tests/Processing/Processors/Transforms/AffineTransformTests.cs, tests/ImageSharp.Tests/Processing/Transforms/ProjectiveTransformTests.cs, tests/ImageSharp.Tests/Quantization/PixelSamplingStrategyTests.cs, tests/Images/External/ReferenceOutput/AffineTransformTests/Identity_Rgba32_TestPattern100x100.png, tests/Images/External/ReferenceOutput/AffineTransformTests/Transform_FromSourceRectangle1_Rgba32_TestPattern96x48.png, tests/Images/External/ReferenceOutput/AffineTransformTests/Transform_FromSourceRectangle2_Rgba32_TestPattern96x48.png, tests/Images/External/ReferenceOutput/AffineTransformTests/Transform_With_Custom_Dimensions_Rgba32_TestPattern100x100_0.0001.png, tests/Images/External/ReferenceOutput/AffineTransformTests/Transform_With_Custom_Dimensions_Rgba32_TestPattern100x100_0.png, tests/Images/External/ReferenceOutput/AffineTransformTests/Transform_With_Custom_Dimensions_Rgba32_TestPattern100x100_57.png, tests/Images/External/ReferenceOutput/ProjectiveTransformTests/Identity_Rgba32_TestPattern100x100.png, tests/Images/External/ReferenceOutput/ProjectiveTransformTests/Transform_With_Custom_Dimensions_Rgba32_TestPattern100x100_0.0001.png, tests/Images/External/ReferenceOutput/ProjectiveTransformTests/Transform_With_Custom_Dimensions_Rgba32_TestPattern100x100_0.png, tests/Images/External/ReferenceOutput/ProjectiveTransformTests/Transform_With_Custom_Dimensions_Rgba32_TestPattern100x100_57.png
Fixes #1911 
- Fixes a situation where given source and destination rectangles can cause an `ImageProcessingException` during transforms when an identity matrix is passed.
- Renames ` Buffer2DRegion{T}.GetRowSpan(y)` adding the `Dangerous` prefix to match other implementations. CC @antonfirsov 
- Removes the exception wrapping from the base cloning processor #1827
=> Correctly handle identity transforms with varying dimensions

tests/ImageSharp.Tests/Memory/Allocators/UniformUnmanagedMemoryPoolTests.cs
Possible cause is that this test can race for particular memory areas with potential parallel tests, this change should fix that.
Also attempting to enable it on Mac.
=> Move RentReturnRelease_SubsequentRentReturnsDifferentHandles out of process

src/ImageSharp/Formats/Webp/IWebpEncoderOptions.cs, src/ImageSharp/Formats/Webp/WebpEncoderCore.cs, tests/ImageSharp.Tests/Formats/WebP/WebpEncoderTests.cs
To match `libwebp` behavior, the Webp encoder now defaults to lossy, if nothing else is specified.
=> Webp encoder now defaults to lossy, if nothing else is specified

src/ImageSharp/Formats/Jpeg/Components/Block8x8F.cs, src/ImageSharp/Formats/Jpeg/Components/FastFloatingPointDCT.Intrinsic.cs, src/ImageSharp/Formats/Jpeg/Components/FastFloatingPointDCT.cs, src/ImageSharp/Formats/Jpeg/Components/ZigZag.Intrinsic.cs, tests/ImageSharp.Tests/Formats/Jpg/Block8x8FTests.cs, tests/ImageSharp.Tests/Formats/Jpg/DCTTests.cs
Closes #1778 for the encoder part, decoder part was implemented long time ago so it can be closed after this PR.
Basically, this removes second matrix transpose call from FDCT-Quantize-Huffman pipeline in the jpeg encoder. Performance gain is not **that** big but it's still nice:
Current master
```
// Encoding q=98 | color=YCbCrRatio444
// Elapsed: 11934ms across 1000 iterations
// Average: 11,934ms
```
PR, roughly **4% faster**
```
// Encoding q=98 | color=YCbCrRatio444
// Elapsed: 11457ms across 1000 iterations
// Average: 11,457ms
```
Tests were done using [Calliphora.jpg](https://github.com/SixLabors/ImageSharp/blob/master/tests/Images/Input/Jpg/baseline/Calliphora.jpg) from test suite. Quality 98, no chroma subsampling.
This optimization has 'constant' delta independent of output …
=> Jpeg encoder optimization via removing second transpose call from FDCT

tests/ImageSharp.Tests/Memory/Allocators/UniformUnmanagedMemoryPoolTests.cs
Reverts commit introducing CI failures.
=> Disable RentReturnRelease_SubsequentRentReturnsDifferentHandles on Mac again

src/ImageSharp/Formats/Webp/AlphaEncoder.cs, src/ImageSharp/Formats/Webp/BitWriter/BitWriterBase.cs, src/ImageSharp/Formats/Webp/BitWriter/Vp8BitWriter.cs, src/ImageSharp/Formats/Webp/IWebpEncoderOptions.cs, src/ImageSharp/Formats/Webp/Lossless/Vp8LEncoder.cs, src/ImageSharp/Formats/Webp/Lossy/Vp8Encoder.cs, src/ImageSharp/Formats/Webp/Lossy/YuvConversion.cs, src/ImageSharp/Formats/Webp/WebpEncoder.cs, src/ImageSharp/Formats/Webp/WebpEncoderCore.cs, tests/ImageSharp.Tests/Formats/WebP/WebpEncoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Png/transparency.png
This PR adds support for encoding lossy webp images with alpha channels.
The alpha data can be either compressed (with webp lossless compression) or uncompressed.
Related to #1802
=> Add support for encoding lossy webp images with alpha channels

tests/ImageSharp.Benchmarks/Codecs/Jpeg/DecodeJpegParseStreamOnly.cs, tests/ImageSharp.Tests/Formats/Jpg/SpectralJpegTests.cs, tests/ImageSharp.Tests/Formats/Jpg/SpectralToPixelConversionTests.cs
Some tests didn't dispose `JpegDecoderCore` instance thus leading to memory leaks. Well, not actual leaks but, you know, it's bad.
=> Fixed IDisposable leaks in jpeg decoder test suite.

.github/workflows/build-and-test.yml, src/ImageSharp/ImageSharp.csproj
Add tiff and webp to the PackageTags of the project in preparation for release of 2.0
=> Add tiff and webp to the PackageTags

src/ImageSharp/Formats/Jpeg/Components/Decoder/HuffmanScanDecoder.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.Images.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/External/ReferenceOutput/JpegDecoderTests/DecodeBaselineJpeg_grayscale_sampling22.png, tests/Images/Input/Jpg/baseline/grayscale_sampling22.jpg
Fixes https://github.com/SixLabors/ImageSharp/issues/1978. ~~Issue author didn't respond (yet) whether we can use attached image in the test suite so~~ I've created a test image based on one of grayscale images from the test suit:
This image after decode-encode on current master:
=> Fixed decoding grayscale jpegs with exotic sampling factors

src/ImageSharp/Formats/Gif/GifDecoderCore.cs, tests/ImageSharp.Tests/Formats/Gif/GifDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/External/ReferenceOutput/GifDecoderTests/Issue1962_Rgba32_issue1962_tiniest_gif_1st.png, tests/Images/Input/Gif/issues/issue1962_tiniest_gif_1st.gif
Allows the decoding of images without a color table. Also fixes misallocation of fully transparent image when a transparency flag does not exist. Fix #1962
=> Handle missing global color table. 

src/ImageSharp/Metadata/ImageMetadata.cs
Also improve the formatting of the ResolutionUnits documentation.
=> Fix documentation of HorizontalResolution and VerticalResolution properties

src/ImageSharp/Formats/Jpeg/Components/Decoder/HuffmanScanDecoder.cs
Fixes https://github.com/SixLabors/ImageSharp/issues/1998. Fix is fairly simple: code had second call which wasn't caught by CI. 
Also renamed a parameter and added `<param>` comment because it could be easily confused with something completely different.
=> Fixed multiple SpectralConverter.CommitConversion() calls

src/ImageSharp/Formats/Jpeg/Components/Decoder/SpectralConverter{TPixel}.cs, src/ImageSharp/Image.Decode.cs, tests/ImageSharp.Tests/Image/LargeImageIntegrationTests.cs
=> Respect PreferContiguousImageBuffers in decoders

src/ImageSharp/Formats/Png/PngScanlineProcessor.cs, src/ImageSharp/Formats/Png/PngThrowHelper.cs, tests/ImageSharp.Tests/Formats/Png/PngDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Png/missing_plte.png, tests/Images/Input/Png/missing_plte_2.png
This PR changes the PNG decoder to throw an appropriate exception, if the palette chunk is missing.
=> PNG: Throw exception, if palette chunk is missing

ImageSharp.sln, src/ImageSharp/Common/Extensions/StreamExtensions.cs, src/ImageSharp/Formats/Gif/GifDecoderCore.cs, src/ImageSharp/Formats/Gif/GifEncoderCore.cs, src/ImageSharp/Formats/Gif/LzwDecoder.cs, src/ImageSharp/Formats/Gif/Sections/GifGraphicControlExtension.cs, src/ImageSharp/Formats/Gif/Sections/GifNetscapeLoopingApplicationExtension.cs, src/ImageSharp/Formats/Gif/Sections/GifXmpApplicationExtension.cs, src/ImageSharp/Metadata/ImageMetadata.cs, tests/ImageSharp.Tests/Formats/Gif/GifDecoderTests.cs, tests/ImageSharp.Tests/Formats/WebP/WebpMetaDataTests.cs, tests/ImageSharp.Tests/Metadata/Profiles/XMP/XmpProfileTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/External/ReferenceOutput/GifDecoderTests/Issue2012BadMinCode_Rgba32_issue2012_drona1.png, tests/Images/External/ReferenceOutput/GifDecoderTests/Issue2012EmptyXmp_Rgba32_issue2012_Stronghold-Crusader-Extreme-Cover.png, tests/Images/External/ReferenceOutput/GifDecoderTests/IssueDeferredClearCode_Rgba32_bugzilla-55918.png, tests/Images/Input/Gif/issues/bugzilla-55918.gif, tests/Images/Input/Gif/issues/issue2012_Stronghold-Crusader-Extreme-Cover.gif, tests/Images/Input/Gif/issues/issue2012_drona1.gif
Fix #2012
- Fixes `GifXmpApplicationExtension` by using a more robust (_handles empty profiles_) and less allocation heavy reader.
- Provides protection against invalid memory operations in `LzwDecoder`
- Fixes cloning of `XmpProfile` when cloning `ImageMetadata`
Integrity of reencoded metadata has been tested externally using ExifTools
=> Gif decoder. Fix memory access violations.

src/ImageSharp/Formats/Png/PngDecoderCore.cs, src/ImageSharp/Formats/Png/PngThrowHelper.cs, tests/ImageSharp.Tests/Formats/Png/PngDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Png/length_gama.png
This PR handles another edge case when the gamma chunk does not contain enough data.
=> PNG: Ignore invalid gamma chunks

src/ImageSharp/Memory/Allocators/UniformUnmanagedMemoryPoolMemoryAllocator.cs, tests/ImageSharp.Tests/Memory/Allocators/UniformUnmanagedPoolMemoryAllocatorTests.cs
Workaround dotnet/runtime#65466 by using the constant fallback pool size if negative memory is reported.
Fixes #2001.
=> Workaround GC.GetMemoryInfo() ARM32 issue

src/ImageSharp/Compression/Zlib/Crc32.cs, tests/ImageSharp.Tests/Formats/Png/Crc32Tests.cs, tests/ImageSharp.Tests/TestUtilities/FeatureTesting/FeatureTestRunner.cs, tests/ImageSharp.Tests/TestUtilities/Tests/FeatureTestRunnerTests.cs
Adds a fast path in Crc32 for arm and arm64
Some benchmarks for the arm64 path:
Current (LUT):
|             Method | Count |     Mean |    Error |   StdDev |
|------------------- |------ |---------:|---------:|---------:|
| SixLaborsCalculate |  1024 | 14.54 us | 0.001 us | 0.001 us |
| SixLaborsCalculate |  2048 | 29.07 us | 0.003 us | 0.002 us |
| SixLaborsCalculate |  4096 | 58.14 us | 0.008 us | 0.008 us |
arm crc32 instructions without loop unrolling:
|             Method | Count |       Mean |   Error |  StdDev |
|------------------- |------ |-----------:|--------:|--------:|
| SixLaborsCalculate |  1024 |   833.0 ns | 7.47 ns | 6.62 ns |
| SixLaborsCalculate |  2048 | 1,557.8 ns | 0.17 ns | 0.14 ns |
| SixLaborsCalculate |  4096 | 3,044.1 ns | 0.75 ns | 0.70 ns |
This PR:
| …
=> Optimize Crc32 for arm

src/ImageSharp/Formats/Tiff/Compression/Decompressors/GrayJpegSpectralConverter.cs, src/ImageSharp/Formats/Tiff/Compression/Decompressors/JpegTiffCompression.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Tiff/JpegCompressedGray.tiff
This PR adds support for decoding gray tiff with jpeg compression.
Fixes #2030
=> Add support for decoding gray tiff with jpeg compression

src/ImageSharp/Formats/Gif/GifDecoder.cs, src/ImageSharp/Formats/Tiff/ITiffDecoderOptions.cs, src/ImageSharp/Formats/Tiff/README.md, src/ImageSharp/Formats/Tiff/TiffDecoder.cs, src/ImageSharp/Formats/Tiff/TiffDecoderCore.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Tiff/SKC1H3.tiff
As discussed in #1982, this adds the TiffDecoder option `FrameDecodingMode`, which allows to decode only the first frame.
=> Tiff Decoder option to decode only first frame

src/ImageSharp/Compression/Zlib/Adler32.cs, tests/ImageSharp.Tests/Formats/Png/Adler32Tests.cs
This PR adds a AVX2 version of adler method.
```
BenchmarkDotNet=v0.13.1, OS=Windows 10.0.19043.1526 (21H1/May2021Update)
Intel Core i7-6700K CPU 4.00GHz (Skylake), 1 CPU, 8 logical and 4 physical cores
.NET SDK=6.0.200
[Host]     : .NET 5.0.14 (5.0.1422.5710), X64 RyuJIT
DefaultJob : .NET 5.0.14 (5.0.1422.5710), X64 RyuJIT
|      Method |       Mean |   Error |  StdDev |
|------------ |-----------:|--------:|--------:|
|    AdlerSse |   160.4 ns | 1.10 ns | 0.92 ns |
|    AdlerAvx |   109.6 ns | 0.52 ns | 0.49 ns |
| AdlerScalar | 1,557.8 ns | 4.71 ns | 4.40 ns |
```
=> Add AVX2 version of adler32

src/ImageSharp/Processing/Extensions/Transforms/PadExtensions.cs, src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeProcessor.cs, src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeProcessor{TPixel}.cs, src/ImageSharp/Processing/ResizeOptions.cs, tests/ImageSharp.Tests/Processing/Processors/Transforms/PadTest.cs, tests/ImageSharp.Tests/Processing/Transforms/PadTest.cs, tests/ImageSharp.Tests/Processing/Transforms/ResizeTests.cs
Adds a new property  `ResizeOptions.PadColor` of type Color which allows choosing a background color to pad images with.
This property color is then applied via the built in `ImageFrame<TPixel>.Clear(TPixel color)` which allows background color filling in non-alpha aware pixel formats like `Rgb24`.
=> Allow pad to work for non-alpha pixel formats

src/ImageSharp/Compression/Zlib/DeflaterEngine.cs, src/ImageSharp/Processing/Processors/Quantization/WuQuantizer{TPixel}.cs
I investigated some possible code optimizations and found minor issues with unnecessary operations in:
- DeflaterEngine
- WuQuantizer
It is connected to the following [discussion](https://github.com/SixLabors/ImageSharp/discussions/2010)
A comparison with BenchmarkDotNet showed ~3% improvement for a 2560 x 1920 image 16 Bit Grayscale Image.
Also used existing test 'ImageSharp Png' for .NET 5.0:
Before (mean): 36.07ms 
Optimized (mean): 35.62 ms
=> Minor PNG Encoding Optimization for DeflaterEngine and WuQuantizer

src/ImageSharp/Formats/Jpeg/Components/Encoder/LuminanceForwardConverter{TPixel}.cs, src/ImageSharp/Formats/Jpeg/Components/Encoder/RgbForwardConverter{TPixel}.cs, src/ImageSharp/Formats/Jpeg/Components/Encoder/RgbToYCbCrConverterVectorized.cs, tests/ImageSharp.Benchmarks/Codecs/Jpeg/EncodeJpeg.cs
This PR fixed #1763
Implemented AVX versions of Luminance and RGB conversions in JPEG Encoding, as described in the issue.
Added Benchmarks for these cases.
Results with and without AVX:
|                                  Method | Quality |     Mean |    Error |   StdDev |
|---------------------------------------- |-------- |---------:|---------:|---------:|
|     ImageSharp (greyscale) Jpeg 4:0:0 |      75 | 12.90 ms | 0.074 ms | 0.069 ms |
| ImageSharp (greyscale) Jpeg 4:0:0 AVX |      75 | 11.96 ms | 0.076 ms | 0.072 ms |
|                   ImageSharp Jpeg rgb |      75 | 28.45 ms | 0.130 ms | 0.115 ms |
|               ImageSharp Jpeg rgb AVX |      75 | 26.22 ms | 0.051 ms | 0.046 ms |
|     ImageSharp (greyscale) Jpeg 4:0:0 |      90 | 16.23 ms | 0.273 ms | 0.255 ms |
| ImageSharp …
=> AVX conversions for Luminance and Rgb

src/ImageSharp/ImageFrame{TPixel}.cs, src/ImageSharp/Metadata/Profiles/Exif/Tags/ExifTag.String.cs, src/ImageSharp/PixelFormats/PixelImplementations/PixelOperations/RgbaVector.PixelOperations.cs, src/ImageSharp/PixelFormats/PixelOperations{TPixel}.cs, tests/ImageSharp.Tests.ruleset, tests/ImageSharp.Tests/PixelFormats/PixelOperations/PixelOperationsTests.cs, tests/ImageSharp.Tests/PixelFormats/RgbaVectorTests.cs, tests/ImageSharp.Tests/TestUtilities/TestPixel.cs
=> Ensure PixelOperations.To(TPixel) uses scaling.

src/ImageSharp/Formats/Tiff/Compression/HorizontalPredictor.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Tiff/RgbaUnassociatedAlphaPredictor16bit_lsb.tiff, tests/Images/Input/Tiff/RgbaUnassociatedAlphaPredictor16bit_msb.tiff, tests/Images/Input/Tiff/RgbaUnassociatedAlphaPredictor32bit_lsb.tiff, tests/Images/Input/Tiff/RgbaUnassociatedAlphaPredictor32bit_msb.tiff, tests/Images/Input/Tiff/RgbaUnassociatedAlphaPredictor8bit.tiff
This PR is a follow up to #2037: I did forget to update the horizontal predictor for handling alpha data. This PR adds support for decoding TIFF images with horizontal predictor with alpha data.
=> TIFF: Add support for horizontal predictor with alpha data

src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.Metadata.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Jpg/issues/Issue2057-App1Parsing.jpg
This PR fixes an issue with APP1 parsing: the remaining bytes was not calculated correctly when it was not an EXIF or XMP profile.
Related to #2057
=> Fix issue with app1 parsing

src/ImageSharp/Metadata/Profiles/Exif/ExifProfile.cs, tests/ImageSharp.Tests/Metadata/Profiles/Exif/ExifProfileTests.cs
Add non-generic overload defaulting to Rgba32. Fix #1995
=> Add non-generic overload for ExifProfile.CreateThumbnail<TPixel>().

src/Directory.Build.props, src/ImageSharp/Diagnostics/MemoryDiagnostics.cs, src/ImageSharp/Formats/Bmp/BmpDecoderCore.cs, src/ImageSharp/Formats/Gif/GifDecoderCore.cs, src/ImageSharp/Formats/Jpeg/Components/Decoder/SpectralConverter{TPixel}.cs, src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs, src/ImageSharp/Formats/Png/PngDecoderCore.cs, src/ImageSharp/Formats/Tiff/Compression/Decompressors/JpegTiffCompression.cs, src/ImageSharp/Formats/Tiff/TiffDecoderCore.cs, src/ImageSharp/Formats/Webp/WebpDecoderCore.cs, tests/ImageSharp.Tests/Formats/Bmp/BmpDecoderTests.cs, tests/ImageSharp.Tests/Formats/Gif/GifDecoderTests.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.Metadata.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.cs, tests/ImageSharp.Tests/Formats/Pbm/PbmDecoderTests.cs, tests/ImageSharp.Tests/Formats/Png/PngDecoderTests.cs, tests/ImageSharp.Tests/Formats/Tga/TgaDecoderTests.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffDecoderTests.cs, tests/ImageSharp.Tests/Formats/WebP/WebpDecoderTests.cs, tests/ImageSharp.Tests/Image/ImageTests.LoadPixelData.cs, tests/ImageSharp.Tests/Image/LargeImageIntegrationTests.cs, tests/ImageSharp.Tests/MemoryAllocatorValidator.cs, tests/ImageSharp.Tests/TestUtilities/ImageComparison/ImageComparingUtils.cs, tests/ImageSharp.Tests/TestUtilities/ImageProviders/FileProvider.cs, tests/ImageSharp.Tests/ValidateDisposedMemoryAllocationsAttribute.cs
This adds some new test helpers APIs + updates the `MemoryDiagnostics` class to consistently track the memory buffers per test.
Also adds 2 helpers in to the tests 
1. `ValidateDisposedMemoryAllocationsAttribute` - This attributes a can be applied to test classes and `Fact`/`Theory`s directly to automatically apply the memory application tracking and validation.
2. `MemoryAllocatorValidator` static class can be used in places the attribute is not appropriate, i.e. inside Remote Executors.
I've also applied some fixes targeting the Decoder tests
this includes the fix from #2081 (which I will merge into this PR so we don't loose attribute of the fix) if we decide this approach is suitable...otherwise we should just merge that one.
=> Memory allocation allocation tracker test helper

src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs, src/ImageSharp/Formats/Jpeg/JpegThrowHelper.cs, src/ImageSharp/IO/BufferedReadStream.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.Images.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Jpg/issues/fuzz/Issue2085-NullReferenceException.jpg
Discussed at https://github.com/SixLabors/ImageSharp/pull/2077. Now before even trying to parse any jpeg marker decoder would check whether input stream has enough bytes available thus there's no need to check any `stream.Read(...)` call for return value.
Closes https://github.com/SixLabors/ImageSharp/issues/2085.
=> Added sanity check for every jpeg marker

src/ImageSharp/Metadata/Profiles/Exif/ExifEncodedStringHelpers.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.Images.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegEncoderTests.Metadata.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegEncoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Jpg/issues/Issue2087-exif-null-reference-on-encode.jpg
Closes https://github.com/SixLabors/ImageSharp/issues/2087.
Given image from linked issue contains empty user comment tag which is written last. Allocated buffer is passed as `Span` which is sliced during different exif values rendering to the given buffer. This exact situation led to copying zero bytes to zero-length span aaaaand looks like .net treats empty spans with valid memory pointer as null pointer thus mentioned `ArgumentNullException`.
Fix is fairly simple: use spans instead of working with raw pointers without any fixed statements (love this performance side effect) and unsafe stuff, `Encoding.GetBytes(ReadOnlySpan, Span)` respects empty spans.
~~P.S.
Waiting for issue image usage approval from the issue author.~~
=> Fixed string exif value corner case exception

src/ImageSharp/Formats/Gif/GifDecoderCore.cs, src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs, src/ImageSharp/Formats/Webp/WebpDecoderCore.cs, src/ImageSharp/Formats/Webp/WebpThrowHelper.cs, tests/ImageSharp.Tests/Formats/WebP/WebpMetaDataTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Webp/exif_lossy.webp, tests/Images/Input/Webp/exif_lossy_not_enough_data.webp
A PR to add additional sanitation checks with a view to fix #2075 
Any additional sanitation fixes added to other open branches should be added here.
=> Add missing decoder sanitation checks

src/ImageSharp/Formats/Png/Filters/AverageFilter.cs, src/ImageSharp/Formats/Png/Filters/PaethFilter.cs, src/ImageSharp/Formats/Png/Filters/SubFilter.cs, src/ImageSharp/Formats/Png/Filters/UpFilter.cs
This PR adds ARM intrinsics versions of the PNG filter methods.
Benchmark results for random data of size 1024, which could be a typical image row:
```
BenchmarkDotNet=v0.13.1, OS=ubuntu 20.04
Unknown processor
.NET SDK=5.0.402
[Host]     : .NET 5.0.11 (5.0.1121.47308), Arm64 RyuJIT
DefaultJob : .NET 5.0.11 (5.0.1121.47308), Arm64 RyuJIT
|        Method |        Mean |    Error |   StdDev |
|-------------- |------------:|---------:|---------:|
|      UpScalar |  2,568.1 ns |  0.74 ns |  0.66 ns |
|         UpArm |    438.2 ns |  0.10 ns |  0.08 ns |
|     SubScalar |  3,130.6 ns |  0.15 ns |  0.13 ns |
|        SubArm |    864.5 ns |  0.04 ns |  0.03 ns |
| AverageScalar |  4,278.0 ns |  0.90 ns |  0.75 ns |
|    AverageArm |  1,154.6 ns |  0.20 ns |  0.19 ns |
|   PaethScalar | 15,902.9 …
```
=> Add ARM versions of PNG filters

.github/workflows/build-and-test.yml, .github/workflows/code-coverage.yml, ImageSharp.sln, src/ImageSharp/ImageSharp.csproj, tests/ImageSharp.Benchmarks/ImageSharp.Benchmarks.csproj, tests/ImageSharp.Tests.ProfilingSandbox/ImageSharp.Tests.ProfilingSandbox.csproj, tests/ImageSharp.Tests.ProfilingSandbox/LoadResizeSaveParallelMemoryStress.cs, tests/ImageSharp.Tests/Formats/Jpg/DCTTests.cs, tests/ImageSharp.Tests/Formats/Png/PngEncoderFilterTests.cs, tests/ImageSharp.Tests/ImageSharp.Tests.csproj, tests/ImageSharp.Tests/TestUtilities/FeatureTesting/FeatureTestRunner.cs, tests/ImageSharp.Tests/TestUtilities/Tests/FeatureTestRunnerTests.cs
Reduces our target framework collection to .NET 6 only (.NET 7 when CI testing preview). See https://github.com/SixLabors/ImageSharp/discussions/2072
I'll do a follow up PR to clear out any compiler conditionals for items with guaranteed support. 
e.g `#if SUPPORTS_RUNTIME_INTRINSICS`
=> Use .NET 6 only

src/ImageSharp/Formats/Webp/Lossy/QuantEnc.cs, src/ImageSharp/Formats/Webp/Lossy/Vp8Matrix.cs
Use the ReadOnlySpan<byte> static data compiler optimization in 2 more places.
=>  Use ReadOnlySpan<byte> static data compiler optimization in more places

src/ImageSharp/Formats/Webp/Lossy/Vp8EncIterator.cs, src/ImageSharp/Formats/Webp/Lossy/Vp8ModeScore.cs, src/ImageSharp/Formats/Webp/Lossy/YuvConversion.cs
Replace all `Array.Clear(array, 0, array.Length);` calls with `Array.Clear(array);` (available since .NET 6).
Less code and more optimized.
=> Replace Array.Clear(array, 0, array.Length) calls with Array.Clear(array)

src/ImageSharp/Formats/Bmp/BmpColorSpace.cs, src/ImageSharp/Formats/Bmp/BmpDecoderCore.cs, src/ImageSharp/Formats/Bmp/BmpEncoderCore.cs, src/ImageSharp/Formats/Bmp/BmpFileHeader.cs, src/ImageSharp/Formats/Bmp/BmpInfoHeader.cs, src/ImageSharp/Formats/Bmp/BmpRenderingIntent.cs, tests/ImageSharp.Tests/Formats/Bmp/BmpDecoderTests.cs, tests/ImageSharp.Tests/Formats/Bmp/BmpEncoderTests.cs, tests/ImageSharp.Tests/Formats/Bmp/BmpMetadataTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Bmp/BMP_v5_with_ICC_2.bmp
This PR changes the decoder to read the color profile when present and also the encoder to preserve it when encoding a bitmap.
Related to #2107
=> Preserve color profile when encoding bitmaps

src/ImageSharp/Formats/Webp/BitWriter/BitWriterBase.cs, src/ImageSharp/Formats/Webp/BitWriter/Vp8BitWriter.cs, src/ImageSharp/Formats/Webp/BitWriter/Vp8LBitWriter.cs, src/ImageSharp/Formats/Webp/Lossless/Vp8LEncoder.cs, src/ImageSharp/Formats/Webp/Lossy/Vp8Encoder.cs, tests/ImageSharp.Tests/Formats/WebP/WebpMetaDataTests.cs
This PR changes the webp encoder to preserve the color profile when encoding an image.
Related to #2107
=> Preserve color profile when encoding webp images

src/ImageSharp/Formats/Png/PngDecoderCore.cs, src/ImageSharp/Formats/Png/PngEncoderCore.cs, tests/ImageSharp.Tests/Formats/Png/PngEncoderTests.Chunks.cs, tests/ImageSharp.Tests/Formats/Png/PngMetadataTests.cs
This PR changes the PNG encoder to preserve the color profile when encoding an image.
Related issue: #2107
=> Preserve color profile when encoding PNG images

.github/workflows/build-and-test.yml, src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs, src/ImageSharp/Formats/Jpeg/JpegThrowHelper.cs, src/ImageSharp/Formats/Tiff/PhotometricInterpretation/YCbCrTiffColor{TPixel}.cs, src/ImageSharp/Formats/Tiff/TiffDecoderOptionsParser.cs, tests/Directory.Build.targets, tests/ImageSharp.Tests/Formats/Tiff/TiffDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/External/ReferenceOutput/TiffDecoderTests/TiffDecoder_CanDecode_YCbCr_24Bit_Rgba32_flower-ycbcr-contig-08_h1v1.png, tests/Images/External/ReferenceOutput/TiffDecoderTests/TiffDecoder_CanDecode_YCbCr_24Bit_Rgba32_flower-ycbcr-contig-08_h2v1.png, tests/Images/External/ReferenceOutput/TiffDecoderTests/TiffDecoder_CanDecode_YCbCr_24Bit_Rgba32_flower-ycbcr-contig-08_h2v2.png, tests/Images/External/ReferenceOutput/TiffDecoderTests/TiffDecoder_CanDecode_YCbCr_24Bit_Rgba32_flower-ycbcr-contig-08_h4v4.png, tests/Images/External/ReferenceOutput/TiffDecoderTests/TiffDecoder_CanDecode_YCbCr_24Bit_Rgba32_flower-ycbcr-planar-08_h1v1.png, tests/Images/External/ReferenceOutput/TiffDecoderTests/TiffDecoder_CanDecode_YCbCr_24Bit_Rgba32_rgb-ycbcr-contig-08_h2v2.png, tests/Images/External/ReferenceOutput/TiffDecoderTests/TiffDecoder_CanDecode_YCbCr_24Bit_Rgba32_rgb-ycbcr-contig-08_h4v4.png, tests/Images/Input/Tiff/Issues/Issue2123.tiff, tests/Images/Input/Tiff/rgb_jpegcompressed_nojpegtable.tiff, tests/Images/Input/Tiff/twain-rgb-jpeg-with-bogus-ycbcr-subsampling.tiff, tests/Images/Input/Tiff/ycbcr_jpegcompressed2.tiff
A backport of #2124 for V2 plus an update to the build script to run tests against release branches.
I did this manually as I didn't want to spend time fighting Git. Only critical changes were copied across.
=> Backport - Issue 2123

src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Jpg/issues/Issue2133.jpg
Another case of deducing the color space of a jpeg image based on the component id's.
Related issue #2133
=> Deduce color space as YCbCr if component id's are 1, 2, 3

src/ImageSharp/Formats/Jpeg/Components/Decoder/JpegBitReader.cs, src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Jpg/issues/Issue2136-scan-segment-extraneous-bytes.jpg
Fixes https://github.com/SixLabors/ImageSharp/issues/2136
Given image contained extra unused bytes right at the end of the SOS segment containing RST markers and `0xFF00` sequences. This lead to non-SOS parser to count them as valid markers and failed with exception. With this PR jpeg decoder now skips any invalid markers during non-SOS parsing so we can at least give the user something instead of exception.
=> Skip invalid markers during jpeg decoding

src/ImageSharp/Formats/Tiff/Compression/Decompressors/T6TiffCompression.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Tiff/Issues/Group4CompressionWithStrips.tiff
This PR fixes an issue with Fax4 compressed tiff images introduced in #2134.
Closes #2149
=> Fix regression in TIF image loading

src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs, src/ImageSharp/Formats/Webp/WebpDecoderCore.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.cs, tests/ImageSharp.Tests/Formats/WebP/WebpDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Jpg/issues/Issue2133.jpg, tests/Images/Input/Webp/issues/Issue2154.webp
Adds backported fixes for #2133 and #2154
=> V2 Backport: 2133, 2154

tests/ImageSharp.Tests/ImageSharp.Tests.csproj, tests/ImageSharp.Tests/TestUtilities/SixLaborsXunitTestFramework.cs
Uses the BenchMarkDotNet tooling to print out environment information before running any tests.
Should be helpful figuring out what is happening with #2117 and https://github.com/SixLabors/ImageSharp/pull/2173#issuecomment-1183293799
=> Print environment info on tests start

src/ImageSharp/Formats/Tga/TgaDecoderCore.cs, src/ImageSharp/Formats/Tga/TgaEncoderCore.cs, tests/ImageSharp.Tests/Formats/Tga/TgaDecoderTests.cs, tests/ImageSharp.Tests/Formats/Tga/TgaEncoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Tga/Github_RLE_legacy.tga, tests/Images/Input/Tga/whitestripes.png
This is a follow up PR for #2172. It does a few things:
- Add tests for #2172
- Add checks to make sure enough data is available when decoding
- Change run length encoding to not always write RLE packets. This can be ineffective (add overhead) if there are no equal pixels.
=> TGA Encoder/Decoder Improvements

src/ImageSharp/Formats/Tiff/TiffEncoderCore.cs
Fixes issue #2179: It was possible to choose a invalid encoder option combination with `TiffPhotometricInterpretation.Rgb` and one of the 1D compressions. This was caught by a `Debug.Guard`, but well only in Debug mode. This PR fixes Encoder Options sanitization by not allowing this and fallback to RGB/No-Compression.
=> Tiff: Make sure 1 Bit compression is only used with 1 bit pixel type

src/ImageSharp/Common/Helpers/EnumUtils.cs
The `EnumUtils.Parse` method used to use the non-generic `Enum.GetValues` method to do its job, which is unsafe and produces AOT warnings.
This PR refactors it to use `Enum.IsDefined` instead, which does not allocate.
I also added asserts to methods in `EnumUtils` that ensure we use them with int-sized enums.
=> Refactor `EnumUtils` and make it AOT-friendly.

src/ImageSharp/Metadata/Profiles/IPTC/IptcProfile.cs, src/ImageSharp/Metadata/Profiles/IPTC/IptcRecordNumber.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegEncoderTests.Metadata.cs, tests/ImageSharp.Tests/Metadata/Profiles/IPTC/IptcProfileTests.cs
This fixes the issue of incorrect characters showed on IPTC tags that contains non-English characters.
=> Fix IPTC tags written on jpg files that contains non-English characters can't be correctly displayed on external apps #2212

src/ImageSharp/Formats/Png/PngDecoderCore.cs, tests/ImageSharp.Tests/Formats/Png/PngDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Png/issues/Issue_2209.png
This PR fixes an issue that `HasTransparency` is not set for index PNG's.
This fixes #2209
=> Identify transparency for indexed PNG correctly

tests/ImageSharp.Tests/TestFile.cs
=> Make TestFile Image threadsafe.

src/ImageSharp/Common/Helpers/Numerics.cs, src/ImageSharp/Formats/Png/Filters/AverageFilter.cs, src/ImageSharp/Formats/Png/Filters/NoneFilter.cs, src/ImageSharp/Formats/Png/Filters/PaethFilter.cs, src/ImageSharp/Formats/Png/Filters/SubFilter.cs, src/ImageSharp/Formats/Png/Filters/UpFilter.cs, tests/ImageSharp.Tests/Formats/Png/ReferenceImplementations.cs
Fixes a bug in the sums calculation for adaptive filtering:
https://github.com/SixLabors/ImageSharp/blob/ea97bac681f325e3ca4e1ecb87eb53d0048c1d25/src/ImageSharp/Formats/Png/Filters/AverageFilter.cs#L217
I can only guess this adjustment was compensating for a bug that existed in an earlier version of the code where it counted the row filter byte in the sum.  In any case, that is not happening now, so the adjustment at the end is taking away from a valid sum value.  Although this is generally harmless, it does mean that in the event of a tie for sum values (e.g. 0 in a solid color image), Paeth will win by virtue of its larger row filter number (-4 adjustment), making the resulting image needlessly expensive to decode.
Also tidies up the code and codegen for PNG filters in a few ways:
* …
=> PNG filter improvements

src/ImageSharp/PixelFormats/HalfTypeHelper.cs
Replaces our incredibly complex custom packing code with `System.Half` plus casting.
=> Use System.Half for HalfTypeHelper

src/ImageSharp/Compression/Zlib/DeflateThrowHelper.cs, src/ImageSharp/Formats/Bmp/BmpThrowHelper.cs, src/ImageSharp/Formats/Gif/GifThrowHelper.cs, src/ImageSharp/Formats/Jpeg/JpegThrowHelper.cs, src/ImageSharp/Formats/Png/PngThrowHelper.cs, src/ImageSharp/Formats/Tga/TgaThrowHelper.cs, src/ImageSharp/Formats/Tiff/TiffThrowHelper.cs, src/ImageSharp/Formats/Webp/WebpThrowHelper.cs
=> [Chore] Remove InlineningOption from ThrowHelpers

src/ImageSharp/Advanced/IRowIntervalOperation{TBuffer}.cs, src/ImageSharp/Advanced/IRowOperation{TBuffer}.cs, src/ImageSharp/Advanced/ParallelRowIterator.Wrappers.cs, src/ImageSharp/Advanced/ParallelRowIterator.cs, src/ImageSharp/Processing/Processors/Binarization/AdaptiveThresholdProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Binarization/BinaryThresholdProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Convolution/BokehBlurProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Convolution/Convolution2DProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Convolution/Convolution2DRowOperation{TPixel}.cs, src/ImageSharp/Processing/Processors/Convolution/Convolution2PassProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Convolution/ConvolutionProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Convolution/MedianBlurProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Convolution/MedianRowOperation{TPixel}.cs, src/ImageSharp/Processing/Processors/Effects/PixelRowDelegateProcessor{TPixel,TDelegate}.cs, src/ImageSharp/Processing/Processors/Filters/FilterProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Filters/OpaqueProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Normalization/AutoLevelProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Normalization/GlobalHistogramEqualizationProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Normalization/GrayscaleLevelsRowOperation{TPixel}.cs, src/ImageSharp/Processing/Processors/Overlays/GlowProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Overlays/VignetteProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Transforms/Linear/AffineTransformProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Transforms/Linear/ProjectiveTransformProcessor{TPixel}.cs, tests/ImageSharp.Tests/Helpers/ParallelRowIteratorTests.cs, tests/ImageSharp.Tests/TestUtilities/TestImageExtensions.cs
Some implementation of `IRowOperation{T}` and `IRowIntervalOperation{T}` interfaces use buffer length other than the width of the bounds. Examples are most convolution processors.
This PR makes the required buffer length an explicit method in these interfaces. This introduces some boiler plate code when the `IRowOperation{T}` is using the default, but I think the readability of the code improves even there. When re-using `IRowOperation{T}` implementations in other processors, the _internal_ knowledge of the buffer length is no longer required. Last but not least, my personal trigger to start this PR: It eliminates contributors going back and forth between the RowOperation and the Processor when the buffer length is changed in the code.
Also, implemented buffered pixel conversions in …
=> Extend row operation interfaces with buffer length method

src/ImageSharp/Formats/Webp/WebpDecoderCore.cs, tests/ImageSharp.Tests/Formats/WebP/WebpDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Webp/issues/Issue2243.webp
Fix for issue #2243, ignoring unknown chunks.
=> Webp: Ignore unknown chunks, fixes #2243

src/ImageSharp/IO/BufferedReadStream.cs, tests/ImageSharp.Tests/IO/BufferedReadStreamTests.cs
Changes the behavior to prefill when the position is set out of the buffer range.
=> Fix position handling in BufferedReadStream

src/ImageSharp/Formats/Tiff/TiffEncoderCore.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffEncoderBaseTester.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffEncoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Tiff/Issues/Issue2255.png
Make sure bits per pixel is set to 1 for bilevel compression when encoding tiff's, fixes #2255.
=> Tiff: Make sure bits per pixel is set to 1 for bilevel compression

src/ImageSharp/Formats/Webp/AlphaDecoder.cs, tests/ImageSharp.Tests/Formats/WebP/WebpDecoderTests.cs, tests/ImageSharp.Tests/Formats/WebP/WebpEncoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Webp/issues/Issue2257.webp
This PR fixes an issue described in #2257, when decoding an lossy webp image with alpha data.
=> Fix issue decoding lossy webp with alpha channel

src/ImageSharp/IO/BufferedReadStream.cs, src/ImageSharp/Image.FromStream.cs, tests/ImageSharp.Tests/Formats/GeneralFormatTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Png/issues/Issue_2259.png
Fixes #2259 
I wasn't able to replicate the issue with main in synchronous loading (likely due to the decoder refactor) but I was able to do so for our asynchronous load.
I addition I've included a more efficient fix for buffered stream position setting.
=> Ensure seekable streams can be read multiple times.

src/ImageSharp/Formats/Gif/GifDecoderCore.cs, src/ImageSharp/Formats/Gif/GifEncoderCore.cs, src/ImageSharp/Formats/Gif/GifFrameMetadata.cs, src/ImageSharp/Formats/Gif/GifMetadata.cs, src/ImageSharp/Formats/Gif/GifThrowHelper.cs, src/ImageSharp/Formats/Gif/MetadataExtensions.cs, src/ImageSharp/Formats/Gif/Sections/GifGraphicControlExtension.cs, src/ImageSharp/Formats/Gif/Sections/GifXmpApplicationExtension.cs, src/ImageSharp/Formats/ImageDecoderUtilities.cs, src/ImageSharp/Metadata/ImageFrameMetadata.cs, src/ImageSharp/Processing/Processors/Quantization/OctreeQuantizer{TPixel}.cs, src/ImageSharp/Processing/Processors/Quantization/PaletteQuantizer.cs, tests/ImageSharp.Tests/Formats/Gif/GifEncoderTests.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffEncoderMultiframeTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/ImageSharp.Tests/TestUtilities/ImageComparison/ExactImageComparer.cs, tests/ImageSharp.Tests/TestUtilities/ImageComparison/Exceptions/ImageDifferenceIsOverThresholdException.cs, tests/ImageSharp.Tests/TestUtilities/ImageComparison/ImageComparer.cs, tests/ImageSharp.Tests/TestUtilities/ImageComparison/ImageSimilarityReport.cs, tests/ImageSharp.Tests/TestUtilities/ImageComparison/TolerantImageComparer.cs, tests/Images/Input/Gif/issues/issue_2288.gif, tests/Images/Input/Gif/issues/issue_2288_2.gif, tests/Images/Input/Gif/issues/issue_2288_3.gif, tests/Images/Input/Gif/issues/issue_2288_4.gif
Fixes #2288 
This PR does a few things
- Ensures that Graphics Control Extension blocks are read and written correctly
- No longer clones the entire previous frame on decode and only write what we need. This was causing some gif sizes to explode.
- Fixes decode transparency flag handling.
- Ensures palette quantizer enables the whole palette
- Changes lower bit threshold for octree hack to ensure a transparent palette entry is maintained
- Allows mixing of global and local color tables per frame as per specification.
- Fixes the comparer to output the correct frames index.
- Fixes bad XMP handling
=> Fix various Gif Decoder/Encoder behaviors. 

src/ImageSharp/Formats/Tiff/TiffEncoderCore.cs, src/ImageSharp/Formats/Tiff/TiffEncoderEntriesCollector.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffEncoderTests.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffMetadataTests.cs, tests/Images/Input/Tiff/metadata_sample.tiff
This PR fixes the following issues when encoding tiff images:
- Write padding byte, because the tiff spec requires ifd offset to begin on a word boundary.
- Change samples per pixel to ushort
Closes #2297
=> Fix small deviation to the spec when encoding tiff images

src/ImageSharp/Image.WrapMemory.cs, tests/ImageSharp.Tests/Image/ImageTests.WrapMemory.cs
* Added byteLength parameter to WrapMemory method and check that the memory is at least the size of byteLength
See #1489
=> Add byteLength to WrapMemory

src/ImageSharp/Formats/Jpeg/Components/Decoder/JFifMarker.cs, src/ImageSharp/Formats/Jpeg/Components/Decoder/SpectralConverter.cs, src/ImageSharp/Formats/Jpeg/Components/Decoder/SpectralConverter{TPixel}.cs, src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs, tests/ImageSharp.Benchmarks/Codecs/Jpeg/DecodeJpegParseStreamOnly.cs, tests/ImageSharp.Tests/Formats/Jpg/JFifMarkerTests.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.cs, tests/ImageSharp.Tests/Formats/Jpg/SpectralJpegTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Jpg/issues/issue-2315.jpg
Fixes #2315 
The image has two issues. 
1. Zero density unit values in the JFIF header.
2. Erroneous marker data at the end of the stream following the image data.
I've relaxed the decoder to cater for these cases.
cc\ @br3aker
=> Allow zero DPI and only throw at EOF when not enough data

src/ImageSharp/Color/Color.cs, src/ImageSharp/ColorSpaces/Conversion/ColorSpaceConverter.Adapt.cs, src/ImageSharp/ColorSpaces/Conversion/ColorSpaceConverter.CieXyz.cs, src/ImageSharp/ColorSpaces/Conversion/ColorSpaceConverter.cs, src/ImageSharp/ColorSpaces/Conversion/ColorSpaceConverterOptions.cs, src/ImageSharp/ColorSpaces/Conversion/Implementation/WorkingSpaces/RgbWorkingSpace.cs
Remove nullable disable from ColorSpace and Color
=> Remove nullable disable from ColorSpace and Color

src/ImageSharp/PixelFormats/PixelImplementations/A8.cs, src/ImageSharp/PixelFormats/PixelImplementations/Abgr32.cs, src/ImageSharp/PixelFormats/PixelImplementations/Argb32.cs, src/ImageSharp/PixelFormats/PixelImplementations/Bgr24.cs, src/ImageSharp/PixelFormats/PixelImplementations/Bgr565.cs, src/ImageSharp/PixelFormats/PixelImplementations/Bgra32.cs, src/ImageSharp/PixelFormats/PixelImplementations/Bgra4444.cs, src/ImageSharp/PixelFormats/PixelImplementations/Byte4.cs, src/ImageSharp/PixelFormats/PixelImplementations/HalfSingle.cs, src/ImageSharp/PixelFormats/PixelImplementations/HalfVector2.cs, src/ImageSharp/PixelFormats/PixelImplementations/HalfVector4.cs, src/ImageSharp/PixelFormats/PixelImplementations/L16.cs, src/ImageSharp/PixelFormats/PixelImplementations/L8.cs, src/ImageSharp/PixelFormats/PixelImplementations/La16.cs, src/ImageSharp/PixelFormats/PixelImplementations/La32.cs, src/ImageSharp/PixelFormats/PixelImplementations/NormalizedByte2.cs, src/ImageSharp/PixelFormats/PixelImplementations/NormalizedByte4.cs, src/ImageSharp/PixelFormats/PixelImplementations/NormalizedShort2.cs, src/ImageSharp/PixelFormats/PixelImplementations/NormalizedShort4.cs, src/ImageSharp/PixelFormats/PixelImplementations/Rg32.cs, src/ImageSharp/PixelFormats/PixelImplementations/Rgb24.cs, src/ImageSharp/PixelFormats/PixelImplementations/Rgb48.cs, src/ImageSharp/PixelFormats/PixelImplementations/Rgba1010102.cs, src/ImageSharp/PixelFormats/PixelImplementations/Rgba32.cs, src/ImageSharp/PixelFormats/PixelImplementations/Rgba64.cs, src/ImageSharp/PixelFormats/PixelImplementations/RgbaVector.cs, src/ImageSharp/PixelFormats/PixelImplementations/Short2.cs, src/ImageSharp/PixelFormats/PixelImplementations/Short4.cs
#2231 Remove nullable disable from PixelImplementation and fix the errors
=> Remove nullable disable from pixelimplementations

src/ImageSharp/Formats/Gif/GifEncoderCore.cs, src/ImageSharp/Processing/DefaultImageProcessorContext{TPixel}.cs, src/ImageSharp/Processing/Processors/Convolution/KernelSamplingMap.cs, src/ImageSharp/Processing/Processors/Drawing/DrawImageProcessor.cs, src/ImageSharp/Processing/Processors/Quantization/OctreeQuantizer{TPixel}.cs, src/ImageSharp/Processing/Processors/Quantization/PaletteQuantizer{TPixel}.cs, src/ImageSharp/Processing/Processors/Quantization/QuantizerOptions.cs, src/ImageSharp/Processing/Processors/Quantization/QuantizerUtilities.cs, src/ImageSharp/Processing/Processors/Quantization/WuQuantizer{TPixel}.cs, src/ImageSharp/Processing/Processors/Transforms/Linear/AffineTransformProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Transforms/Linear/ProjectiveTransformProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Transforms/Resize/ResizeProcessor{TPixel}.cs
#2231
Here I went the easy way and introduced some bangs!.
It is not easy to not use it, for example using the visitor pattern, I can not tell the compiler that the value is not null so I had to use the !
=> Remove nullable disable from Processing.Processors

src/ImageSharp/Formats/Tiff/Compression/HorizontalPredictor.cs, src/ImageSharp/Formats/Tiff/Constants/TiffConstants.cs, src/ImageSharp/Formats/Tiff/TiffBitsPerPixel.cs, src/ImageSharp/Formats/Tiff/TiffEncoderCore.cs, src/ImageSharp/Formats/Tiff/TiffEncoderEntriesCollector.cs, src/ImageSharp/Formats/Tiff/Writers/TiffColorWriterFactory.cs, src/ImageSharp/Formats/Tiff/Writers/TiffGrayL16Writer{TPixel}.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffDecoderTests.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffEncoderTests.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffMetadataTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Tiff/Calliphora_gray_deflate_16bit.tiff, tests/Images/Input/Tiff/Calliphora_gray_deflate_predictor_16bit.tiff, tests/Images/Input/Tiff/Calliphora_gray_lzw_predictor_16bit.tiff, tests/Images/Input/Tiff/Calliphora_grayscale_uncompressed_16bit.tiff, tests/Images/Input/Tiff/grayscale_uncompressed_16bit.tiff
Added L16 support to tiff encoder ([source discussion](https://github.com/SixLabors/ImageSharp/discussions/2333)).
Breaking Changes:
- When encoder BitsPerPixel is set to Bit16, the image will be encoded as L16 now instead of Rgb24
- When only PhotometricInterpretation is set to BlackIsZero or WhiteIsZero and source image pixel type has Bits/Px of 16 then the image will be encoded as L16 instead of L8
- When neither is set and source image pixel type has Bits/Px of 16 then the image will be encoded as L16 instead of Rgb24
=> Added L16 support to tiff encoder

src/ImageSharp/Compression/Zlib/Adler32.cs, src/ImageSharp/Compression/Zlib/Crc32.cs, src/ImageSharp/Formats/Png/Filters/AverageFilter.cs, src/ImageSharp/Formats/Png/Filters/PaethFilter.cs, src/ImageSharp/Formats/Png/Filters/SubFilter.cs, src/ImageSharp/Formats/Png/Filters/UpFilter.cs, tests/ImageSharp.Tests/Formats/Png/Crc32Tests.cs, tests/ImageSharp.Tests/TestUtilities/FeatureTesting/FeatureTestRunner.cs, tests/ImageSharp.Tests/TestUtilities/Tests/FeatureTestRunnerTests.cs
All credit goes to @brianpopow here. Merging main into his arm branch containing these optimizations proved too difficult after a 10 month gap so I simply recreated them in a new branch.
=> Add ARM Intrinsics for PNG filters

src/ImageSharp/Compression/Zlib/Adler32.cs, src/ImageSharp/Compression/Zlib/Crc32.cs
This is a follow up PR for #2344: There was a mistake that the arm methods for Adler and CRC32 were not called. It was not catched by tests, because it did fallback to the scalar version.
=> Actually call arm methods, if arm is supported

src/ImageSharp/Formats/DecoderOptions.cs, tests/ImageSharp.Tests/TestUtilities/ImageProviders/FileProvider.cs
The property was internal when it shouldn't be.
=> Allow setting configuration property

tests/ImageSharp.Tests/xunit.runner.json
Added `"preEnumerateTheories": false` to the xunit config, to avoid many useless warnings during tests.
=> Disable preEnumerateTheories for running tests

.github/workflows/build-and-test.yml, ci-pack.ps1
=> Attempt to workaround SDK build changes

.github/workflows/build-and-test.yml, README.md
MyGet is refusing to upload our binaries reporting the following error
>Pushing SixLabors.ImageSharp.3.0.0-alpha.0.101.nupkg to 'https://www.myget.org/F/sixlabors/api/v2/package'...
PUT https://www.myget.org/F/sixlabors/api/v2/package/
RequestEntityTooLarge https://www.myget.org/F/sixlabors/api/v2/package/ 1312ms
error: Response status code does not indicate success: 413 (The total packages size for the pending uploads is too large. The feed owner may have to upgrade the MyGet subscription to resolve this issue.).
We've only used 6MB of 100MB so I'm switching our as I cannot afford time wasted. 
Feedz give us 2GB of storage and 2GB of package traffic per month plus has a limit of 3.5GB for individual package sizes so should never cause issues.
=> Replace MyGet with Feedz as our nightly package repository.

.gitattributes, src/ImageSharp/Formats/Webp/AlphaDecoder.cs, src/ImageSharp/Formats/Webp/AlphaEncoder.cs, src/ImageSharp/Formats/Webp/BitReader/BitReaderBase.cs, src/ImageSharp/Formats/Webp/BitReader/Vp8BitReader.cs, src/ImageSharp/Formats/Webp/BitReader/Vp8LBitReader.cs, src/ImageSharp/Formats/Webp/BitWriter/BitWriterBase.cs, src/ImageSharp/Formats/Webp/BitWriter/Vp8BitWriter.cs, src/ImageSharp/Formats/Webp/BitWriter/Vp8LBitWriter.cs, src/ImageSharp/Formats/Webp/Lossless/BackwardReferenceEncoder.cs, src/ImageSharp/Formats/Webp/Lossless/ColorCache.cs, src/ImageSharp/Formats/Webp/Lossless/CostInterval.cs, src/ImageSharp/Formats/Webp/Lossless/CostManager.cs, src/ImageSharp/Formats/Webp/Lossless/WebpLosslessDecoder.cs, src/ImageSharp/Formats/Webp/Lossy/Vp8Encoder.cs, src/ImageSharp/Formats/Webp/WebpAnimationDecoder.cs, src/ImageSharp/Formats/Webp/WebpChunkParsingUtils.cs, src/ImageSharp/Formats/Webp/WebpDecoderCore.cs, src/ImageSharp/Formats/Webp/WebpEncoder.cs, src/ImageSharp/Formats/Webp/WebpEncoderCore.cs, src/ImageSharp/Formats/Webp/WebpImageInfo.cs, src/ImageSharp/Formats/Webp/WebpThrowHelper.cs
#2231 Remove nullable disable from some classes in the webp format
=> #2231 First steps for removing nullable disable in webp

.gitattributes, src/ImageSharp/Common/Helpers/Numerics.cs, src/ImageSharp/Common/Helpers/Shuffle/IComponentShuffle.cs, src/ImageSharp/Common/Helpers/Shuffle/IPad3Shuffle4.cs, src/ImageSharp/Common/Helpers/Shuffle/IShuffle3.cs, src/ImageSharp/Common/Helpers/Shuffle/IShuffle4Slice3.cs, src/ImageSharp/PixelFormats/PixelBlenders/PorterDuffFunctions.Generated.cs, src/ImageSharp/PixelFormats/PixelBlenders/PorterDuffFunctions.Generated.tt, src/ImageSharp/PixelFormats/PixelBlenders/PorterDuffFunctions.cs, tests/ImageSharp.Benchmarks/Color/Bulk/PremultiplyVector4.cs, tests/ImageSharp.Benchmarks/Color/Bulk/Shuffle3Channel.cs, tests/ImageSharp.Benchmarks/Color/Bulk/Shuffle4Slice3Channel.cs, tests/ImageSharp.Benchmarks/Color/Bulk/UnPremultiplyVector4.cs, tests/ImageSharp.Benchmarks/PixelBlenders/PorterDuffBulkVsPixel.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffDecoderTests.cs, tests/Images/External/ReferenceOutput/PorterDuffCompositorTests/PorterDuffOutputIsCorrect_Rgba32_pd-dest_DestOut.png, tests/Images/External/ReferenceOutput/PorterDuffCompositorTests/PorterDuffOutputIsCorrect_Rgba32_pd-dest_In.png, tests/Images/External/ReferenceOutput/PorterDuffCompositorTests/PorterDuffOutputIsCorrect_Rgba32_pd-dest_Out.png
Our existing `UnPremultiply` methods suffered from an issue in that they allowed dividing values by zero. This was masked by our tests since the transform to byte would lead to `zero` in most cases but could cause issues when chaining certain operations requiring premultiplication using single precision pixel formats since interim values for the `XYZ` components would be `∞`.
The Porter-Duff operators contained a bad fix for this by dividing by the max of the `W` component vs an epsilon of `0.001F`. This would lead to out-of-range values if the X, Y, Z components had a non-zero value. This was generally masked by clamping but again could cause issues for single precision pixel formats.
The fix is simple. Compare the alpha component to `zero` and return the source value if so. We return …
=> Fix and normalize Vector4 UnPremultiply

.github/workflows/build-and-test.yml
Adds configuration to automatically push the build to NuGet on a tagged release.
=> Automatically push the build to NuGet on a tagged release

.github/workflows/build-and-test.yml, src/ImageSharp/Formats/Jpeg/Components/ColorConverters/JpegColorConverter.RgbArm.cs, src/ImageSharp/Formats/Jpeg/Components/ColorConverters/JpegColorConverterArm.cs, src/ImageSharp/Formats/Jpeg/Components/ColorConverters/JpegColorConverterBase.cs, tests/ImageSharp.Benchmarks/Codecs/Jpeg/ColorConversion/RgbColorConversion.cs, tests/ImageSharp.Tests/PixelFormats/PixelBlenders/PorterDuffFunctionsTests.cs
This is my first attempt in learning something about intrinsics. 
So I picked something which looked straight forward (for me) for a port to arm.
I will also try to see if there is already an benchmark for this, or going to look into writing one
=> Add Arm intrinsics to JpegColorConverter RGB

README.md, src/ImageSharp/Formats/Jpeg/Components/ColorConverters/JpegColorConverter.CmykArm64.cs, src/ImageSharp/Formats/Jpeg/Components/ColorConverters/JpegColorConverterArm64.cs, src/ImageSharp/Formats/Jpeg/Components/ColorConverters/JpegColorConverterBase.cs, tests/ImageSharp.Benchmarks/Codecs/Jpeg/ColorConversion/CmykColorConversion.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegColorConverterTests.cs
Added Simd for CMYK. I added ARM64 because there was no matching method in arm32
Benchmarks:
|          Method |     Mean |   Error |  StdDev | Ratio | RatioSD |
|---------------- |---------:|--------:|--------:|------:|--------:|
|          Scalar | 288.7 ns | 1.75 ns | 1.64 ns |  1.00 |    0.00 |
|     SimdVector8 | 125.4 ns | 1.74 ns | 1.63 ns |  0.43 |    0.01 |
|   SimdVectorAvx |       NA |      NA |      NA |     ? |       ? |
| SimdVectorArm64 | 108.1 ns | 0.56 ns | 0.43 ns |  0.37 |    0.00 |
=> Add arm64 intrinsics for cmyk converter

src/ImageSharp/Formats/Webp/Lossy/Vp8Encoder.cs
This PR changes the disposing of the encodedAlphaData to be in a try/finally block instead of using statement.
This is related to Issue #2411
=> Webp: Dont use using statement for encodedAlphaData

src/ImageSharp/Formats/Webp/Lossless/LosslessUtils.cs
In https://github.com/SixLabors/ImageSharp/pull/2401 I introduced a bug (sorry for that) -- this PR fixes that.
The bit-hack for divison by powers of two is only valid for positive numerators, and in the failed testcase (cf. https://github.com/SixLabors/ImageSharp/pull/2409#issuecomment-1482798035) it was negative. As showcase see [this sharplab](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAmARgFgAoayPAZwwAIBLPZgExgBsMBDJgF4mcAMwB2ANzVqRMgE4AFF14CA9ExIBKaVTlKV/JgD5jTMjqA===).
**Note to maintainers**: please run CI on ARM too (as I understand that's not on by default, so that bug even came into main-branch)
=> Fixed wrong division hack

src/ImageSharp/Common/Helpers/SimdUtils.HwIntrinsics.cs, src/ImageSharp/Formats/Jpeg/Components/ColorConverters/JpegColorConverter.GrayScaleArm.cs, src/ImageSharp/Formats/Jpeg/Components/ColorConverters/JpegColorConverterBase.cs, tests/ImageSharp.Benchmarks/Codecs/Jpeg/ColorConversion/GrayscaleColorConversion.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegColorConverterTests.cs
Port Grayscaleconverter to ARM
Benchmarks:
```md
|        Method |      Mean |    Error |   StdDev | Ratio | RatioSD |
|-------------- |----------:|---------:|---------:|------:|--------:|
|        Scalar | 118.76 ns | 0.499 ns | 0.443 ns |  1.00 |    0.00 |
| SimdVectorAvx |        NA |       NA |       NA |     ? |       ? |
| SimdVectorArm |  53.57 ns | 0.410 ns | 0.364 ns |  0.45 |    0.00 |
```
=> Port GrayscalConverter to Arm

src/ImageSharp/Formats/Jpeg/Components/ColorConverters/JpegColorConverterBase.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegColorConverterTests.cs
I ran the tests with SSE Disabled. And I found this bug... 
Before fixing it I had 151 failing tests after it only 53 tests are failing. On a quick check all other failures are 'Image difference is over threshold!'
=> Fix RgbScalar

src/ImageSharp/Formats/Jpeg/Components/ColorConverters/JpegColorConverter.YCbCrArm.cs, src/ImageSharp/Formats/Jpeg/Components/ColorConverters/JpegColorConverter.YccKArm64.cs, src/ImageSharp/Formats/Jpeg/Components/ColorConverters/JpegColorConverterBase.cs, tests/ImageSharp.Benchmarks/Codecs/Jpeg/ColorConversion/YCbCrColorConversion.cs, tests/ImageSharp.Benchmarks/Codecs/Jpeg/ColorConversion/YccKColorConverter.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegColorConverterTests.cs
Benchmark:
YCbCr
|        Method |       Mean |    Error |   StdDev |
|-------------- |-----------:|---------:|---------:|
|        Scalar | 4,777.9 ns | 15.98 ns | 14.95 ns |
|   SimdVector8 |   295.5 ns |  1.07 ns |  1.00 ns |
| SimdVectorAvx |         NA |       NA |       NA |
| SimdVectorArm |   188.3 ns |  0.87 ns |  0.77 ns |
YCCk
|          Method |       Mean |    Error |   StdDev | Ratio | RatioSD |
|---------------- |-----------:|---------:|---------:|------:|--------:|
|          Scalar | 5,934.5 ns | 12.66 ns | 11.22 ns |  1.00 |    0.00 |
|     SimdVector8 |   327.8 ns |  0.74 ns |  0.70 ns |  0.06 |    0.00 |
|  SimdVectorAvx2 |         NA |       NA |       NA |     ? |       ? |
| SimdVectorArm64 |   228.3 ns |  0.47 ns |  0.42 ns |  0.04 |    0.00 |
=> Port colorconverter YCbCr and YCCk  to arm

src/ImageSharp/Common/Helpers/Numerics.cs, src/ImageSharp/Common/Helpers/SimdUtils.ExtendedIntrinsics.cs, src/ImageSharp/Common/Helpers/SimdUtils.HwIntrinsics.cs, src/ImageSharp/Formats/Jpeg/Components/ColorConverters/JpegColorConverter.CmykAvx.cs, src/ImageSharp/Formats/Jpeg/Components/ColorConverters/JpegColorConverter.CmykVector.cs, src/ImageSharp/Formats/Jpeg/Components/ColorConverters/JpegColorConverter.GrayScaleArm.cs, src/ImageSharp/Formats/Jpeg/Components/ColorConverters/JpegColorConverter.GrayScaleAvx.cs, src/ImageSharp/Formats/Jpeg/Components/ColorConverters/JpegColorConverter.GrayScaleVector.cs, src/ImageSharp/Formats/Jpeg/Components/ColorConverters/JpegColorConverter.RgbArm.cs, src/ImageSharp/Formats/Jpeg/Components/ColorConverters/JpegColorConverter.RgbAvx.cs, src/ImageSharp/Formats/Jpeg/Components/ColorConverters/JpegColorConverter.RgbVector.cs, src/ImageSharp/Formats/Jpeg/Components/ColorConverters/JpegColorConverter.YCbCrAvx.cs, src/ImageSharp/Formats/Jpeg/Components/ColorConverters/JpegColorConverter.YCbCrVector.cs, src/ImageSharp/Formats/Jpeg/Components/ColorConverters/JpegColorConverter.YccKAvx.cs, src/ImageSharp/Formats/Jpeg/Components/ColorConverters/JpegColorConverter.YccKVector.cs, src/ImageSharp/Formats/Jpeg/Components/Encoder/ComponentProcessor.cs, tests/ImageSharp.Tests/TestUtilities/FeatureTesting/FeatureTestRunner.cs
Instead of typing 
```c#
nuint n = (uint)dest.Length / (uint)Vector256<float>.Count;
```
everytime, there's now a helper that shortens this to
```c#
nuint n = dest.Vector256Count<float>();
```
Cf. https://github.com/SixLabors/ImageSharp/pull/2419#discussion_r1149799246
=> Added and used Numerics.Vector{128|256}Count extension

src/ImageSharp/Common/Helpers/SimdUtils.HwIntrinsics.cs, tests/ImageSharp.Benchmarks/General/PixelConversion/PixelConversion_PackFromRgbPlanes.cs
On .NET 6 onwards (which is relevant here) it's better for codegen to define vector constant inline (including to have helper-methods for this).
* `private static readonly VectorXYZ`-fields produce less ideal code with more indirections
* reading the vector constant from a ROS<byte> (which may refer directly to assembly's data segment) results in some overhead
Now the vector constants can be read from memory directly.
<sub>PS: I don't have any other planned PRs -- right now weather is too bad / good enough to dig through this code 😉</sub>
=> Create vector constants inline and not via ROS<byte>

src/ImageSharp/Image.FromFile.cs, src/ImageSharp/Image.FromStream.cs
This PR fixes Incorrect comments on some methods.
=> Fix incorrect comments

src/ImageSharp/Formats/Jpeg/Components/Decoder/SpectralConverter{TPixel}.cs
Partially fixes #2414 for jpeg and tiff with jpeg compressions tests for scalar path. According to https://github.com/SixLabors/ImageSharp/issues/2414#issuecomment-1491455526 we have some more failing tests for GIF and PNG.
Problem was with how jpeg decoder determined buffer size compliment for color converters as those required buffer size to aligned to their batch size, e.g. for avx with batch size 8 buffer size should be divisible by 8, 204 => 208. For scalar encoders any buffer size is complient as any number is divisible by 1 without a remainder. 
Decoder was adding `(batch_size - remainder)` to the buffer size which led to extra 1 pixel for scalar implementations- that's why decoded image had this diagonal color shift:
This PR is not covered by tests as I want us to discuss possible …
=> Fixed invalid jpeg buffer width compliment for scalar color converters

src/ImageSharp/Formats/Jpeg/Components/Encoder/ComponentProcessor.cs
Added Arm intrinsics in the ComponentProcessor. 
Only SumHorizontal is not ported to Arm.
=> Add AdvSimd in ComponentProcessor

src/ImageSharp/Formats/Tiff/TiffDecoderCore.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Tiff/Issues/Issue2435.tiff
This PR fixes an issue when decoding tiled tiff images. The tile height was not correctly determined.
Fixes #2435
=> Fix decoding tiled tiff with unequal tile width and height

tests/ImageSharp.Tests/Formats/Gif/GifDecoderTests.cs, tests/ImageSharp.Tests/Formats/Png/PngDecoderTests.cs, tests/ImageSharp.Tests/Formats/Tga/TgaDecoderTests.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffDecoderTests.cs, tests/ImageSharp.Tests/Formats/WebP/WebpDecoderTests.cs, tests/Images/External/ReferenceOutput/PngDecoderTests/PngDecoder_Decode_Resize_ScalarResizeKernel_splash_150_150.png
This PR fixes the thresholds for the resize kernel tests, which #2414 revealed.
The resize kernel uses FMA, which can have slightly different results the scalar version.
For more details see discussion: https://github.com/SixLabors/ImageSharp/pull/1513#issuecomment-763643594
Also adds a scalar version of test `PngDecoder_Decode_Resize()`
=> Fix thresholds for Resize kernel tests

src/ImageSharp/Formats/Tiff/Compression/HorizontalPredictor.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/External/ReferenceOutput/TiffDecoderTests/TiffDecoder_CanDecode_Cmyk_Rgba32_Cmyk-lzw-predictor.png, tests/Images/Input/Tiff/Cmyk-lzw-predictor.tiff
Fix for Issue #2456: Horizontal predictor was not reverted correctly when decoding cmyk images.
=> Tiff: Undo horizontal predictor for cmyk images

src/ImageSharp/PixelFormats/PixelImplementations/Rgb48.cs
=> fix a typo in XML comment for struct `Rgb48`

src/ImageSharp/Formats/Bmp/BmpEncoderCore.cs, tests/ImageSharp.Tests/Formats/Bmp/BmpEncoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Bmp/bit1datamatrix.bmp
Fix for issue #2467.
If you have a BMP with 1 bit per pixel, and more pixels per row than divisible by 8, the last byte of the row will need to be padded with extra zeros.
So if you have a black/white image of 10 pixels in a row, and the row looks like: 
`bwwbbbwbww`
The bytes should look like:"
`0x01100010 0x11000000`
However, the current implementation of Write1BitPixelData will when it reaches the last byte looks like:
```C#
if (quantizedPixelRow.Length % 8 != 0)
{
int startIdx = quantizedPixelRow.Length - 7;
endIdx = quantizedPixelRow.Length;
Write1BitPalette(stream, startIdx, endIdx, quantizedPixelRow);
}
```
So `quantizedPixelRow.Length` will be 10, resulting in a `startIdx` of 10-7 = 3
It will then write pixels to the byte starting at index 3 again, meaning that the last bytes …
=> Fix #2467 bmp encoding issue for BMP with 1 bit per pixel and more pixels per row than divisible by 8.

src/ImageSharp/Primitives/LongRational.cs, src/ImageSharp/Primitives/Rational.cs, tests/ImageSharp.Tests/Numerics/RationalTests.cs
In cases, when you're trying to create Rational.FromDouble(0) it generates an invalid Rational item.
=> bugfix in Rational.cs, when both Nominator and Denominator equals to 0

src/ImageSharp/Formats/Pbm/BinaryDecoder.cs, src/ImageSharp/Formats/Pbm/BinaryEncoder.cs, tests/ImageSharp.Tests/Formats/Pbm/PbmDecoderTests.cs, tests/ImageSharp.Tests/Formats/Pbm/PbmEncoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/External/ReferenceOutput/PbmDecoderTests/DecodeReferenceImage_L8_issue2477.png, tests/Images/Input/Pbm/issue2477.pbm
This fixes #2477 by handling Black & White binary images with a width not dividable by 8 correctly. The handling of the padding bits was incorrect and not according to the specification.
Thanks for reporting this bug !
=> Fix for B&W pbm images with width not dividable by 8

src/ImageSharp/Formats/Tiff/Compression/Decompressors/T6BitReader.cs
This PR fixes #2541 as discussed [here](https://github.com/SixLabors/ImageSharp/issues/2451#issuecomment-1544618277):
If we encounter a Extensions1D or 2D code, we read the next 5 bits and if it turns out to be a EOL and not a Extensions1D or 2D, we return that. Otherwise throw a NotSupported Exception for the Extension1D/2D code.
=> Tiff: ccitt compression, fix for issue #2451

src/ImageSharp/IO/IFileSystem.cs, src/ImageSharp/IO/LocalFileSystem.cs, src/ImageSharp/Image.FromFile.cs, src/ImageSharp/ImageExtensions.cs, tests/ImageSharp.Tests/IO/LocalFileSystemTests.cs, tests/ImageSharp.Tests/Image/ImageSaveTests.cs, tests/ImageSharp.Tests/Image/ImageTests.ImageLoadTestBase.cs, tests/ImageSharp.Tests/TestFileSystem.cs, tests/ImageSharp.Tests/TestUtilities/SingleStreamFileSystem.cs
=> Use `FileOptions.Asynchronous` when doing async IO

src/ImageSharp/Formats/Jpeg/Components/Decoder/JFifMarker.cs, src/ImageSharp/Formats/Jpeg/Components/Decoder/ProfileResolver.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Jpg/issues/issue-2478-jfxx.jpg
=> Allow JFXX as an App0 marker header

src/ImageSharp/Formats/Gif/GifEncoderCore.cs
See https://github.com/SixLabors/ImageSharp/pull/2455#issuecomment-1613901985
A simple benchmark -- just for the inner loop -- yields:
```
|     Method |      Mean |    Error |   StdDev | Ratio |
|----------- |----------:|---------:|---------:|------:|
|    Default | 102.33 ns | 2.073 ns | 2.973 ns |  1.00 |
| Vectorized |  16.53 ns | 0.065 ns | 0.055 ns |  0.16 |
```
This is measured with .NET 7, but the codegen for .NET 6 is very similar.
<details>
<summary>benchmark code</summary>
```c#
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Intrinsics;
using BenchmarkDotNet.Attributes;
Bench bench = new();
bench.Setup();
Console.WriteLine(bench.Default());
Console.WriteLine(bench.Vectorized());
#if !DEBUG …
```
=> Vectorize TrimTransparentPixels in GifEncoderCore

src/ImageSharp/Formats/Pbm/BufferedReadStreamExtensions.cs, tests/ImageSharp.Tests/Formats/Pbm/PbmMetadataTests.cs
It's possible to cause the library to hang with a crafted byte array targetting the PBM decoder. This PR fixes that vulnarability. All other formats correctly test for the end of the stream.
=> Prevent crafted DOS attack.

src/ImageSharp/Formats/Pbm/BufferedReadStreamExtensions.cs, tests/ImageSharp.Tests/Formats/Pbm/PbmMetadataTests.cs
=> Backport #2501

ImageSharp.sln, SixLabors.ImageSharp.props
Fixes #2466
Reverses the behavior of our global includes to require an explicit `<UseImageSharp>true</UseImageSharp>` tag. 
Breaking but I think necessary.
=> Reverse automatic include behavior.

.github/workflows/build-and-test.yml, src/ImageSharp/Advanced/ParallelRowIterator.cs, src/ImageSharp/Formats/Jpeg/Components/Decoder/JpegBitReader.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.cs, tests/ImageSharp.Tests/Helpers/ParallelRowIteratorTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Jpg/issues/Hang_C438A851.jpg
This specially crafted file has had the start of frame marker altered to change the dimensions to values (_65503x65503_) that far exceed the encoded data. Nothing seems to be able to open this but with a very small change we actually can and quickly too. 
It's better that we allow decoding than explicitly throwing because there is no way to tell the difference between a maliciously crafted file with complete data from a damaged file with limited data and we already work very hard to enable decoding the latter.
I've also added a fix to allow us to actually parallel process images of this size. I discovered the iterator suffered from an overflow issue during attempts to determine what the maximum dimensions of a file Windows can handle (_65500x65500_) as it cannot decode a reencoded of the …
=> Handle EOF in Jpeg bit reader when data is bad to prevent DOS attack.

src/ImageSharp/Advanced/ParallelRowIterator.cs, src/ImageSharp/Formats/Jpeg/Components/Decoder/HuffmanScanBuffer.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.cs, tests/ImageSharp.Tests/Helpers/ParallelRowIteratorTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Jpg/issues/Hang_C438A851.jpg
=> Backport - Handle EOF in Jpeg bit reader when data is bad to prevent DOS attack.

src/ImageSharp/Formats/Tiff/TiffEncoderCore.cs, src/ImageSharp/Formats/Tiff/TiffEncoderEntriesCollector.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffMetadataTests.cs
When testing adding and writing out IPTC tag data, it was found that the data was being lost during the save process for TIFF files.  It was also determined that the ICC profile data was also being lost.
During debugging, it was found that the Exif and XMP profiles were coming from the root frame only, and the IPTC and ICC profiles were coming from the image and not the root frame.
The changes introduced by this pull request split the writing of the image's metadata from each frame's metadata.  Also, rather than only using the profile data from the root frame, the metadata for each frame is written instead.  If multiple frames in the TIFF file have different metadata settings, that should preserve the data for each frame.
A new unit test was added to store and retrieve IPTC and ICC …
=> Fix for issue 2504 - IPTC and ICC profile information being lost during TIFF file save

src/ImageSharp/Metadata/Profiles/Exif/Tags/ExifTag.LongArray.cs, src/ImageSharp/Metadata/Profiles/Exif/Tags/ExifTag.SignedShortArray.cs, src/ImageSharp/Metadata/Profiles/Exif/Values/ExifSignedShortArray.cs, src/ImageSharp/Metadata/Profiles/Exif/Values/ExifValues.cs, tests/ImageSharp.Tests/Metadata/Profiles/Exif/Values/ExifValuesTests.cs
Fixes #2437 
As per the linked issue. TimeZoneOffset is a signed short array. However, currently in ImageSharp it is treated as a unsigned short array.
Changing the type to match the spec.
=> Change ExifTag TimeZoneOffset to Signed Short

src/ImageSharp/Metadata/Profiles/Exif/Tags/ExifTag.Rational.cs, src/ImageSharp/Metadata/Profiles/Exif/Tags/ExifTagValue.cs, src/ImageSharp/Metadata/Profiles/Exif/Values/ExifValues.cs, tests/ImageSharp.Tests/Metadata/Profiles/Exif/Values/ExifValuesTests.cs
Fixes #2542 
This PR adds the missing GPSHPositioningError Exif tag. I've also checked that all the other GPS related tags are present, this is the only one that seem to have been missed.
=> Add GPSHPositioningError exif tag

src/ImageSharp/ImageSharp.csproj, src/ImageSharp/Memory/Allocators/UniformUnmanagedMemoryPoolMemoryAllocator.cs, tests/ImageSharp.Tests/Image/ImageTests.cs, tests/ImageSharp.Tests/Memory/Allocators/UniformUnmanagedPoolMemoryAllocatorTests.cs
Throw an exception on allocation attempts of sizes that are not representable by `long`.
=> Disallow allocation attempts of unrepresentable sizes

src/ImageSharp/Formats/Tiff/Compression/Decompressors/WebpTiffCompression.cs, src/ImageSharp/Formats/Tiff/Compression/TiffDecompressorsFactory.cs, src/ImageSharp/Formats/Webp/BackgroundColorHandling.cs, src/ImageSharp/Formats/Webp/WebpAnimationDecoder.cs, src/ImageSharp/Formats/Webp/WebpDecoder.cs, src/ImageSharp/Formats/Webp/WebpDecoderCore.cs, src/ImageSharp/Formats/Webp/WebpDecoderOptions.cs, tests/ImageSharp.Tests/Formats/WebP/WebpDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Webp/issues/Issue2528.webp
Adds a flag to decide how to handle the background color Animation Chunk.
The specification is vague on how to handle the background color of the animation chunk.
This option let's the user choose how to deal with it.
Related Issue: #2528
=> Add webp decoder option to handle the background color in ANIM chunk

src/ImageSharp/Compression/Zlib/ZlibInflateStream.cs, src/ImageSharp/Formats/Tiff/Ifd/DirectoryReader.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/External/ReferenceOutput/TiffDecoderTests/TiffDecoder_CanDecode_TiledWithBadZlib_tiled-0000023664.png, tests/Images/Input/Tiff/Issues/JpegCompressedGray-0000539558.tiff, tests/Images/Input/Tiff/Issues/tiled-0000023664.tiff
Adds additional checks to the decoder infrastructure to enable us to better handle corrupt files. 
Some light formatting cleanup also.
=> Tiff decoding robustness improvements

src/ImageSharp/Formats/ImageDecoderUtilities.cs, src/ImageSharp/Formats/Pbm/BinaryDecoder.cs, src/ImageSharp/Formats/Pbm/BufferedReadStreamExtensions.cs, src/ImageSharp/Formats/Pbm/PbmDecoderCore.cs, src/ImageSharp/Formats/Pbm/PlainDecoder.cs, src/ImageSharp/IO/BufferedReadStream.cs, tests/ImageSharp.Tests/Formats/Pbm/PbmDecoderTests.cs, tests/ImageSharp.Tests/Formats/Pbm/PbmMetadataTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/ImageSharp.Tests/TestUtilities/EofHitCounter.cs, tests/Images/Input/Pbm/00000_00000_premature_eof.ppm
Add additonal checks to handle corrupt files better in the PBM decoder.
Also extend `BufferedReadStream` to monitor the number of times it has been made to hit EOF by read calls. This improves the testability of decoder behavior. The perf impact of the `BufferedReadStream` change is [within the margin of error](https://gist.github.com/antonfirsov/456c748e5bf1dc52c41f1e416560e4f1).
=> PBM decoder robustness improvements and BufferedReadStream observability

src/ImageSharp/Memory/Allocators/UniformUnmanagedMemoryPoolMemoryAllocator.cs, tests/ImageSharp.Tests/Image/ImageTests.cs, tests/ImageSharp.Tests/Memory/Allocators/UniformUnmanagedPoolMemoryAllocatorTests.cs
Backport of #2545 to `release/2.1`.
=> [release/2.1] Disallow allocation attempts of unrepresentable sizes

src/ImageSharp/Formats/ImageDecoderUtilities.cs, src/ImageSharp/Formats/Pbm/BinaryDecoder.cs, src/ImageSharp/Formats/Pbm/BufferedReadStreamExtensions.cs, src/ImageSharp/Formats/Pbm/PbmDecoderCore.cs, src/ImageSharp/Formats/Pbm/PlainDecoder.cs, src/ImageSharp/IO/BufferedReadStream.cs, tests/ImageSharp.Tests/Formats/Pbm/PbmDecoderTests.cs, tests/ImageSharp.Tests/Formats/Pbm/PbmMetadataTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/ImageSharp.Tests/TestUtilities/EofHitCounter.cs, tests/Images/Input/Pbm/00000_00000_premature_eof.ppm
Backport of #2551 & #2552 to `release/2.1`.
=> [release/2.1] PBM decoder robustness improvements and BufferedReadStream observability

src/ImageSharp/Memory/Allocators/UniformUnmanagedMemoryPoolMemoryAllocator.cs, tests/ImageSharp.Tests/Image/ImageTests.cs, tests/ImageSharp.Tests/Memory/Allocators/UniformUnmanagedPoolMemoryAllocatorTests.cs
Backport of #2545 to `release/v3.0.x`. I created that branch by renaming `release/v3.0.2`.
=> [release/3.0] Disallow allocation attempts of unrepresentable sizes

src/ImageSharp/Formats/ImageDecoderUtilities.cs, src/ImageSharp/Formats/Pbm/BinaryDecoder.cs, src/ImageSharp/Formats/Pbm/BufferedReadStreamExtensions.cs, src/ImageSharp/Formats/Pbm/PbmDecoderCore.cs, src/ImageSharp/Formats/Pbm/PlainDecoder.cs, src/ImageSharp/IO/BufferedReadStream.cs, tests/ImageSharp.Tests/Formats/Pbm/PbmDecoderTests.cs, tests/ImageSharp.Tests/Formats/Pbm/PbmMetadataTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/ImageSharp.Tests/TestUtilities/EofHitCounter.cs, tests/Images/Input/Pbm/00000_00000_premature_eof.ppm
Backport of #2551 and #2552 to `release/v3.0.x`.
=> [release/3.0] PBM decoder robustness improvements and BufferedReadStream observability

src/ImageSharp/Compression/Zlib/ZlibInflateStream.cs, src/ImageSharp/Formats/Tiff/Ifd/DirectoryReader.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/External/ReferenceOutput/TiffDecoderTests/TiffDecoder_CanDecode_TiledWithBadZlib_tiled-0000023664.png, tests/Images/Input/Tiff/Issues/JpegCompressedGray-0000539558.tiff, tests/Images/Input/Tiff/Issues/tiled-0000023664.tiff
Backport of `#2550` to `release/v3.0.x`.
=> [release/3.0] Tiff decoding robustness improvements (#2550)

src/ImageSharp/Formats/Webp/Lossless/BackwardReferenceEncoder.cs, src/ImageSharp/Formats/Webp/Lossless/CostModel.cs, src/ImageSharp/Formats/Webp/Lossless/HistogramEncoder.cs, src/ImageSharp/Formats/Webp/Lossless/HuffmanUtils.cs, src/ImageSharp/Formats/Webp/Lossless/PixOrCopy.cs, src/ImageSharp/Formats/Webp/Lossless/Vp8LBitEntropy.cs, src/ImageSharp/Formats/Webp/Lossless/Vp8LEncoder.cs, src/ImageSharp/Formats/Webp/Lossless/Vp8LHistogram.cs, src/ImageSharp/Formats/Webp/Lossless/Vp8LHistogramSet.cs, tests/ImageSharp.Benchmarks/Codecs/Webp/EncodeWebp.cs, tests/ImageSharp.Tests/Formats/WebP/DominantCostRangeTests.cs, tests/ImageSharp.Tests/Formats/WebP/Vp8LHistogramTests.cs
This PR refactors the `Vp8LHistogram` type to use pooled allocations. It also introduces the concept of a `Vp8LHistogramSet` type to allow allocating a single buffer for a collection.
Benchmark indicates a 20ms speedup for lossless encoding while using less than half the original allocated memory.
```
BenchmarkDotNet=v0.13.0, OS=Windows 10.0.22621
11th Gen Intel Core i7-11370H 3.30GHz, 1 CPU, 8 logical and 4 physical cores
.NET SDK=8.0.100-rc.1.23455.8
[Host]     : .NET 6.0.22 (6.0.2223.42425), X64 RyuJIT
Job-ZADQXC : .NET 6.0.22 (6.0.2223.42425), X64 RyuJIT
Runtime=.NET 6.0  Arguments=/p:DebugType=portable  IterationCount=3
LaunchCount=1  WarmupCount=3
```
**Main**
|                     Method |    TestImage |      Mean |     Error |   StdDev | Ratio | RatioSD |     Gen 0 |     Gen 1 | …
=> WebP - Reduce the allocations in lossless encoding

src/ImageSharp/Formats/Tiff/TiffDecoderOptionsParser.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Tiff/Issues/Issue2587.tiff
Explicitly set BitsPerPixel and BitsPerSample to 1 for bicolor compressed images, fixes #2587
=> Explicitly set BitsPerPixel and BitsPerSample to 1 for bicolor compressed images

tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Jpg/issues/issue2517-bad-d7.jpg
Looks like this already works. Just added the test file for confirmation.
=> Confirm we can correctly decode jpegs with malformed D0-D7 chunks.

src/ImageSharp/Formats/Gif/GifEncoderCore.cs, src/ImageSharp/Formats/Gif/MetadataExtensions.cs, src/ImageSharp/Formats/Webp/BitReader/Vp8LBitReader.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Gif/18-bit_RGB_Cube.gif
@saucecontrol found me an image that broke the new encoder. We'd missed an edge case here when local palettes are 256 length. 
I'll update main once this is merged.
=> Handle dedup of local palette of 256 length

src/ImageSharp/Processing/Processors/Drawing/DrawImageProcessor{TPixelBg,TPixelFg}.cs, tests/ImageSharp.Tests/Drawing/DrawImageTests.cs, tests/Images/External/ReferenceOutput/Drawing/DrawImageTests/Issue2608_NegOffset.png
This fixes #2608 which incorrectly handles the a negative drawing target/background location when drawing an image, ensuing the correct portion of the foreground image is retained and never cropped incorrectly.
The foreground rectangle is supposed to be in the foreground images coordinate space where are the background location is in the background images coordinate space, so we need to offset the x, y by the amount we shrink it by when unifying them to determine the portion of the foreground we are interested in.
This still does not change the rules for the foregrounds rectangle as that should not  support a negative x,y but only effects the background/target location we will draw the final cropped foreground image to.
=> Correctly calculate foreground Rectangle when negative background location is set (3.1 fix)

src/ImageSharp/Processing/Processors/Drawing/DrawImageProcessor{TPixelBg,TPixelFg}.cs, tests/ImageSharp.Tests/Drawing/DrawImageTests.cs, tests/Images/External/ReferenceOutput/Drawing/DrawImageTests/Issue2603.png
Prevents the `ArgumentOutOfRangeException` when the area of interest of the foreground image will be drawn past the edge of the bounds of the background image.
fixes #2603 
related to #2609
Targeting 3.1 release branch
=> Handle case when Foreground image overhangs bottom of background image during DrawImage Call (3.1 target)

src/ImageSharp/Processing/Processors/Drawing/DrawImageProcessor{TPixelBg,TPixelFg}.cs, tests/ImageSharp.Tests/Drawing/DrawImageTests.cs, tests/Images/External/ReferenceOutput/Drawing/DrawImageTests/Issue2603.png, tests/Images/External/ReferenceOutput/Drawing/DrawImageTests/Issue2608_NegOffset.png
Sync `release/3.1.x` release branch with `main` bringing the 2 DrawImage fixes in. #2610 & #2609.
=> Sync 3.1 DrawImage fixes 

src/ImageSharp/Formats/Png/Filters/PaethFilter.cs, tests/ImageSharp.Tests/Formats/Png/PngDecoderFilterTests.cs
=> Fix Paeth Filter decode on platforms that do not support Ssse3

src/ImageSharp/Formats/Webp/WebpFormat.cs
I adjusted the casing the Webp format name. It is the only format that has a mixed case name. All other formats are in upper case. This helps eliminate the need for case insensitive matching of format names (which is not always possible).
=> Adjusted the casing of the Webp format name

src/ImageSharp/Formats/Webp/WebpFrameMetadata.cs
`Milliseconds` is the milli seconds component of the TimeSpan, `TotalMilliseconds` is the entire TimeSpan expressed as milliseconds.
Example, Timespan of 3.5 seconds:
* `Milliseconds`: 500
* `TotalMilliseconds`: 3500
Fixes #2619
=> Fix WebP animation speed bug

src/ImageSharp/Processing/Processors/Drawing/DrawImageProcessor{TPixelBg,TPixelFg}.cs
Moving the foreground image intersect to before the sanitation check ensures invalid arguments are not processed.
Fixes #2663 will duplicate for main following this fix.
=> Make DrawImage processor more robust to bad input.

src/ImageSharp/Formats/Png/PngDecoderCore.cs, tests/ImageSharp.Tests/Formats/Png/PngDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Png/issues/Issue_2666.png
Fixes #2666 
Will follow up fix in main following merge.
=> Don't skip reading data for animation chunks on identify. 

src/ImageSharp/Color/Color.cs, src/ImageSharp/Formats/Gif/GifFrameMetadata.cs, src/ImageSharp/Formats/Png/PngEncoderCore.cs, src/ImageSharp/Formats/Webp/AlphaDecoder.cs, tests/ImageSharp.Tests/Color/ColorTests.CastTo.cs, tests/ImageSharp.Tests/Formats/Png/PngEncoderTests.cs, tests/ImageSharp.Tests/Formats/WebP/WebpDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/External/ReferenceOutput/PngEncoderTests/Issue2668_Quantized_Encode_Alpha_Rgba32_Issue_2668.png, tests/Images/Input/Png/issues/Issue_2668.png, tests/Images/Input/Webp/issues/Issue2670.webp
Add fixes #2668 #2676 #2677 to main. Also fixes some API quirks in Color to match IPixel.
=> Add fixes 2668, 2676, and 2677 to main

src/ImageSharp/Formats/Png/PngDecoderCore.cs, src/ImageSharp/Formats/Png/PngDecoderOptions.cs, tests/ImageSharp.Tests/Formats/Png/PngDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Png/issues/bad-ztxt.png, tests/Images/Input/Png/issues/bad-ztxt2.png
Adds a configurable value limiting the size of uncompressed buffers in ancillary PNG chunks.
=> Limit ancillary PNG chunk size.

src/Directory.Build.props, src/ImageSharp/Formats/Png/PngDecoderCore.cs, src/ImageSharp/ImageSharp.csproj
=> Backport 2681

.github/workflows/build-and-test.yml, src/ImageSharp/Formats/Png/PngDecoderCore.cs, src/ImageSharp/Formats/Png/PngDecoderOptions.cs, src/ImageSharp/Formats/Webp/AlphaDecoder.cs, tests/ImageSharp.Tests/Formats/Png/PngDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Png/issues/bad-ztxt.png, tests/Images/Input/Png/issues/bad-ztxt2.png
Adds #2681 to Main. Also adds Arm64 support for #2676
=> Merge 2681 to v4 Main

src/ImageSharp/Formats/Jpeg/Components/Decoder/JpegBitReader.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Jpg/issues/Issue2638.jpg
Fixes #2638 
Updates the `JpegBitReader` to only exit after we've hit the end of the file multiple times. This ensures that we do not skip over the last MCU.
cc @br3aker
=> Only exit JPEG scan decoding after multiple EOF hits

src/ImageSharp/Formats/Jpeg/Components/Decoder/JpegBitReader.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Jpg/issues/Issue2638.jpg
=> Backport - Only exit JPEG scan decoding after multiple EOF hits

src/ImageSharp/Common/Helpers/RiffHelper.cs, src/ImageSharp/Formats/Webp/BitWriter/BitWriterBase.cs, src/ImageSharp/Formats/Webp/Chunks/WebpVp8X.cs, src/ImageSharp/Formats/Webp/Lossless/Vp8LEncoder.cs, src/ImageSharp/Formats/Webp/Lossy/Vp8Encoder.cs, src/ImageSharp/Formats/Webp/WebpChunkParsingUtils.cs, src/ImageSharp/Formats/Webp/WebpDecoderCore.cs, src/ImageSharp/Formats/Webp/WebpEncoderCore.cs
When encoding webp image using the [extended format](https://developers.google.com/speed/webp/docs/riff_container#extended_file_format) we must ensure that the VP8X chunk contains the correct alpha flags in order to correctly display alpha color.
Fixes #2692 and https://github.com/SixLabors/ImageSharp/issues/2528#issuecomment-1993901348
=> Ensure VP8X alpha flag is updated correctly.

src/ImageSharp/Formats/Webp/BitWriter/BitWriterBase.cs, src/ImageSharp/Formats/Webp/Chunks/WebpVp8X.cs, src/ImageSharp/Formats/Webp/Lossless/Vp8LEncoder.cs, src/ImageSharp/Formats/Webp/Lossy/Vp8Encoder.cs, src/ImageSharp/Formats/Webp/RiffHelper.cs, src/ImageSharp/Formats/Webp/WebpChunkParsingUtils.cs, src/ImageSharp/Formats/Webp/WebpDecoderCore.cs, src/ImageSharp/Formats/Webp/WebpEncoderCore.cs
V4 Version of #2699 
When encoding webp image using the [extended format](https://developers.google.com/speed/webp/docs/riff_container#extended_file_format) we must ensure that the VP8X chunk contains the correct alpha flags in order to correctly display alpha color.
Fixes https://github.com/SixLabors/ImageSharp/issues/2692 and https://github.com/SixLabors/ImageSharp/issues/2528#issuecomment-1993901348
=> V4 Ensure VP8X alpha flag is updated correctly. 

src/ImageSharp/Formats/Png/PngDecoderCore.cs, src/ImageSharp/Formats/Png/PngEncoderCore.cs, src/ImageSharp/Formats/Png/PngMetadata.cs, src/ImageSharp/Formats/Png/PngScanlineProcessor.cs, tests/ImageSharp.Tests/Formats/Png/PngDecoderTests.cs, tests/ImageSharp.Tests/Formats/Png/PngEncoderTests.Chunks.cs, tests/ImageSharp.Tests/Formats/Png/PngEncoderTests.cs, tests/ImageSharp.Tests/Formats/Png/PngMetadataTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/External/ReferenceOutput/PngDecoderTests/Decode_VerifyAllFrames_Rgba32_default-not-animated.png/00.png, tests/Images/External/ReferenceOutput/PngDecoderTests/Decode_VerifyAllFrames_Rgba32_default-not-animated.png/01.png, tests/Images/External/ReferenceOutput/PngDecoderTests/Decode_VerifyAllFrames_Rgba32_frame-offset.png/00.png, tests/Images/External/ReferenceOutput/PngDecoderTests/Decode_VerifyAllFrames_Rgba32_frame-offset.png/01.png, tests/Images/External/ReferenceOutput/PngDecoderTests/Decode_VerifyAllFrames_Rgba32_frame-offset.png/02.png, tests/Images/External/ReferenceOutput/PngDecoderTests/Decode_VerifyAllFrames_Rgba32_frame-offset.png/03.png, tests/Images/External/ReferenceOutput/PngDecoderTests/Decode_VerifyAllFrames_Rgba32_frame-offset.png/04.png, tests/Images/Input/Png/animated/default-not-animated.png, tests/Images/Input/Png/animated/frame-offset.png
Identified and fixed the issues mentioned in issue #2708.
Fix: ProcessInterlacedPaletteScanline now respects frameControl.XOffset
Fix: PngDecoderCore handling of PngDisposalMethod.RestoreToBackground and RestoreToPrevious, for specification compliance.
Metadata change: Added DefaultImageAnimated to PngMetadata. The apng format allows for the first frame to not be part of the animation sequence, which needs to be visible to users.
Fix: Decoding and encoding when the default image is not animated
=> Fix animated png handling (issue #2708)

src/ImageSharp/Formats/Png/PngScanlineProcessor.cs, tests/ImageSharp.Tests/Formats/Png/PngDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Png/issues/Issue_2714.png
Limit palette indices when reading indexed PNG files. Fixes #2714
=> Limit Read Palette Indices

src/ImageSharp/Formats/Png/PngScanlineProcessor.cs, tests/ImageSharp.Tests/Formats/Png/PngDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Png/issues/Issue_2714.png
=> V2 - Limit Read Palette Indices

src/ImageSharp/Formats/Jpeg/Components/Decoder/SpectralConverter{TPixel}.cs, src/ImageSharp/Formats/Tga/TgaDecoderCore.cs
=> V2 - Clear Pixel Buffers on Decode.

src/ImageSharp/Formats/Jpeg/Components/Decoder/SpectralConverter{TPixel}.cs, src/ImageSharp/Formats/Tga/TgaDecoderCore.cs
Ensure that all decoders clear the pixel buffer on allocation.
=> Clear Pixel Buffers on Decode.

src/ImageSharp/Formats/Png/PngDecoderCore.cs, src/ImageSharp/Memory/Allocators/Internals/UnmanagedMemoryHandle.cs, src/ImageSharp/Memory/Allocators/MemoryAllocator.cs, src/ImageSharp/Memory/Allocators/MemoryAllocatorOptions.cs, src/ImageSharp/Memory/Allocators/SimpleGcMemoryAllocator.cs, src/ImageSharp/Memory/Allocators/UniformUnmanagedMemoryPoolMemoryAllocator.cs, src/ImageSharp/Memory/DiscontiguousBuffers/MemoryGroup{T}.cs, src/ImageSharp/Memory/InvalidMemoryOperationException.cs, tests/ImageSharp.Tests/Formats/Bmp/BmpDecoderTests.cs, tests/ImageSharp.Tests/Memory/Allocators/SimpleGcMemoryAllocatorTests.cs, tests/ImageSharp.Tests/Memory/Allocators/UniformUnmanagedPoolMemoryAllocatorTests.cs, tests/ImageSharp.Tests/Memory/Buffer2DTests.cs, tests/ImageSharp.Tests/Memory/DiscontiguousBuffers/MemoryGroupTests.Allocate.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Bmp/issue-2696.bmp
=> V2 - Limit all memory allocations in the MemoryAllocator layer 

src/ImageSharp/Formats/Jpeg/Components/Decoder/SpectralConverter{TPixel}.cs, src/ImageSharp/Formats/Png/PngDecoderCore.cs, src/ImageSharp/Formats/Png/PngScanlineProcessor.cs, src/ImageSharp/Formats/Tga/TgaDecoderCore.cs, src/ImageSharp/Memory/Allocators/Internals/UnmanagedMemoryHandle.cs, src/ImageSharp/Memory/Allocators/MemoryAllocator.cs, src/ImageSharp/Memory/Allocators/MemoryAllocatorOptions.cs, src/ImageSharp/Memory/Allocators/SimpleGcMemoryAllocator.cs, src/ImageSharp/Memory/Allocators/UniformUnmanagedMemoryPoolMemoryAllocator.cs, src/ImageSharp/Memory/DiscontiguousBuffers/MemoryGroup{T}.cs, src/ImageSharp/Memory/InvalidMemoryOperationException.cs, tests/ImageSharp.Tests/Formats/Bmp/BmpDecoderTests.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.cs, tests/ImageSharp.Tests/Formats/Png/PngDecoderTests.cs, tests/ImageSharp.Tests/Memory/Allocators/SimpleGcMemoryAllocatorTests.cs, tests/ImageSharp.Tests/Memory/Allocators/UniformUnmanagedPoolMemoryAllocatorTests.cs, tests/ImageSharp.Tests/Memory/Buffer2DTests.cs, tests/ImageSharp.Tests/Memory/DiscontiguousBuffers/MemoryGroupTests.Allocate.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Bmp/issue-2696.bmp, tests/Images/Input/Png/issues/Issue_2714.png
Adds fixes for #2696  #2706  #2718
=> Merge latest release from v3

.github/workflows/build-and-test.yml, tests/ImageSharp.Tests/TestFormat.cs
~Dummy PR to run against `macos-latest` on CI.~
As noted in https://github.com/SixLabors/ImageSharp/pull/2728#issuecomment-2078083691, we need to use `macos-13` to get the tests running.
In long term we need to migrate away from using `System.Drawing.Common` reference implementations, at least on Mac.
=> Fix MacOS jobs

src/ImageSharp/Image.Decode.cs, src/ImageSharp/Image.FromStream.cs
While investigating recent instability in our production server environment, we discovered another code path within the async image loading code that would result in a blocking, synchronous stream read, which on our servers was leading to threadpool exhaustion.  This change adds a proper asynchronous variant of the offending code so that the stream reading triggered by `Image.DecodeAsync()` executes asynchronously.
=> Fix async-over-sync issue in Image.DecodeAsync()

src/ImageSharp/Memory/Allocators/MemoryAllocator.cs, tests/ImageSharp.Tests/Memory/Allocators/UniformUnmanagedPoolMemoryAllocatorTests.cs
Fix an overlook from #2706. See https://github.com/SixLabors/ImageSharp/commit/92b82779ac8e7a032989533bb9a01ef092186b2e#r141770676.
=> Fix overflow in MemoryAllocator.Create(options)

src/ImageSharp/Memory/Allocators/MemoryAllocator.cs, tests/ImageSharp.Tests/Memory/Allocators/UniformUnmanagedPoolMemoryAllocatorTests.cs
Backport of #2730 to `release/3.1.x`
=> [3.1] Fix overflow in MemoryAllocator.Create(options)

.github/workflows/build-and-test.yml, src/ImageSharp/Memory/Allocators/MemoryAllocator.cs, tests/ImageSharp.Tests/Memory/Allocators/UniformUnmanagedPoolMemoryAllocatorTests.cs
Backport of #2730 to `release/2.1.x`
=> [2.1] Fix overflow in MemoryAllocator.Create(options)

src/ImageSharp/Formats/Gif/GifDecoderCore.cs, src/ImageSharp/Formats/Gif/LzwDecoder.cs, tests/ImageSharp.Tests/Formats/Gif/GifDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/External/ReferenceOutput/GifDecoderTests/Issue2012BadMinCode_Rgba32_issue2012_drona1.png, tests/Images/External/ReferenceOutput/GifDecoderTests/IssueTooLargeLzwBits_Rgba32_issue_2743.gif/00.png, tests/Images/External/ReferenceOutput/GifDecoderTests/IssueTooLargeLzwBits_Rgba32_issue_2743.gif/01.png, tests/Images/External/ReferenceOutput/GifDecoderTests/IssueTooLargeLzwBits_Rgba32_issue_2743.gif/02.png, tests/Images/External/ReferenceOutput/GifDecoderTests/IssueTooLargeLzwBits_Rgba32_issue_2743.gif/03.png, tests/Images/External/ReferenceOutput/GifDecoderTests/IssueTooLargeLzwBits_Rgba32_issue_2743.gif/04.png, tests/Images/External/ReferenceOutput/GifDecoderTests/IssueTooLargeLzwBits_Rgba32_issue_2743.gif/05.png, tests/Images/External/ReferenceOutput/GifDecoderTests/IssueTooLargeLzwBits_Rgba32_issue_2743.gif/06.png, tests/Images/External/ReferenceOutput/GifDecoderTests/IssueTooLargeLzwBits_Rgba32_issue_2743.gif/07.png, tests/Images/Input/Gif/issues/issue_2743.gif
The image provided in #2743 has some invalid lzwCode length. This PR changes the gif lzw decoder to raise an exception when the lzwCode is larger then 12 Bits.
=> GifDecoder: Limit lzw bits to a maximum of 12 bits

src/ImageSharp/Formats/Gif/LzwDecoder.cs, tests/ImageSharp.Tests/Formats/Gif/GifMetadataTests.cs
Follow up to #2744 that changes the behavior to skip bad min/max codes. Fixes #2743
=> GifDecoder : Allow skipping bad metadata using identify

src/ImageSharp/Formats/Gif/LzwDecoder.cs, tests/ImageSharp.Tests/Formats/Gif/GifDecoderTests.cs, tests/ImageSharp.Tests/Formats/Gif/GifMetadataTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/External/ReferenceOutput/GifDecoderTests/Issue2012BadMinCode_Rgba32_issue2012_drona1.png, tests/Images/External/ReferenceOutput/GifDecoderTests/IssueTooLargeLzwBits_Rgba32_issue_2743.gif/00.png, tests/Images/External/ReferenceOutput/GifDecoderTests/IssueTooLargeLzwBits_Rgba32_issue_2743.gif/01.png, tests/Images/External/ReferenceOutput/GifDecoderTests/IssueTooLargeLzwBits_Rgba32_issue_2743.gif/02.png, tests/Images/External/ReferenceOutput/GifDecoderTests/IssueTooLargeLzwBits_Rgba32_issue_2743.gif/03.png, tests/Images/External/ReferenceOutput/GifDecoderTests/IssueTooLargeLzwBits_Rgba32_issue_2743.gif/04.png, tests/Images/External/ReferenceOutput/GifDecoderTests/IssueTooLargeLzwBits_Rgba32_issue_2743.gif/05.png, tests/Images/External/ReferenceOutput/GifDecoderTests/IssueTooLargeLzwBits_Rgba32_issue_2743.gif/06.png, tests/Images/External/ReferenceOutput/GifDecoderTests/IssueTooLargeLzwBits_Rgba32_issue_2743.gif/07.png, tests/Images/Input/Gif/issues/issue_2743.gif
Backport of #2744 #2749 for v3.1.x
=> v3 - Backport. Handle out of bounds Gif LZW max code

src/ImageSharp/Formats/Gif/LzwDecoder.cs, tests/ImageSharp.Tests/Formats/Gif/GifDecoderTests.cs, tests/ImageSharp.Tests/Formats/Gif/GifMetadataTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/External/ReferenceOutput/GifDecoderTests/Issue2012BadMinCode_Rgba32_issue2012_drona1.png, tests/Images/External/ReferenceOutput/GifDecoderTests/IssueTooLargeLzwBits_Rgba32_issue_2743.gif/00.png, tests/Images/External/ReferenceOutput/GifDecoderTests/IssueTooLargeLzwBits_Rgba32_issue_2743.gif/01.png, tests/Images/External/ReferenceOutput/GifDecoderTests/IssueTooLargeLzwBits_Rgba32_issue_2743.gif/02.png, tests/Images/External/ReferenceOutput/GifDecoderTests/IssueTooLargeLzwBits_Rgba32_issue_2743.gif/03.png, tests/Images/External/ReferenceOutput/GifDecoderTests/IssueTooLargeLzwBits_Rgba32_issue_2743.gif/04.png, tests/Images/External/ReferenceOutput/GifDecoderTests/IssueTooLargeLzwBits_Rgba32_issue_2743.gif/05.png, tests/Images/External/ReferenceOutput/GifDecoderTests/IssueTooLargeLzwBits_Rgba32_issue_2743.gif/06.png, tests/Images/External/ReferenceOutput/GifDecoderTests/IssueTooLargeLzwBits_Rgba32_issue_2743.gif/07.png, tests/Images/Input/Gif/issues/issue_2743.gif
This is a backport of #2754 to 2.1.x.
=> Backport GIF LZW fix to 2.1

src/ImageSharp/Formats/Webp/Lossless/Vp8LEncoder.cs, src/ImageSharp/Formats/Webp/WebpChunkParsingUtils.cs, tests/ImageSharp.Tests/Formats/WebP/WebpEncoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Webp/issues/Issue2763.png
Backport of #2767 
Also contains a fix for #2692
=> v3.1.x - Backport Webp: Fix Issue 2763/2692

src/ImageSharp/Formats/Gif/GifDecoder.cs, src/ImageSharp/Formats/Gif/GifDecoderCore.cs, src/ImageSharp/Formats/Gif/GifThrowHelper.cs, src/ImageSharp/Formats/Gif/IGifDecoderOptions.cs, src/ImageSharp/Formats/Gif/LzwDecoder.cs, src/ImageSharp/Formats/Jpeg/Components/Quantization.cs, tests/ImageSharp.Tests/Formats/Gif/GifDecoderTests.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.Metadata.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/External/ReferenceOutput/GifDecoderTests/Issue2012BadMinCode_Rgba32_issue2012_drona1.png, tests/Images/External/ReferenceOutput/GifDecoderTests/Issue2758_BadDescriptorDimensions_Rgba32_issue_2758.gif/00.png, tests/Images/External/ReferenceOutput/GifDecoderTests/Issue2758_BadDescriptorDimensions_Rgba32_issue_2758.gif/01.png, tests/Images/External/ReferenceOutput/GifDecoderTests/IssueTooLargeLzwBits_Rgba32_issue_2743.gif/07.png, tests/Images/Input/Gif/issues/issue_2758.gif, tests/Images/Input/Jpg/issues/issue-2758.jpg
Implemented it by a full port of 3.1.x Gif Decoder, so it contains improvements and behavioral changes made since then. It also decodes some stuff 2.1 API doesn't expose.
I didn't fully understand what was the JPEG change about, but the 2.1 decoder detects it as an invalid image. Added the test as a skipped test.
=> Backport 2759 to 2.1.x

src/ImageSharp/Formats/Png/PngDecoderCore.cs, tests/ImageSharp.Tests/Formats/Png/PngDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Png/issues/Issue_2752.png
Fixes #2752 
We weren't breaking from the loop only the nested switch. We were also missing a chunk break. The first `fcTL` chunk in a PNG is followed by one or more `IDAT` chunk, only subsequent `fcTL` chunks are followed by `fdAT` chunks.
The test image contains the following chunks. 
```
IHDR, pHYs, acTL, fcTL, IDAT ×3, fcTL, fdAT, fdAT, fcTL, fdAT, fdAT, fdAT, fcTL, fdAT, fdAT, fdAT, fcTL, fdAT, fdAT, fdAT, fcTL, fdAT,
fdAT, fdAT, fcTL, fdAT, fdAT, fdAT, fcTL, fdAT, fdAT, fdAT, fcTL, fdAT, fdAT, fdAT, fcTL, fdAT, fdAT, fdAT, fcTL, fdAT, fdAT, fdAT, fcTL, 
fdAT, fdAT, fdAT, fcTL, fdAT, fdAT, fdAT, fcTL, fdAT, fdAT, fdAT, fcTL, fdAT, fdAT, fdAT, fcTL, fdAT, fdAT, fdAT, fcTL, fdAT, fdAT, fdAT,
fcTL, fdAT, fdAT, fcTL, fdAT, fdAT, fcTL, fdAT, fdAT, fdAT, fcTL, fdAT, fdAT, fdAT, fcTL, fdAT, …
```
=> Correctly break during Png decoding

src/ImageSharp/Formats/Png/PngDecoderCore.cs, src/ImageSharp/Formats/Webp/WebpChunkParsingUtils.cs, tests/ImageSharp.Tests/Formats/Png/PngDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Png/issues/Issue_2752.png
=> V4 Correctly break during Png decoding

src/ImageSharp/Formats/Png/Filters/AverageFilter.cs, src/ImageSharp/Formats/Png/Filters/SubFilter.cs, src/ImageSharp/Formats/Png/Filters/UpFilter.cs, src/ImageSharp/Formats/Png/PngEncoderCore.cs
Fixes #2771 where the filter method was ignored when encoding PNGs. Also fixes a SIMD accelerated unsigned integer overflow defect in several of the filters which was masked by this issue.
=> Fix filtering on PNG encode.

src/ImageSharp/Image.WrapMemory.cs, tests/ImageSharp.Tests/Image/ImageTests.WrapMemory.cs
Fix #2779 by accounting pixel size. Also fixed some `width*height` multuplication overflows:
```csharp
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;
Rgba64[] data = new Rgba64[65536];
using Image<Rgba64> img = Image.WrapMemory<Rgba64>(data, 65537, 65536);
// doesn't throw here but will blow up later
// ...here for example
img.SaveAsPng("output.png");
```
=> Fix #2779 buffer overrun

src/ImageSharp/Metadata/ImageMetadata.cs
Fixes a typo in `ImageMetadata` docs which bugged me, no big deal.
=> Fix ImageMetadata docs typo

src/ImageSharp/Formats/Bmp/BmpEncoderCore.cs
=> Fix using dither in BmpEncoder when bit per pixel is <= 4

src/ImageSharp/Image.WrapMemory.cs, tests/ImageSharp.Tests/Image/ImageTests.WrapMemory.cs
=> Backport : V3 Fix #2779 buffer overrun

src/ImageSharp/Formats/Webp/AlphaDecoder.cs, src/ImageSharp/Formats/Webp/Lossless/LosslessUtils.cs, src/ImageSharp/Formats/Webp/Lossless/WebpLosslessDecoder.cs, tests/ImageSharp.Tests/Formats/WebP/WebpEncoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Webp/issues/Issue2801.webp
=> Backport - v3 WEBP : Use Correct Width With AlphaDecoder

src/ImageSharp/Formats/Webp/AlphaDecoder.cs, src/ImageSharp/Formats/Webp/Lossless/LosslessUtils.cs, src/ImageSharp/Formats/Webp/Lossless/WebpLosslessDecoder.cs, tests/ImageSharp.Tests/Formats/WebP/WebpEncoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Webp/issues/Issue2801.webp
Fixes #2801 
The Alpha decoder was using the incorrect width. Updated and copied the comment from the original code. I also moved an allocation to our memory allocator.
=> WEBP : Use Correct Width With AlphaDecoder 

src/ImageSharp/Formats/ImageEncoder.cs, src/ImageSharp/IO/ChunkedMemoryStream.cs, tests/ImageSharp.Tests/Formats/WebP/WebpEncoderTests.cs, tests/ImageSharp.Tests/IO/ChunkedMemoryStreamTests.cs, tests/ImageSharp.Tests/Image/NonSeekableStream.cs
#2828 but for v4. No additional changes.
=> V4 : Rewrite ChunkedMemoryStream 

src/ImageSharp/Processing/Extensions/Convolution/BokehBlurExtensions.cs, src/ImageSharp/Processing/Extensions/Convolution/BoxBlurExtensions.cs, src/ImageSharp/Processing/Extensions/Convolution/ConvolutionExtensions.cs, src/ImageSharp/Processing/Extensions/Convolution/DetectEdgesExtensions.cs, src/ImageSharp/Processing/Extensions/Convolution/GaussianBlurExtensions.cs, src/ImageSharp/Processing/Extensions/Convolution/GaussianSharpenExtensions.cs, src/ImageSharp/Processing/Extensions/Convolution/MedianBlurExtensions.cs, src/ImageSharp/Processing/Processors/Convolution/Convolution2DProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Convolution/Convolution2PassProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Convolution/ConvolutionProcessor.cs, src/ImageSharp/Processing/Processors/Convolution/ConvolutionProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Convolution/EdgeDetectorCompassProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Convolution/EdgeDetectorProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Convolution/GaussianBlurProcessor{TPixel}.cs, src/ImageSharp/Processing/Processors/Convolution/GaussianSharpenProcessor{TPixel}.cs, tests/ImageSharp.Tests/Processing/Convolution/DetectEdgesTest.cs, tests/ImageSharp.Tests/Processing/Convolution/GaussianBlurTest.cs, tests/ImageSharp.Tests/Processing/Convolution/GaussianSharpenTest.cs, tests/ImageSharp.Tests/Processing/Convolution/MedianBlurTest.cs, tests/ImageSharp.Tests/Processing/Processors/Convolution/BokehBlurTest.cs, tests/ImageSharp.Tests/Processing/Processors/Convolution/ConvolutionTests.cs, tests/ImageSharp.Tests/Processing/Processors/Convolution/GaussianBlurTest.cs, tests/ImageSharp.Tests/Processing/Processors/Convolution/GaussianSharpenTest.cs, tests/ImageSharp.Tests/Processing/Processors/Convolution/MedianBlurTest.cs, tests/Images/External/ReferenceOutput/Convolution/ConvolutionTests/InBox_Rgba32_CalliphoraPartial_-1_-1_-1_-1_16_-1_-1_-1_-1.png, tests/Images/External/ReferenceOutput/Convolution/ConvolutionTests/InBox_Rgba32_Car_-1_-1_-1_-1_16_-1_-1_-1_-1.png, tests/Images/External/ReferenceOutput/Convolution/ConvolutionTests/InBox_Rgba32_blur_-1_-1_-1_-1_16_-1_-1_-1_-1.png, tests/Images/External/ReferenceOutput/Convolution/ConvolutionTests/OnFullImage_Rgba32_CalliphoraPartial_-1_-1_-1_-1_16_-1_-1_-1_-1.png, tests/Images/External/ReferenceOutput/Convolution/ConvolutionTests/OnFullImage_Rgba32_Car_-1_-1_-1_-1_16_-1_-1_-1_-1.png, tests/Images/External/ReferenceOutput/Convolution/ConvolutionTests/OnFullImage_Rgba32_blur_-1_-1_-1_-1_16_-1_-1_-1_-1.png
See the roadmap discussion at https://github.com/SixLabors/ImageSharp/discussions/2533
Adds a general convolution API that accepts a `DenseMatrix<float>` to describe the convolution kernel. 
All this stuff has been the plumbing for various processors over the years and should be exposed publicly now it's solid.
=> Expose Convolution Api

src/ImageSharp/Formats/Gif/GifDecoderCore.cs, tests/ImageSharp.Benchmarks/Codecs/Gif/DecodeGif.cs
Originally wanted to straightly PR the idea in #2850, but felt like we need to do something about the high amount of unsafe code in `GifDecoderCore` before touching anything there. By simply removing Unsafe, I noticed a minor perf drop. I managed compensate it by changing the inner loops so the JIT can remove bounds checks at least for one of the spans.
```
BenchmarkDotNet v0.14.0, Windows 11 (10.0.22631.4602/23H2/2023Update/SunValley3)
12th Gen Intel Core i7-1280P, 1 CPU, 20 logical and 14 physical cores
.NET SDK 9.0.100
[Host]     : .NET 8.0.11 (8.0.1124.51707), X64 RyuJIT AVX2
Job-JOLLXK : .NET 8.0.11 (8.0.1124.51707), X64 RyuJIT AVX2
Runtime=.NET 8.0  Arguments=/p:DebugType=portable  IterationCount=3
LaunchCount=1  WarmupCount=3
//// main ////
| Method               | TestImage      | …
```
=> Remove Unsafe usage from `GifDecoderCore` and optimize loops

.github/workflows/build-and-test.yml, .github/workflows/code-coverage.yml, ci-build.ps1, src/ImageSharp/Formats/Png/PngThrowHelper.cs, src/ImageSharp/Formats/Tiff/TiffDecoderCore.cs
Fixes #2873
Avoids the integer overflow issue by removing the interim allocation completely and decoding directly to the pixel buffer.
=> V3 : Decode Chunky Tile Rows Directly.

src/ImageSharp/Formats/Png/PngThrowHelper.cs, src/ImageSharp/Formats/Tiff/TiffDecoderCore.cs
=> V4 : Decode Chunky Tile Rows Directly. 

.github/workflows/build-and-test.yml, src/ImageSharp/Formats/Gif/LzwDecoder.cs, tests/ImageSharp.Tests/Formats/Gif/GifDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/External/ReferenceOutput/GifDecoderTests/Issue2859_LZWPixelStackOverflow_Rgba32_issue_2859_A.gif/00.png, tests/Images/External/ReferenceOutput/GifDecoderTests/Issue2859_LZWPixelStackOverflow_Rgba32_issue_2859_B.gif/00.png, tests/Images/External/ReferenceOutput/GifDecoderTests/Issue2859_LZWPixelStackOverflow_Rgba32_issue_2859_B.gif/01.png, tests/Images/Input/Gif/issues/issue_2859_A.gif, tests/Images/Input/Gif/issues/issue_2859_B.gif
The issue is caused by using the full capacity of the pixel stack for intermediate pushes without reserving a slot for the final push, which leads to an overflow. By capping out the max index we can skip corrupt blocks. 
Fixes #2859
=> V3: Gracefully handle LZW overflows

src/ImageSharp/Formats/Gif/LzwDecoder.cs, tests/ImageSharp.Tests/Formats/Gif/GifDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/External/ReferenceOutput/GifDecoderTests/Issue2859_LZWPixelStackOverflow_Rgba32_issue_2859_A.gif/00.png, tests/Images/External/ReferenceOutput/GifDecoderTests/Issue2859_LZWPixelStackOverflow_Rgba32_issue_2859_B.gif/00.png, tests/Images/External/ReferenceOutput/GifDecoderTests/Issue2859_LZWPixelStackOverflow_Rgba32_issue_2859_B.gif/01.png, tests/Images/Input/Gif/issues/issue_2859_A.gif, tests/Images/Input/Gif/issues/issue_2859_B.gif
The same as #2880 but for V4. 
@antonfirsov You'll like the benchmark. .NET 8 is flying!
```
BenchmarkDotNet v0.14.0, Windows 11 (10.0.26100.3037)
11th Gen Intel Core i7-11370H 3.30GHz, 1 CPU, 8 logical and 4 physical cores
.NET SDK 9.0.200-preview.0.25057.12
[Host]     : .NET 8.0.12 (8.0.1224.60305), X64 RyuJIT AVX-512F+CD+BW+DQ+VL+VBMI
Job-TWXXIM : .NET 8.0.12 (8.0.1224.60305), X64 RyuJIT AVX-512F+CD+BW+DQ+VL+VBMI
Runtime=.NET 8.0  Arguments=/p:DebugType=portable  IterationCount=3
LaunchCount=1  WarmupCount=3
```
| Method               | TestImage     | Mean     | Error    | StdDev  | Ratio | RatioSD | Gen0   | Allocated | Alloc Ratio |
|--------------------- |-------------- |---------:|---------:|--------:|------:|--------:|-------:|----------:|------------:|
| 'System.Drawing Gif' | …
=> V4: Gracefully handle LZW overflows

.gitattributes, .github/workflows/build-and-test.yml, src/ImageSharp/Formats/Gif/LzwDecoder.cs, tests/ImageSharp.Tests/Formats/Bmp/BmpDecoderTests.cs, tests/ImageSharp.Tests/Formats/Gif/GifDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/External/ReferenceOutput/GifDecoderTests/Issue2859_LZWPixelStackOverflow_Rgba32_issue_2859_A.gif/00.png, tests/Images/External/ReferenceOutput/GifDecoderTests/Issue2859_LZWPixelStackOverflow_Rgba32_issue_2859_B.gif/00.png, tests/Images/External/ReferenceOutput/GifDecoderTests/Issue2859_LZWPixelStackOverflow_Rgba32_issue_2859_B.gif/01.png, tests/Images/Input/Gif/issues/issue_2859_A.gif, tests/Images/Input/Gif/issues/issue_2859_B.gif
Backport #2859 to release/2.1.x
=> Backport #2859 to release/2.1.x

src/ImageSharp/Formats/Jpeg/Components/Decoder/HuffmanScanBuffer.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Jpg/issues/Issue2638.jpg
Copy of #2868, but without the yaml changes.
=> Backport #2701 to 2.1.x [copy]

src/ImageSharp/Formats/Webp/BitWriter/Vp8BitWriter.cs
This change enhances memory efficiency by reducing heap allocations and leveraging stack allocation for better performance.
=> Refactor buffer allocation in Vp8BitWriter.cs to use Span<byte> instead of byte[] in WriteFrameHeader

src/ImageSharp/Metadata/Profiles/Exif/ExifReader.cs, tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.Metadata.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Jpg/issues/issue-2857-subsub-ifds.jpg
=> V3 Nested sub ifds parsing fix 

src/ImageSharp/Formats/Bmp/BmpDecoderCore.cs
=> Fix #2907. BMP indexed palette parsed wrong

src/ImageSharp/Formats/Tiff/TiffEncoderCore.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffEncoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Tiff/Issues/Issue2909.tiff
Uses the computed `BitsPerPixel` from the color writer instance for the compressor to ensure parity.
Fixes #2909
=> V3 - Use BPP from Color Writer for Compressor

src/ImageSharp/Formats/Png/PngDecoderCore.cs, tests/ImageSharp.Tests/Formats/Png/PngDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/External/ReferenceOutput/PngDecoderTests/CanDecode_Issue2924_Rgba32_Issue_2924.png, tests/Images/Input/Png/issues/Issue_2924.png
Fixes #2924 
With the update to the chunk identification code in v3.1.8, now detects an invalid iDAT chunk containing 6 bytes of data immediately following the correct and complete data. validation code throws an exception in cases, as this information is considered critical.
The revised behavior now ensures an early return when an issue with zLib data arises after the complete decoding of pixel data.
=> Do not attempt to decode iDAT chunks when image is fully decoded.

.github/workflows/build-and-test.yml, .github/workflows/code-coverage.yml, src/ImageSharp/Formats/Webp/WebpDecoderCore.cs, tests/ImageSharp.Tests/Formats/WebP/WebpDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Webp/issues/Issue2925.webp
=> V3 - Do not throw exception for non-required chunks.

tests/ImageSharp.Tests/TestUtilities/TestImageExtensions.cs
Our code coverage CI build was failing due to an introduced reliance on `DebugSaveXX` working correctly in all build environments. 
Since we no longer run the coverage tests against PRs directly it's best just to remove the condition.
=> Fix Code Coverage Tests

src/ImageSharp/Formats/Jpeg/JpegEncoderCore.cs, src/ImageSharp/Formats/Webp/Lossless/Vp8LEncoder.cs, src/ImageSharp/Formats/Webp/WebpEncoderCore.cs, src/ImageSharp/Formats/Webp/WebpThrowHelper.cs
=> V3: Do not encode WEBP images exceeding max dimensions

src/ImageSharp/IO/BufferedReadStream.cs, src/ImageSharp/IO/ChunkedMemoryStream.cs
* While checking ChunkedMemoryStream i saw differences in the Seek method of BufferedReadStream
=> Fix Typo and Offset in BufferedReadStream

src/ImageSharp/Metadata/Profiles/Exif/Tags/ExifTagValue.cs
=> V3:  Remove ExifTagValue.InteroperabilityIndex 

src/ImageSharp/Formats/Tiff/TiffDecoderOptionsParser.cs, src/ImageSharp/Formats/Tiff/TiffExtraSampleType.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Tiff/Issues/ExtraSamplesUnspecified.tif
=> V3 TIFF : Allow additional and undefined extra samples

src/ImageSharp/Metadata/Profiles/Exif/ExifEncodedStringHelpers.cs, src/ImageSharp/Metadata/Profiles/Exif/ExifReader.cs, src/ImageSharp/Metadata/Profiles/Exif/Tags/ExifTag.cs, src/ImageSharp/Metadata/Profiles/Exif/Values/ExifEncodedString.cs, tests/ImageSharp.Tests/Formats/WebP/WebpDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Webp/issues/Issue2906.webp
Fixes #2906 
A backport of #2943 for V3.
=> V3 Use EXIF byte order for EXIF encoded strings. 

src/ImageSharp/Formats/Webp/Lossless/BackwardReferenceEncoder.cs, src/ImageSharp/Formats/Webp/Lossless/CostModel.cs, src/ImageSharp/Formats/Webp/Lossless/HistogramEncoder.cs, src/ImageSharp/Formats/Webp/Lossless/PixOrCopy.cs, src/ImageSharp/Formats/Webp/Lossless/Vp8LBackwardRefs.cs, src/ImageSharp/Formats/Webp/Lossless/Vp8LEncoder.cs, src/ImageSharp/Formats/Webp/Lossless/Vp8LHistogram.cs, tests/ImageSharp.Tests/Formats/WebP/Vp8LHistogramTests.cs
=> V3 Backport : Reduce the number of memory allocations in lossless WebP encoder

src/ImageSharp/Formats/Gif/GifDecoderCore.cs, tests/ImageSharp.Tests/Formats/Gif/GifDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Gif/issues/issue_2953.gif
=> GIF: Check for end of stream when reading comments. 

src/ImageSharp/Formats/Gif/GifDecoderCore.cs, tests/ImageSharp.Tests/Formats/Gif/GifDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Gif/issues/issue_2953.gif
=> Backport V3 - GIF: Check for end of stream when reading comments. 

src/ImageSharp/Formats/Png/PngMetadata.cs
=> Do not store obsolete tRNS chunk data following processing.

.editorconfig
Updates the submodule to point at the version supporting new build requirements
See:
https://sixlabors.com/posts/licence-enforcement-changes/
=> Update to license enforcing submodule

src/ImageSharp/Formats/Tiff/Compression/Decompressors/LzwString.cs, tests/ImageSharp.Tests/Formats/Tiff/TiffDecoderTests.cs, tests/ImageSharp.Tests/TestImages.cs, tests/Images/Input/Tiff/Issues/Issue2983.tiff
This is a proposed fix for https://github.com/SixLabors/ImageSharp/issues/2983. The idea is to truncate a too-long string, rather than throw an exception. This allows ImageSharp to successfully load some problematic TIFF files.
=> When decoding a compressed TIFF, truncate a too-long string instead of throwing an exception
