src/ImageSharp/Drawing/Draw_Rectangle.cs
src/ImageSharp/Drawing/Fill_Rectangle.cs
src/ImageSharp/Drawing/Processors/DrawPathProcessor.cs
src/ImageSharp/Drawing/Processors/FillShapeProcessor.cs
src/ImageSharp/Drawing/Shapes/RectangularPolygon.cs
tests/ImageSharp.Benchmarks/Drawing/FillRectangle.cs
tests/ImageSharp.Tests/Drawing/PolygonTests.cs
tests/ImageSharp.Tests/Drawing/SolidPolygonTests.cs

A small improvement for when you want to draw simple rectangles

Add optimised Rectangular Polygon

---

tests/ImageSharp.Tests/Colors/ColorConstructorTests.cs
tests/ImageSharp.Tests/Colors/ColorEqualityTests.cs
tests/ImageSharp.Tests/Colors/ColorPackingTests.cs
tests/ImageSharp.Tests/Colors/PackedPixelTests.cs

* Added unit tests for color constructors
** Vector4
** Vector3
** 4 floats
** 3 floats
* Added tests for ==
* Added tests for !=
* Added tests for Equals with concrete object
* Added tests for ! Equals with concrete object
* Added tests for PackFromVector4 - ToVector4
🍰 🍰 🍰 🍰

Adding unit tests for color constructors. Adding tests for packing. Improving equality tests. 

---

src/ImageSharp/Colors/ColorspaceTransforms.cs
src/ImageSharp/Colors/Spaces/Bgra32.cs
src/ImageSharp/Colors/Spaces/CieLab.cs
src/ImageSharp/Colors/Spaces/CieXyz.cs
src/ImageSharp/Colors/Spaces/Cmyk.cs
src/ImageSharp/Colors/Spaces/Hsl.cs
src/ImageSharp/Colors/Spaces/Hsv.cs
src/ImageSharp/Colors/Spaces/IAlmostEquatable.cs
src/ImageSharp/Colors/Spaces/YCbCr.cs
tests/ImageSharp.Tests/Colors/ColorConversionTests.cs

Optimizing YCbCr to use a backing vector. Refactoring namespaces for Color Spaces.

---

src/ImageSharp/Colors/Spaces/Bgra32.cs
src/ImageSharp/Colors/Spaces/CieLab.cs
src/ImageSharp/Colors/Spaces/Cmyk.cs
src/ImageSharp/Colors/Spaces/Hsl.cs
src/ImageSharp/Colors/Spaces/Hsv.cs
src/ImageSharp/Colors/Spaces/YCbCr.cs

Making some constants static to reduce the number of allocations.

Reducing allocations in color spaces. 

---

.vscode/tasks.json
global.json
tests/ImageSharp.Benchmarks/Program.cs
tests/ImageSharp.Benchmarks/benchmark.sh
tests/ImageSharp.Benchmarks/project.json

The minimal changes required for the project to build and execute benchmarks on Linux with NetCore 1.1

Benchmark running on .NetCore1.1

---

src/ImageSharp/Formats/Jpeg/Components/Block8x8F.cs
src/ImageSharp/Formats/Jpeg/Components/DCT.cs

Mutlipling
Vector4 * scalar is the same as 
Vector4 * new Vector4(scalar)

Reduce register pressure

---

src/ImageSharp/Formats/Png/PngDecoderCore.cs
tests/ImageSharp.Tests/Formats/Png/PngDecoderTests.cs

Only throw exceptions when the CRC of a critical chunk is incorrect.

---

src/ImageSharp.Web/Caching/PhysicalFileSystemCache.cs
src/ImageSharp.Web/Middleware/ImageContext.cs
src/ImageSharp.Web/Resolvers/PhysicalFileSystemResolver.cs

These are not necessary in this case, and it's better not to.

Removing unnecessary async/await usage

---

src/ImageSharp.Drawing/ImageSharp.Drawing.csproj
src/ImageSharp/ImageSharp.csproj

Fix icon paths

---

README.md

I think it is important to provide links pointed to respective NuGet / MyGet package pages in README, so people can discover the project more easily.
These high resolution badges should be auto-updating to reflect the latest and greatest package versions.
Resolves #333

Updated README with package badges linked to install page (NuGet / MyGet)

---

README.md

Made several changes on `README.md` to make it up-to date, more compact and easier to follow:
- Removed the alpha disclaimer
- Badges: Removed: stars, forks, issues. Moved the rest to the top of the document so they do not distract the reader
- Added the *Questions?* point
- Moved the **Manual Build** point after the API description
- Moved the "self promotion" part of the API descrtiption to the start of the document
- Removed `Span<T>` stuff from the API description
- Added reference to our samples repository and to our beta blog post

Update & Cleanup README.md

---

tests/ImageSharp.Tests/Formats/Jpg/JpegProfilingBenchmarks.cs

Disable benchmark tests

---

tests/CodeCoverage/CodeCoverage.cmd

Creating a pull request to test if this resolves the codecov issue.

Clean the solution to force a rebuild with /p:codecov=true

---

src/ImageSharp/Formats/Jpeg/GolangPort/OrigJpegDecoderCore.cs

Removed invalid check reported in issue #394.

---

src/ImageSharp/Memory/Buffer2DExtensions.cs
src/ImageSharp/Processing/Processors/Transforms/ResamplingWeightedProcessor.Weights.cs
src/ImageSharp/Processing/Processors/Transforms/ResizeProcessor.cs

Fixing typos in comments in various types. Contribution of the year I guess :D.

Fixing typos in comments

---

src/ImageSharp/Formats/Png/Zlib/ZlibInflateStream.cs

Just a minor tweak to our Zlib inflate stream to reuse the buffer for consuming the CRC and Adler checksums. They are never actually used for anything so we can make the buffer private static.

Reuse buffer and fix error messaging

---

src/ImageSharp/MetaData/Profiles/Exif/ExifTag.cs

Fixed incorrect value in ExifTagDescription.

Fixed invalid value for description.

---

README.md

Refer to Contribution Guide from README.md

Refer to Contribution Guide from README.md

---

README.md
src/ImageSharp.Drawing/ImageSharp.Drawing.csproj
src/ImageSharp/ImageSharp.csproj

README.md: fix link [skip ci]

---

README.md
tests/ImageSharp.Benchmarks/Config.cs

Update the `Short.Config` used by our codec benchmarks to run against both Core and the CLR targets.

Benchmark both Core and CLR

---

src/ImageSharp/Common/Helpers/DebugGuard.cs
src/ImageSharp/Common/Helpers/Guard.cs

Fix copy-paste documentation mistakes. 
Besides that, I noticed that the DebugGuard has different methods than Guard. Didn't do anything with that but just letting you know.

Update documentation on Guard methods.

---

src/ImageSharp/Image.FromBytes.cs

@davidfowl [spotted](https://github.com/SixLabors/ImageSharp/pull/618#pullrequestreview-143844759) an allocation we don't need in `Image.DetectFormat(Configuration config, ReadOnlySpan<byte> data)` so this fixes that.

Use span directly for DetectFormat

---

src/ImageSharp/PixelFormats/Alpha8.cs
src/ImageSharp/PixelFormats/Argb32.cs
src/ImageSharp/PixelFormats/Bgr565.cs
src/ImageSharp/PixelFormats/Bgra32.cs
src/ImageSharp/PixelFormats/Bgra4444.cs
src/ImageSharp/PixelFormats/Bgra5551.cs
src/ImageSharp/PixelFormats/Byte4.cs
src/ImageSharp/PixelFormats/HalfSingle.cs
src/ImageSharp/PixelFormats/HalfVector2.cs
src/ImageSharp/PixelFormats/HalfVector4.cs
src/ImageSharp/PixelFormats/NormalizedByte2.cs
src/ImageSharp/PixelFormats/NormalizedByte4.cs
src/ImageSharp/PixelFormats/Rgba32.cs
src/ImageSharp/PixelFormats/Rgba64.cs
src/ImageSharp/PixelFormats/Short2.cs
src/ImageSharp/PixelFormats/Short4.cs

Optimizes the Equals & GetHashCode methods within PixelFormats.

Optimize Equals & GetHashCode methods within PixelFormats

---

src/ImageSharp/PixelFormats/PixelImplementations/Generated/Argb32.PixelOperations.Generated.cs
src/ImageSharp/PixelFormats/PixelImplementations/Generated/Argb32.PixelOperations.Generated.tt
src/ImageSharp/PixelFormats/PixelImplementations/Generated/Bgr24.PixelOperations.Generated.cs
src/ImageSharp/PixelFormats/PixelImplementations/Generated/Bgr24.PixelOperations.Generated.tt
src/ImageSharp/PixelFormats/PixelImplementations/Generated/Bgra32.PixelOperations.Generated.cs
src/ImageSharp/PixelFormats/PixelImplementations/Generated/Bgra32.PixelOperations.Generated.tt
src/ImageSharp/PixelFormats/PixelImplementations/Generated/Gray16.PixelOperations.Generated.cs
src/ImageSharp/PixelFormats/PixelImplementations/Generated/Gray16.PixelOperations.Generated.tt
src/ImageSharp/PixelFormats/PixelImplementations/Generated/Gray8.PixelOperations.Generated.cs
src/ImageSharp/PixelFormats/PixelImplementations/Generated/Gray8.PixelOperations.Generated.tt
src/ImageSharp/PixelFormats/PixelImplementations/Generated/Rgb24.PixelOperations.Generated.cs
src/ImageSharp/PixelFormats/PixelImplementations/Generated/Rgb24.PixelOperations.Generated.tt
src/ImageSharp/PixelFormats/PixelImplementations/Generated/Rgb48.PixelOperations.Generated.cs
src/ImageSharp/PixelFormats/PixelImplementations/Generated/Rgb48.PixelOperations.Generated.tt
src/ImageSharp/PixelFormats/PixelImplementations/Generated/Rgba32.PixelOperations.Generated.cs
src/ImageSharp/PixelFormats/PixelImplementations/Generated/Rgba32.PixelOperations.Generated.tt
src/ImageSharp/PixelFormats/PixelImplementations/Generated/Rgba64.PixelOperations.Generated.cs
src/ImageSharp/PixelFormats/PixelImplementations/Generated/Rgba64.PixelOperations.Generated.tt
src/ImageSharp/PixelFormats/PixelImplementations/Generated/_Common.ttinclude

This is whitespace cleanup in the templates and the generated code.

Replaced tabs with spaces.

---

tests/ImageSharp.Sandbox46/ImageSharp.Sandbox46.csproj
tests/ImageSharp.Tests/ImageSharp.Tests.csproj

Upgraded Magick.NET to the latest release.

---

tests/ImageSharp.Tests/Formats/Jpg/JpegDecoderTests.Images.cs

`MultiHuffmanBaseline394` was in the list twice.

Removed duplicate item from the list.

---

src/ImageSharp.Drawing/Processing/Processors/Text/DrawTextProcessor.cs
src/ImageSharp/ColorSpaces/Conversion/Implementation/Converters/CieXyzToHunterLabConverter.cs
src/ImageSharp/ColorSpaces/Conversion/Implementation/Converters/HunterLabToCieXyzConverter.cs
src/ImageSharp/Formats/Bmp/BmpDecoderCore.cs
src/ImageSharp/Formats/Gif/LzwEncoder.cs
src/ImageSharp/Formats/Jpeg/Components/Block8x8F.cs
src/ImageSharp/Formats/Jpeg/JpegDecoderCore.cs
src/ImageSharp/Formats/Jpeg/JpegEncoderCore.cs
src/ImageSharp/Formats/Png/PngEncoderCore.cs
src/ImageSharp/Formats/Png/PngScanlineProcessor.cs
src/ImageSharp/Image.FromBytes.cs
src/ImageSharp/Processing/Processors/Quantization/FrameQuantizerBase{TPixel}.cs
src/ImageSharp/Processing/ResizeHelper.cs

Small code optimizations, all reducing the operations to be done less often by reusing intermediate results instead of doing the same calculations multiple times.

Avoid doing the same thing multiple times

---

.github/CONTRIBUTING.md

- Basic info about test execution
- No one should try running tests in Debug mode on old frameworks

Add testing/debugging related info to CONTRIBUTING.md

---

.github/FUNDING.yml

With this file it is possible to display a "sponsor" button at the top of the project. Info on how to do that can be found here: https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository

Added funding file with a link to open collective.

---

src/ImageSharp.Drawing/Processing/PatternBrush.cs

Not sure if this is a redundancy or a bug?

remove patternVector in patternBrush

---

.github/CONTRIBUTING.md
CODE_OF_CONDUCT.md
README.md

Add code of conduct

---

src/ImageSharp/Metadata/Profiles/Exif/Tags/ExifTag.SignedRational.cs
src/ImageSharp/Metadata/Profiles/Exif/Values/ExifValues.cs

Fixes a couple of issues spotted post #1067

EXIF - Post review fixes

---

src/ImageSharp/ColorSpaces/Conversion/ColorSpaceConverter.LinearRgb.cs

Correct xml docs

---

Directory.Build.targets

Make MS Compilers Toolset private

---

.github/workflows/build-and-test.yml

Bump GitVersion action to the latest version to test build numbers

Bump Gitversion

---

src/ImageSharp/Formats/WebP/BitWriter/Vp8LBitWriter.cs
src/ImageSharp/Formats/WebP/Lossless/Vp8LEncoder.cs

Had a look at some of the lossless WebP work and tried to start resolving some of the TODOs with the lossless encoding. 
In its current state this is really just a PR to check I'm on track and not going off the rails before I invest too much time

Added Clone and Resize to Vp8LBitWriter

---

.github/FUNDING.yml
.github/workflows/build-and-test.yml
README.md

Adds Github Sponsors button and updates Open Collective avatars. Also configured actions to ignore trivial non-code changes.

Add GitHub Sponsors

---

src/ImageSharp/Formats/Tiff/Utils/TiffLzwDecoder.cs
tests/ImageSharp.Tests/Formats/Tiff/TiffDecoderTests.cs
tests/ImageSharp.Tests/TestImages.cs

As [discussed ](https://github.com/SixLabors/ImageSharp/issues/12#issuecomment-736764223) in #12

#12 Tiff specific fixes for LZW

---

tests/ImageSharp.Tests.ruleset

Ruleset path was incorrect. Fixes #1460

Use correct shared ruleset path. 

---

.gitattributes

Update shared infra structure to treat images file types by git lfs.

Update shared infra structure to treat image file types by git lfs

---

tests/ImageSharp.Benchmarks/benchmark.sh

Delete outdated benchmark.sh

---

.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/oss-bug-report.md

Config changes for the site. Frustrating that these have to be PR'd

Remove QA from config [skip ci]

---

src/ImageSharp/Metadata/ImageFrameMetadata.cs
src/ImageSharp/Metadata/ImageMetadata.cs

Correct IccProfile comment

---

src/ImageSharp/Processing/Extensions/Drawing/DrawImageExtensions.cs
src/ImageSharp/Processing/Processors/Drawing/DrawImageProcessor.cs
src/ImageSharp/Processing/Processors/Drawing/DrawImageProcessor{TPixelBg,TPixelFg}.cs
tests/ImageSharp.Tests/Drawing/DrawImageTests.cs
tests/Images/External/ReferenceOutput/Drawing/DrawImageTests/WorksWithDifferentBounds_10_10.png
tests/Images/External/ReferenceOutput/Drawing/DrawImageTests/WorksWithDifferentBounds_25_50.png
tests/Images/External/ReferenceOutput/Drawing/DrawImageTests/WorksWithDifferentBounds_50_25.png
tests/Images/External/ReferenceOutput/Drawing/DrawImageTests/WorksWithDifferentBounds_50_50.png

Fixes #2112 
In addition to the new overloads I've refactored the extensions to make each overload call another one to reduce the amount of refactoring work required in future updates and to improve test coverage.

Add DrawImage(Image, Point, Rectangle) method to the DrawImage processor

---

src/ImageSharp/Compression/Zlib/DeflateThrowHelper.cs
src/ImageSharp/Compression/Zlib/Deflater.cs
src/ImageSharp/Compression/Zlib/DeflaterEngine.cs
src/ImageSharp/Compression/Zlib/DeflaterHuffman.cs
src/ImageSharp/Compression/Zlib/DeflaterOutputStream.cs
src/ImageSharp/Compression/Zlib/DeflaterPendingBuffer.cs
src/ImageSharp/Compression/Zlib/ZlibDeflateStream.cs
src/ImageSharp/Compression/Zlib/ZlibInflateStream.cs
src/ImageSharp/Diagnostics/MemoryDiagnostics.cs
src/ImageSharp/Formats/Tiff/Compression/Decompressors/DeflateTiffCompression.cs

#2231
Removes Nullable disable from the zlib implementation

Remove nullable disable from zlib

---

src/ImageSharp/Formats/Gif/GifDecoderCore.cs
src/ImageSharp/Formats/Gif/GifEncoderCore.cs
src/ImageSharp/Image.Decode.cs
src/ImageSharp/Image.cs
src/ImageSharp/ImageInfo.cs
src/ImageSharp/Image{TPixel}.cs

remove nullable disable from format gif

---

src/ImageSharp/Formats/Pbm/PbmDecoderCore.cs

remove nullable disable from Format Pbm

---

src/ImageSharp/Formats/Tga/TgaDecoderCore.cs
src/ImageSharp/Formats/Tga/TgaEncoderCore.cs

Remove nullable disable from format tga

---

src/ImageSharp/IO/ChunkedMemoryStream.cs

Remove nullable disable from ChunkedMemoryStream

---

src/ImageSharp/Formats/Pbm/BinaryDecoder.cs
src/ImageSharp/Formats/Pbm/BufferedReadStreamExtensions.cs
src/ImageSharp/Formats/Pbm/PbmDecoderCore.cs
src/ImageSharp/Formats/Pbm/PlainDecoder.cs

Minor tweaks for cleaner code.

Follow up on post-merge discussions in #2551

---

src/ImageSharp/Formats/Webp/WebpFrameMetadata.cs

Backport: Fix WebP animation speed bug

---

src/ImageSharp/Formats/Png/PngDecoderCore.cs
src/ImageSharp/Processing/Processors/Drawing/DrawImageProcessor{TPixelBg,TPixelFg}.cs
tests/ImageSharp.Tests/Formats/Png/PngDecoderTests.cs
tests/ImageSharp.Tests/TestImages.cs
tests/Images/Input/Png/issues/Issue_2666.png

Adding v3.1.x fixes #2673 and #2674 into main.

Add v3.1.x fixes #2673 and #2674 into main.

---

src/ImageSharp/Formats/Png/PngDecoderCore.cs
src/ImageSharp/Formats/Png/PngEncoderCore.cs
src/ImageSharp/Formats/Png/PngMetadata.cs
src/ImageSharp/Formats/Png/PngScanlineProcessor.cs
tests/ImageSharp.Tests/Formats/Png/PngDecoderTests.cs
tests/ImageSharp.Tests/Formats/Png/PngEncoderTests.Chunks.cs
tests/ImageSharp.Tests/Formats/Png/PngEncoderTests.cs
tests/ImageSharp.Tests/Formats/Png/PngMetadataTests.cs
tests/ImageSharp.Tests/TestImages.cs
tests/Images/External/ReferenceOutput/PngDecoderTests/Decode_VerifyAllFrames_Rgba32_default-not-animated.png/00.png
tests/Images/External/ReferenceOutput/PngDecoderTests/Decode_VerifyAllFrames_Rgba32_default-not-animated.png/01.png
tests/Images/External/ReferenceOutput/PngDecoderTests/Decode_VerifyAllFrames_Rgba32_frame-offset.png/00.png
tests/Images/External/ReferenceOutput/PngDecoderTests/Decode_VerifyAllFrames_Rgba32_frame-offset.png/01.png
tests/Images/External/ReferenceOutput/PngDecoderTests/Decode_VerifyAllFrames_Rgba32_frame-offset.png/02.png
tests/Images/External/ReferenceOutput/PngDecoderTests/Decode_VerifyAllFrames_Rgba32_frame-offset.png/03.png
tests/Images/External/ReferenceOutput/PngDecoderTests/Decode_VerifyAllFrames_Rgba32_frame-offset.png/04.png
tests/Images/Input/Png/animated/default-not-animated.png
tests/Images/Input/Png/animated/frame-offset.png

Backport of PR #2710 to release/3.1.x

Backport APNG fix to release/3.1.x

---

src/ImageSharp/Formats/Png/Filters/AverageFilter.cs
src/ImageSharp/Formats/Png/Filters/SubFilter.cs
src/ImageSharp/Formats/Png/Filters/UpFilter.cs
src/ImageSharp/Formats/Png/PngEncoderCore.cs

V4 :  Fix filtering on PNG encode.

---

src/ImageSharp/Image.Decode.cs

Added the early return in this method when a format is found.

#2807 Add early return in InternalDetectFormat
